worker_processes 1;
error_log /dev/stdout warn;
pid /var/run/nginx-app-qrcode.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    
    access_log /dev/stdout;
    sendfile on;
    keepalive_timeout 65;
    
    server {
        listen 8200;
        server_name localhost;
        charset utf-8;
        
        root /workspace/ainative-app-qrcode;
        
        location / {
            try_files $uri $uri/ /index.html;
        }
        
        location /qrcode/ {
            alias /workspace/ainative-app/qrcode/;
            autoindex on;
        }
    }
}
