syntax = "proto3";

package shadow.v1;

import "google/api/annotations.proto";
//import "protoc-gen-openapiv2/options/annotations.proto";
import "validate/validate.proto";

option go_package = "gitlab.yc345.tv/backend/yanxue/api/shadow/v1;v1";

//商品
service Good {
  //商品-创建一条数据
  rpc CreateGood(CreateGoodReq) returns (CreateGoodReply) {
    option (google.api.http) = {
      post: "/yanxue/api/shadow/v1/good/create"
      body: "*"
    };
  }
  //商品-更新一条数据
  rpc UpdateGood(UpdateGoodReq) returns (UpdateGoodReply) {
    option (google.api.http) = {
      post: "/yanxue/api/shadow/v1/good/update"
      body: "*"
    };
  }
  //商品-修改商品状态
  rpc UpdateGoodStatus(UpdateGoodStatusReq) returns (UpdateGoodStatusReply) {
    option (google.api.http) = {
      post: "/yanxue/api/shadow/v1/good/updateGoodStatus"
      body: "*"
    };
  }
  //商品-单条数据查询
  rpc GetGoodInfo(GetGoodInfoReq) returns (GetGoodInfoReply) {
    option (google.api.http) = {get: "/yanxue/api/shadow/v1/good/info"};
  }
  //商品-列表数据查询
  rpc GetGoodList(GetGoodListReq) returns (GetGoodListReply) {
    option (google.api.http) = {
      post: "/yanxue/api/shadow/v1/good/list"
      body: "*"
    };
  }
}

//商品信息
message GoodInfo {
  string id = 1; // id
  string name = 2; // 名称
  repeated string mainImage = 3; // 主图(多张)
  repeated string detailImages = 4; // 详情图(多张)
  int32 price = 5; // 价格：单位分
  GoodContent content = 6; // 内容
  int32 sales = 7; // 销量
  string status = 8; // 状态
  string appointmentRules = 9; // 预约规则
  string channel = 10; // 渠道
  string channelId = 11; // 渠道Id
  string channelGoodId = 12; // 渠道商品Id
  string platformGoodId = 13; // 平台商品Id
  string createdAt = 14; // 开始时间
  string updatedAt = 15; // 更新时间
  string updatedBy = 16; // 操作人
  string updatedByName = 17; // 操作人名称
  bool isPushAppointmentInfo = 18; // 是否推送预约信息
  string goodType = 19; // 商品类型：单日营：single；多日营：multi
  repeated string label = 20; // 商品标签
  string purchaseAgreementName = 21; // 购买协议名称
  string purchaseAgreementLink = 22; // 购买协议链接
  int32 stock = 23; // 库存数量，NULL表示无限库存，>0表示有限库存
}

message CourseItem {
  string courseId = 1; // 课程Id
  string courseName = 2; // 课程名称
  string coursePrice = 3; // 课程价格
  bool isAppointment = 4; // 是否预约
}

message GoodCategory {
  string categoryId = 1; // 商品类别Id
  string categoryName = 2; // 商品类别名称
  int32 useTimes = 3; // 使用次数
  int32 alreadyAppointmentUseTimes = 4; // 已预约使用次数
  repeated CourseItem courses = 5; // 课程列表
}

message GoodContent {
  repeated GoodCategory goodCategories = 1; // 商品类别列表
}

//请求-商品-创建一条数据
message CreateGoodReq {
  string platformGoodId = 1 [(validate.rules).string = {min_len: 1}]; // 平台商品Id
  repeated string mainImages = 2 [(validate.rules).repeated = {
    min_items: 1 // 至少包含1张详情图
    items: {
      string: {min_len: 1}
    }
  }]; // 主图(多张)
  repeated string detailImages = 3 [(validate.rules).repeated = {
    min_items: 1 // 至少包含1张详情图
    items: {
      string: {min_len: 1}
    }
  }]; // 详情图(多张)
  int32 price = 4 [(validate.rules).int32 = {
    gt: 0 // 必须大于0
  }]; // 售价：单位分
  GoodContent content = 5 [(validate.rules).message = {required: true}]; // 内容
  string appointmentRules = 6; // 预约规则
  string channelId = 7 [(validate.rules).string = {min_len: 1}]; // 渠道Id
  string channelGoodId = 8; // 渠道商品Id
  bool isPushAppointmentInfo = 9; // 是否推送预约信息
  repeated string label = 10; // 商品标签
  string purchaseAgreementName = 11; // 购买协议名称
  string purchaseAgreementLink = 12; // 购买协议链接
  int32 stock = 13; // 库存数量，0表示无限库存，>0表示有限库存（可选字段，定金商品使用）
}

//响应-商品-创建一条数据
message CreateGoodReply {
  string id = 1; // id
}

//请求-商品-更新一条数据
message UpdateGoodReq {
  string id = 1 [(validate.rules).string = {min_len: 1}]; // id
  string platformGoodId = 2 [(validate.rules).string = {min_len: 1}]; // 平台商品Id
  repeated string mainImages = 3; // 主图(多张)
  repeated string detailImages = 4; // 详情图(多张)
  int32 price = 5; // 售价：单位分
  GoodContent content = 6; // 内容
  string appointmentRules = 7; // 预约规则
  string channelId = 8 [(validate.rules).string = {min_len: 1}]; // 渠道Id
  string channelGoodId = 9; // 渠道商品Id
  bool isPushAppointmentInfo = 10; // 是否推送预约信息
  repeated string label = 11; // 商品标签
  string purchaseAgreementName = 12; // 购买协议名称
  string purchaseAgreementLink = 13; // 购买协议链接
  int32 stock = 14; // 库存数量，0表示无限库存，>0表示有限库存（可选字段，定金商品使用）
}

//响应-商品-更新一条数据
message UpdateGoodReply {
  bool isSucceed = 1; // 是否成功
}

//请求-商品-修改商品状态
message UpdateGoodStatusReq {
  string id = 1 [(validate.rules).string = {min_len: 1}]; // id
  string status = 2 [(validate.rules).string = {min_len: 1}]; // 状态:delete:删除；putOn:上架；putOff:下架；pending:待上架
}

//响应-商品-修改商品状态
message UpdateGoodStatusReply {
  bool isSucceed = 1; // 是否成功
}

//请求-商品-单条数据查询
message GetGoodInfoReq {
  string id = 1 [(validate.rules).string = {min_len: 1}]; // id
}

//响应-商品-单条数据查询
message GetGoodInfoReply {
  GoodInfo info = 1;
}

//请求-商品-列表数据查询
message GetGoodListReq {
  int32 page = 1; //页码
  int32 pageSize = 2; //页数
  string platformGoodId = 3; // 平台商品Id
  string channelName = 4; // 渠道名称
  string goodName = 5; // 商品名称
  string status = 6; // 状态:delete:删除；putOn:上架；putOff:下架；pending:待上架
}

//响应-商品-列表数据查询
message GetGoodListReply {
  int32 total = 1; //总数
  repeated GoodInfo list = 2; // 列表数据
}
