syntax = "proto3";

package shadow.v1;

import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";
import "validate/validate.proto";

option go_package = "gitlab.yc345.tv/backend/yanxue/api/shadow/v1;v1";

// 变量的命名一律使用小驼峰命名法，例如：firstName、lastName等。
// 后缀定义:请求req,响应reply

// 部门模块
service SysDept {
  //部门-列表
  rpc SysDeptList(SysDeptListReq) returns (SysDeptListResp) {
    option (google.api.http) = {get: "/yanxue/shadow/v1/sysDept/list"};
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      parameters: {
        headers: {
          name: "Authorization"
          description: "TOKEN"
          type: STRING
          required: true
        }
      }
    };
  }

  //部门-保存
  rpc SysDeptStore(SysDeptStoreReq) returns (SysDeptStoreResp) {
    option (google.api.http) = {
      post: "/yanxue/shadow/v1/sysDept/store"
      body: "*"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      parameters: {
        headers: {
          name: "Authorization"
          description: "TOKEN"
          type: STRING
          required: true
        }
      }
    };
  }
  //部门-删除
  rpc SysDeptDel(SysDeptDelReq) returns (SysDeptDelResp) {
    option (google.api.http) = {
      post: "/yanxue/shadow/v1/sysDept/del"
      body: "*"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      parameters: {
        headers: {
          name: "Authorization"
          description: "TOKEN"
          type: STRING
          required: true
        }
      }
    };
  }
  //部门-修改权限状态
  rpc SysDeptStatus(SysDeptStatusReq) returns (SysDeptStatusResp) {
    option (google.api.http) = {
      post: "/yanxue/shadow/v1/sysDept/status"
      body: "*"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      parameters: {
        headers: {
          name: "Authorization"
          description: "TOKEN"
          type: STRING
          required: true
        }
      }
    };
  }
}

//部门-信息
message SysDeptInfo {
  string id = 1; // Id
  string pid = 2; // pid
  string type = 3; // 类型:root=根节点,child=子节点,leaf=叶子节点
  string name = 4; // 名称
  string remark = 5; // 备注
  int32 status = 6; // 状态:-1=禁用,1=启用
  string createdAt = 7; // 创建时间
  string updatedAt = 8; // 更新时间
  repeated SysDeptInfo children = 9; //子集
  bool isSelect = 10; // 是否可选
}

//部门-列表-请求
message SysDeptListReq {}

//部门-列表-响应
message SysDeptListResp {
  repeated SysDeptInfo list = 1; //列表
}

//部门-保存-请求
message SysDeptStoreReq {
  option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_schema) = {
    json_schema: {
      required: [
        "id",
        "pid",
        "type",
        "name",
        "remark",
        "status"
      ]
    }
  };
  string id = 1 [(validate.rules).string = {
    uuid: true
    ignore_empty: true
  }]; //Id
  string pid = 2 [(validate.rules).string = {
    uuid: true
    ignore_empty: true
  }]; //pid
  string type = 3 [(validate.rules).string = {
    in: [
      "root",
      "child",
      "leaf"
    ]
  }]; //类型:root=根节点,child=子节点,leaf=叶子节点
  string name = 4 [(validate.rules).string = {
    min_len: 1
    max_len: 50
  }]; //名称
  string remark = 5; //备注
  int32 status = 6 [(validate.rules).int32 = {
    in: [
      -1,
      1
    ]
  }]; //状态:-1=禁用,1=启用
}

//部门-保存-响应
message SysDeptStoreResp {
  string id = 1; // Id
}

//部门-删除-请求
message SysDeptDelReq {
  option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_schema) = {
    json_schema: {
      required: ["id"]
    }
  };
  string id = 1 [(validate.rules).string = {uuid: true}]; //Id
}

//部门-删除-响应
message SysDeptDelResp {}

//部门-修改权限状态-请求
message SysDeptStatusReq {
  option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_schema) = {
    json_schema: {
      required: [
        "id",
        "status"
      ]
    }
  };
  string id = 1 [(validate.rules).string.uuid = true]; // Id
  int32 status = 2 [(validate.rules).int32 = {
    in: [
      -1,
      1
    ]
  }]; // 状态:-1=禁用,1=启用
}

//部门-修改权限状态-响应
message SysDeptStatusResp {}
