syntax = "proto3";

package shadow.v1;

import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";
import "shadow/v1/sys_dept.proto";
import "shadow/v1/sys_permission.proto";
import "validate/validate.proto";

option go_package = "gitlab.yc345.tv/backend/yanxue/api/shadow/v1;v1";

// 变量的命名一律使用小驼峰命名法，例如：firstName、lastName等。
// 后缀定义:请求req,响应reply

// 管理员模块
service SysAdmin {
  //管理用户-列表
  rpc SysAdminList(SysAdminListReq) returns (SysAdminListReply) {
    option (google.api.http) = {get: "/yanxue/shadow/v1/sysAdminList"};
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      parameters: {
        headers: {
          name: "Authorization"
          description: "TOKEN"
          type: STRING
          required: true
        }
      }
    };
  }
  //管理用户-保存管理员
  rpc SysAdminStore(SysAdminStoreReq) returns (SysAdminStoreReply) {
    option (google.api.http) = {
      post: "/yanxue/shadow/v1/sysAdminStore"
      body: "*"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      parameters: {
        headers: {
          name: "Authorization"
          description: "TOKEN"
          type: STRING
          required: true
        }
      }
    };
  }
  //管理用户-修改状态
  rpc SysAdminStatus(SysAdminStatusReq) returns (SysAdminStatusReply) {
    option (google.api.http) = {
      post: "/yanxue/shadow/v1/sysAdminStatus"
      body: "*"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      parameters: {
        headers: {
          name: "Authorization"
          description: "TOKEN"
          type: STRING
          required: true
        }
      }
    };
  }
  //管理用户-修改密码
  rpc SysAdminChangePwd(SysAdminChangePwdReq) returns (SysAdminChangePwdReply) {
    option (google.api.http) = {
      post: "/yanxue/shadow/v1/sysAdminChangePwd"
      body: "*"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      parameters: {
        headers: {
          name: "Authorization"
          description: "TOKEN"
          type: STRING
          required: true
        }
      }
    };
  }
  // 管理用户-密码重置
  rpc SysAdminResetPwd(SysAdminResetPwdReq) returns (SysAdminResetPwdReply) {
    option (google.api.http) = {
      post: "/yanxue/shadow/v1/sysAdminResetPwd"
      body: "*"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      parameters: {
        headers: {
          name: "Authorization"
          description: "TOKEN"
          type: STRING
          required: true
        }
      }
    };
  }
  //管理用户-删除管理员
  rpc SysAdminDel(SysAdminDelReq) returns (SysAdminDelReply) {
    option (google.api.http) = {
      post: "/yanxue/shadow/v1/sysAdminDelReply"
      body: "*"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      parameters: {
        headers: {
          name: "Authorization"
          description: "TOKEN"
          type: STRING
          required: true
        }
      }
    };
  }
  //管理用户-获取当前登录管理员的信息
  rpc SysAdminInfo(SysAdminInfoReq) returns (SysAdminInfoReply) {
    option (google.api.http) = {get: "/yanxue/shadow/v1/sysAdminInfo"};
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      parameters: {
        headers: {
          name: "Authorization"
          description: "TOKEN"
          type: STRING
          required: true
        }
      }
    };
  }
  //管理用户-获取当前登录管理员的菜单权限数据
  rpc SysAdminPermission(SysAdminPermissionReq) returns (SysAdminPermissionReply) {
    option (google.api.http) = {get: "/yanxue/shadow/v1/sysAdminPermission"};
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      parameters: {
        headers: {
          name: "Authorization"
          description: "TOKEN"
          type: STRING
          required: true
        }
      }
    };
  }
  //管理用户-获取当前登录管理员的可见部门数据
  rpc SysAdminDeptList(SysAdminDeptListReq) returns (SysAdminDeptListReply) {
    option (google.api.http) = {get: "/yanxue/shadow/v1/sysAdminDeptList"};
  }
}

//角色信息
message SysAdminRoleInfo {
  string roleId = 1; //角色Id
  string roleName = 2; //角色名称
}

//部门信息
message SysAdminDeptInfo {
  string deptId = 1; //部门Id
  string deptName = 2; //部门名称
}
message SysAdminInfo {
  string id = 1; // Id
  string phone = 2; // 手机号
  string nickname = 3; // 昵称
  string avatar = 4; // 头像
  int32 status = 5; // 状态:-1=禁用,1=启用
  bool isChangePwd = 6; // 是否修改密码
  string createdAt = 7; // 创建时间
  string updatedAt = 8; // 更新时间
  repeated SysAdminRoleInfo roleList = 9; //角色集合
  repeated SysAdminDeptInfo deptList = 10; //部门集合
}

message SysAdminListReq {
  int32 page = 1 [(validate.rules).int32 = {gte: 1}]; //页码
  int32 pageSize = 2 [(validate.rules).int32 = {
    gte: 1
    lte: 1000
  }]; //页数
  string phone = 3; //手机号
  string nickname = 4; //昵称
  int32 status = 5; // 状态:-1=禁用,1=启用
  repeated string roleIds = 6; //角色Id集合
  repeated string deptIds = 7; //部门Id集合
}

//响应-管理员列表
message SysAdminListReply {
  int32 total = 1; //总数
  repeated SysAdminInfo list = 2; //管理员列表
}

//请求-管理员保存
message SysAdminStoreReq {
  string id = 1 [(validate.rules).string = {
    ignore_empty: true
    uuid: true
  }]; //ID
  string phone = 2 [(validate.rules).string = {pattern: "^[a-zA-Z0-9_-]{4,16}$"}]; // 手机号
  string nickname = 3 [(validate.rules).string = {
    min_len: 1
    max_len: 50
  }]; // 昵称
  string avatar = 5; // 头像
  int32 status = 6 [(validate.rules).int32 = {
    in: [
      -1,
      1
    ]
  }]; // 状态:-1=禁用,1=启用
  repeated string roleIds = 7; //角色Id集合
  repeated string deptIds = 8; //部门Id集合
}

//响应-管理员保存
message SysAdminStoreReply {
  string id = 1; //ID
}

//请求-管理员修改状态
message SysAdminStatusReq {
  string id = 1 [(validate.rules).string = {uuid: true}]; //Id
  int32 status = 2 [(validate.rules).int32 = {
    in: [
      -1,
      1
    ]
  }]; // 状态:-1=禁用,1=启用
}

//响应-管理员修改状态
message SysAdminStatusReply {}

//请求-管理员修改密码
message SysAdminChangePwdReq {
  string oldPassword = 1 [(validate.rules).string = {min_len: 6}]; //旧密码
  string password = 2 [(validate.rules).string = {min_len: 6}]; //新密码
}

//响应-管理员修改密码
message SysAdminChangePwdReply {}

//请求-管理员重置密码
message SysAdminResetPwdReq {
  string id = 1 [(validate.rules).string = {uuid: true}]; //Id
}

//响应-管理员重置密码
message SysAdminResetPwdReply {}

//请求-管理员删除
message SysAdminDelReq {
  string id = 1 [(validate.rules).string = {uuid: true}]; //Id
}

//响应-管理员删除
message SysAdminDelReply {}

//请求-管理员信息
message SysAdminInfoReq {}

//响应-管理员信息
message SysAdminInfoReply {
  SysAdminInfo info = 1; //管理员信息
}

//请求-管理员权限
message SysAdminPermissionReq {}

//响应-管理员权限
message SysAdminPermissionReply {
  repeated SysPermissionInfo list = 1; //权限列表
}

//请求-管理员部门列表
message SysAdminDeptListReq {}

//响应-管理员部门列表
message SysAdminDeptListReply {
  repeated SysDeptInfo list = 1; //部门列表
}
