syntax = "proto3";

package shadow.v1;

import "google/api/annotations.proto";

option go_package = "gitlab.yc345.tv/backend/yanxue/api/shadow/v1;v1";

//用户-消息
service UserMessage {
  //用户-消息-创建一条数据
  rpc CreateUserMessage(CreateUserMessageReq) returns (CreateUserMessageReply) {
    option (google.api.http) = {
      post: "/yanxue/api/shadow/v1/user_message/create"
      body: "*"
    };
  }
  //用户-消息-更新一条数据
  rpc UpdateUserMessage(UpdateUserMessageReq) returns (UpdateUserMessageReply) {
    option (google.api.http) = {
      post: "/yanxue/api/shadow/v1/user_message/update"
      body: "*"
    };
  }
  //用户-消息-删除多条数据
  rpc DeleteUserMessage(DeleteUserMessageReq) returns (DeleteUserMessageReply) {
    option (google.api.http) = {
      post: "/yanxue/api/shadow/v1/user_message/delete"
      body: "*"
    };
  }
  //用户-消息-单条数据查询
  rpc GetUserMessageInfo(GetUserMessageInfoReq) returns (GetUserMessageInfoReply) {
    option (google.api.http) = {get: "/yanxue/api/shadow/v1/user_message/info"};
  }
  //用户-消息-列表数据查询
  rpc GetUserMessageList(GetUserMessageListReq) returns (GetUserMessageListReply) {
    option (google.api.http) = {
      post: "/yanxue/api/shadow/v1/user_message/list"
      body: "*"
    };
  }
}

//用户-消息信息
message UserMessageInfo {
  string id = 1; // id
  string userId = 2; // 用户ID
  string category = 3; // 类别
  string type = 4; // 类型
  string data = 5; // 内容
  int32 status = 6; // 状态
  string createdAt = 7; // 创建时间
}

//请求-用户-消息-创建一条数据
message CreateUserMessageReq {
  string userId = 1; // 用户ID
  string category = 2; // 类别
  string type = 3; // 类型
  string data = 4; // 内容
  int32 status = 5; // 状态
}

//响应-用户-消息-创建一条数据
message CreateUserMessageReply {
  string id = 1; // id
}

//请求-用户-消息-更新一条数据
message UpdateUserMessageReq {
  string id = 1; // id
  string userId = 2; // 用户ID
  string category = 3; // 类别
  string type = 4; // 类型
  string data = 5; // 内容
  int32 status = 6; // 状态
}

//响应-用户-消息-更新一条数据
message UpdateUserMessageReply {}

//请求-用户-消息-删除多条数据
message DeleteUserMessageReq {
  repeated string ids = 1; // id集合
}

//响应-用户-消息-删除多条数据
message DeleteUserMessageReply {}

//请求-用户-消息-单条数据查询
message GetUserMessageInfoReq {
  string id = 1; // id
}

//响应-用户-消息-单条数据查询
message GetUserMessageInfoReply {
  UserMessageInfo info = 1;
}

//请求-用户-消息-列表数据查询
message GetUserMessageListReq {
  int32 page = 1; //页码
  int32 pageSize = 2; //页数
}

//响应-用户-消息-列表数据查询
message GetUserMessageListReply {
  int32 total = 1; //总数
  repeated UserMessageInfo list = 2; // 列表数据
}
