run:
  timeout: 5m  # 分析超时时间 默认：1m
  # 这个配置项具有以下可用的选项值：
  # normal：正常模式，表示直接下载所需要的模块依赖。
  # vendor：使用项目的 vendor 目录中的模块依赖。
  # readonly：只读模式，不下载任何模块依赖，只使用已经存在的依赖。
  modules-download-mode: readonly
  skip-dirs:
    - api
    - bin
    - internal/pkg/errcodec
    - internal/data/dao
    - internal/data/cache
    - internal/data/*_repo
    - internal/data/*_model
    - internal/data/*_dao
    - internal/data/*_type
  skip-files:
    - cmd/.*/wire_gen.go
    - internal/conf/*.pb.go
linters:
  #  disable-all: true  # 关闭所有的配置项
  fast: false  # 快速模式，有可能一些校验不会检测出来
  enable:
    - bodyclose
    - durationcheck
    - errcheck
    - exportloopref
    - govet
    - gosimple
    - gofmt
    - ineffassign
    - lll
    - typecheck
    - unused
    - gosec
  # 以下linter为可选配置，如果需要可以添加到enable中
  disable:
    - dogsled
    - gofumpt
    - goconst
    - goimports
    - gomnd
    - gocyclo
    - prealloc
    - revive
    - staticcheck
    - whitespace
    - wastedassign
    - unconvert
    - misspell
    - funlen
    - gochecknoinits
    - gocritic
    - goprintffuncname
    - nakedret
    - noctx
    - nolintlint
    - stylecheck
    - unparam

linters-settings:
  govet:
    # 用于检查变量声明是否发生了屏蔽（shadowing） 内部的变量声明了与外部相同名称的变量，导致外部变量无法被访问。这可能会导致代码的可读性和逻辑混乱，带来潜在的错误
    check-shadowing: true
  whitespace:
    # 函数签名后强制新行
    multi-func: true
  lll:
    # 单行代码长度检查
    line-length: 160
  goconst:
    # 忽略测试文件
    ignore-tests: true
  gocyclo:
    # recommend 10-20
    # 最小复杂度
    min-complexity: 50
  goimports:
    # 给指定的前缀分组
    local-prefixes: gitlab.yc345.tv/backend # Put imports beginning with prefix after 3rd-party packages
  misspell: # Finds commonly misspelled English words in comments
    # US or UK.  英式英语 or 美式英语
    locale: US
  dupl:
    # Tokens（DSL）阈值
    threshold: 300
  funlen:
    # 函数长度
    lines: 100
    # 函数声明（赋值语句、条件语句、循环语句、函数调用语句）
    statements: 100
  gocritic:
    enabled-tags:
      - diagnostic # 检测代码中各种错误的检查
      - experimental # 实验性的检查，未支持
      - opinionated # 标识有关代码风格和潜在问题的检查项
      - performance # 检测代码中潜在性能问题的检查
      - style # 查找代码中样式问题的检查
    disabled-checks:
      - dupImport # 检测不同别名下同一包的多次导入。 style
      - ifElseChain # 检测重复的 if-else 语句并建议将其替换为 switch 语句 style
      - octalLiteral # 检测旧式八进制文字。 style experimental opinionated
      - whyNoLint # 确保 //nolint 注释包含解释
      - hugeParam # 检测导致过多复制的参数。 func f(x [1024]int) {}
  gomnd:
    # don't include the "operation" and "assign"
    checks:
      - argument
      - case
      - condition
      - return
    # 忽略的数字
    ignored-numbers:
      - "0"
      - "1"
      - "2"
      - "3"
    # 忽略的函数
    ignored-functions:
      - strings.SplitN
  nolintlint:
    # 允许未使用变量
    allow-unused: false # report any unused nolint directives
    # 不需要解释
    require-explanation: false # don't require an explanation for nolint directives
    # 不要求指令具体说明要跳过哪个linters  //nolint //nolint:gosec
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped