syntax = "proto3";

package wechat.v1;

import "google/api/annotations.proto";
import "validate/validate.proto";

option go_package = "gitlab.yc345.tv/backend/yanxue/api/wechat/v1;v1";

//评价表
service Evaluation {
  //评价表-创建一条数据
  rpc CreateEvaluation(CreateEvaluationReq) returns (CreateEvaluationReply) {
    option (google.api.http) = {
      post: "/yanxue/wechat/v1/evaluation/create"
      body: "*"
    };
  }
}

//请求-评价表-创建一条数据
message CreateEvaluationReq {
  string appointmentId = 1 [(validate.rules).string = {min_len: 1}]; // 预约编号
  string parentName = 2 [(validate.rules).string = {min_len: 1}]; // 家长姓名
  string phone = 3 [(validate.rules).string = {min_len: 1}]; // 联系方式
  string childName = 4 [(validate.rules).string = {min_len: 1}]; // 孩子姓名
  string courseName = 5 [(validate.rules).string = {min_len: 1}]; // 课程名称
  string courseTime = 6 [(validate.rules).string = {min_len: 1}]; // 上课时间
  int32 totalScore = 7; // 总评分
  repeated string dimensionScore = 8; // 维度评分：每一行是"教学水平:5"这样的格式
  string feedBack = 9; // 反馈内容
  repeated string feedBackImage = 10; // 反馈图片
  repeated string evaluationLabel = 11; // 快速标签
}

//响应-评价表-创建一条数据
message CreateEvaluationReply {
  string id = 1; // id
}
