syntax = "proto3";

package wechat.v1;

import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";
import "validate/validate.proto";

option go_package = "gitlab.yc345.tv/backend/yanxue/api/wechat/v1;v1";

//用户绑定学生
service UserBindStudent {
  //用户绑定学生-创建一条数据
  rpc StoreUserBindStudent(StoreUserBindStudentReq) returns (StoreUserBindStudentReply) {
    option (google.api.http) = {
      post: "/yanxue/wechat/v1/user_bind_student/create"
      body: "*"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      parameters: {
        headers: {
          name: "Authorization"
          description: "TOKEN"
          type: STRING
          required: true
        }
      }
    };
  }
  //用户绑定学生-删除多条数据
  rpc DeleteUserBindStudent(DeleteUserBindStudentReq) returns (DeleteUserBindStudentReply) {
    option (google.api.http) = {
      post: "/yanxue/wechat/v1/user_bind_student/delete"
      body: "*"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      parameters: {
        headers: {
          name: "Authorization"
          description: "TOKEN"
          type: STRING
          required: true
        }
      }
    };
  }
  //用户绑定学生-列表数据查询
  rpc GetUserBindStudentList(GetUserBindStudentListReq) returns (GetUserBindStudentListReply) {
    option (google.api.http) = {
      post: "/yanxue/wechat/v1/user_bind_student/list"
      body: "*"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      parameters: {
        headers: {
          name: "Authorization"
          description: "TOKEN"
          type: STRING
          required: true
        }
      }
    };
  }
  //用户绑定学生-单条数据查询
  rpc GetUserBindStudentInfo(GetUserBindStudentInfoReq) returns (GetUserBindStudentInfoReply) {
    option (google.api.http) = {
      post: "/yanxue/wechat/v1/user_bind_student/info"
      body: "*"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      parameters: {
        headers: {
          name: "Authorization"
          description: "TOKEN"
          type: STRING
          required: true
        }
      }
    };
  }
}

//用户绑定学生信息
message UserBindStudentInfo {
  string id = 1; // id
  string studentIdentityCard = 2; // 学生-身份证
  string studentName = 3; // 学生-名称
  string studentSex = 4; // 学生-性别 男M 女F
  int32 studentAge = 5; // 学生-年龄 1-100
  string createdAt = 6; // 创建时间
  string updatedAt = 7; // 更新时间
}

//请求-用户绑定学生-创建一条数据
message StoreUserBindStudentReq {
  option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_schema) = {
    json_schema: {
      required: [
        "studentName",
        "studentSex",
        "studentAge"
      ]
    }
  };
  string id = 1; // id
  string studentName = 2 [(validate.rules).string.min_len = 1]; // 学生-名称
  string studentIdentityCard = 3; // 学生-身份证
  string studentSex = 4 [(validate.rules).string.min_len = 1]; // 学生-性别 男M 女F
  int32 studentAge = 5 [(validate.rules).int32 = {
    gte: 1
    lte: 100
  }]; // 学生-年龄
}

//响应-用户绑定学生-创建一条数据
message StoreUserBindStudentReply {
  string id = 1; // id
}

//请求-用户绑定学生-删除多条数据
message DeleteUserBindStudentReq {
  option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_schema) = {
    json_schema: {
      required: ["id"]
    }
  };
  string id = 1 [(validate.rules).string.min_len = 1]; // id
}

//响应-用户绑定学生-删除多条数据
message DeleteUserBindStudentReply {}

//请求-用户绑定学生-列表数据查询
message GetUserBindStudentListReq {}

//响应-用户绑定学生-列表数据查询
message GetUserBindStudentListReply {
  repeated UserBindStudentInfo list = 1; // 列表数据
}

//请求-用户绑定学生-单条数据查询
message GetUserBindStudentInfoReq {
  option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_schema) = {
    json_schema: {
      required: ["id"]
    }
  };
  string id = 1 [(validate.rules).string.min_len = 1]; // id
}

//响应-用户绑定学生-单条数据查询
message GetUserBindStudentInfoReply {
  UserBindStudentInfo info = 1; // 单条数据
}
