syntax = "proto3";

package wechat.v1;

import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";
import "validate/validate.proto";

option go_package = "gitlab.yc345.tv/backend/yanxue/api/wechat/v1;v1";

//用户优惠券记录表
service UserCoupon {
  //用户优惠券记录表-创建一条数据
  rpc CreateUserCoupon(CreateUserCouponReq) returns (CreateUserCouponReply) {
    option (google.api.http) = {
      post: "/yanxue/wechat/v1/user_coupon/create"
      body: "*"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      parameters: {
        headers: {
          name: "Authorization"
          description: "TOKEN"
          type: STRING
          required: true
        }
      }
    };
  }
  //用户优惠券记录表-更新一条数据
  rpc UpdateUserCoupon(UpdateUserCouponReq) returns (UpdateUserCouponReply) {
    option (google.api.http) = {
      post: "/yanxue/wechat/v1/user_coupon/update"
      body: "*"
    };
  }
  //用户优惠券记录表-查询我的优惠券列表
  rpc GetMyCouponList(GetMyCouponListReq) returns (GetMyCouponListReply) {
    option (google.api.http) = {get: "/yanxue/wechat/v1/user_coupon/getMyCouponList"};
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      parameters: {
        headers: {
          name: "Authorization"
          description: "TOKEN"
          type: STRING
          required: true
        }
      }
    };
  }
  //用户优惠券记录表-通过用户优惠券ID查询用户优惠券信息
  rpc GetUserCouponInfo(GetUserCouponInfoReq) returns (GetUserCouponInfoReply) {
    option (google.api.http) = {get: "/yanxue/wechat/v1/user_coupon/getUserCouponInfo"};
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      parameters: {
        headers: {
          name: "Authorization"
          description: "TOKEN"
          type: STRING
          required: true
        }
      }
    };
  }
}

//请求-查询用户优惠券信息
message GetUserCouponInfoReq {
  string userCouponId = 1 [(validate.rules).string = {uuid: true}]; // 用户优惠券ID
}

//响应-查询用户优惠券信息
message GetUserCouponInfoReply {
  MyCouponItem couponInfo = 1; // 优惠券信息
}

message MyCouponItem {
  string id = 1; // id
  string userId = 2; // 用户ID
  string couponId = 3; // 优惠券ID
  string couponName = 4; // 优惠券名称
  string status = 5; // 状态：已核销:used；未核销:unUsed；已过期:expired；已锁定:locked;
  string pushType = 6; // 推送方式：public:公开；private:私密
  string claimTime = 7; // 领取时间
  string expireTime = 8; // 过期时间
  string useTime = 9; // 使用时间
  int32 discountAmount = 10; // 优惠金额
  string couponType = 11; // 优惠券类型：common:通用；good:商品
  int32 minAmount = 12; // 门槛金额：为0则表示无门槛
}

//请求-我的优惠券列表
message GetMyCouponListReq {
  string goodId = 1; // 商品ID
}

//响应-我的优惠券列表
message GetMyCouponListReply {
  repeated MyCouponItem list = 1; // 优惠券列表
}

//请求-用户优惠券记录表-创建一条数据
message CreateUserCouponReq {
  string couponId = 1; // 优惠券ID
}

//响应-用户优惠券记录表-创建一条数据
message CreateUserCouponReply {
  string id = 1; // id
}

//请求-用户优惠券记录表-更新一条数据
message UpdateUserCouponReq {
  string id = 1; // id
  string status = 2; // 状态：已核销；未核销；已过期；
  string orderNumber = 3; // 订单编号
  string useTime = 4; // 使用时间
}

//响应-用户优惠券记录表-更新一条数据
message UpdateUserCouponReply {}
