syntax = "proto3";

package wechat.v1;

import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";
import "validate/validate.proto";

option go_package = "gitlab.yc345.tv/backend/yanxue/api/wechat/v1;v1";

//微信小程序码
service WxXcxQrcode {
  //微信小程序码-生成小程序码
  rpc GenerateWxXcxQrcode(GenerateWxXcxQrcodeReq) returns (GenerateWxXcxQrcodeReply) {
    option (google.api.http) = {
      post: "/yanxue/wechat/v1/wx_xcx_qrcode/generate"
      body: "*"
    };
  }
  //微信小程序码-根据token获取场景
  rpc GetWxXcxQrcodeScene(GetWxXcxQrcodeSceneReq) returns (GetWxXcxQrcodeSceneReply) {
    option (google.api.http) = {get: "/yanxue/wechat/v1/wx_xcx_qrcode/scene"};
  }
}

//请求-微信小程序码-创建一条数据
message GenerateWxXcxQrcodeReq {
  option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_schema) = {
    json_schema: {
      required: [
        "page",
        "scene"
      ]
    }
  };
  string page = 1 [(validate.rules).string.min_len = 1]; // 主页
  string scene = 2 [(validate.rules).string.min_len = 1]; // 场景
}

//响应-微信小程序码-创建一条数据
message GenerateWxXcxQrcodeReply {
  string token = 1; //token 32位
  string url = 2; // 图片地址
}

//请求-微信小程序码-单条数据查询
message GetWxXcxQrcodeSceneReq {
  string token = 1 [(validate.rules).string.min_len = 1]; //token 32位
}

//响应-微信小程序码-单条数据查询
message GetWxXcxQrcodeSceneReply {
  string page = 1; // 主页
  string scene = 2; // 场景
}
