// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: shadow/v1/contract.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GenerateContractByUserInfoReq with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GenerateContractByUserInfoReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GenerateContractByUserInfoReq with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// GenerateContractByUserInfoReqMultiError, or nil if none found.
func (m *GenerateContractByUserInfoReq) ValidateAll() error {
	return m.validate(true)
}

func (m *GenerateContractByUserInfoReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetCourseAppointmentId()) < 1 {
		err := GenerateContractByUserInfoReqValidationError{
			field:  "CourseAppointmentId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetParentName()) < 1 {
		err := GenerateContractByUserInfoReqValidationError{
			field:  "ParentName",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetParentPhone()) < 1 {
		err := GenerateContractByUserInfoReqValidationError{
			field:  "ParentPhone",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetChildName()) < 1 {
		err := GenerateContractByUserInfoReqValidationError{
			field:  "ChildName",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetChildId()) < 1 {
		err := GenerateContractByUserInfoReqValidationError{
			field:  "ChildId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetActivityStartDate()) < 1 {
		err := GenerateContractByUserInfoReqValidationError{
			field:  "ActivityStartDate",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetActivityEndDate()) < 1 {
		err := GenerateContractByUserInfoReqValidationError{
			field:  "ActivityEndDate",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetCost()) < 1 {
		err := GenerateContractByUserInfoReqValidationError{
			field:  "Cost",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetCostCapital()) < 1 {
		err := GenerateContractByUserInfoReqValidationError{
			field:  "CostCapital",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetPayEndDate()) < 1 {
		err := GenerateContractByUserInfoReqValidationError{
			field:  "PayEndDate",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GenerateContractByUserInfoReqMultiError(errors)
	}

	return nil
}

// GenerateContractByUserInfoReqMultiError is an error wrapping multiple
// validation errors returned by GenerateContractByUserInfoReq.ValidateAll()
// if the designated constraints aren't met.
type GenerateContractByUserInfoReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GenerateContractByUserInfoReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GenerateContractByUserInfoReqMultiError) AllErrors() []error { return m }

// GenerateContractByUserInfoReqValidationError is the validation error
// returned by GenerateContractByUserInfoReq.Validate if the designated
// constraints aren't met.
type GenerateContractByUserInfoReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GenerateContractByUserInfoReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GenerateContractByUserInfoReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GenerateContractByUserInfoReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GenerateContractByUserInfoReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GenerateContractByUserInfoReqValidationError) ErrorName() string {
	return "GenerateContractByUserInfoReqValidationError"
}

// Error satisfies the builtin error interface
func (e GenerateContractByUserInfoReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGenerateContractByUserInfoReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GenerateContractByUserInfoReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GenerateContractByUserInfoReqValidationError{}

// Validate checks the field values on GenerateContractByUserInfoReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GenerateContractByUserInfoReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GenerateContractByUserInfoReply with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// GenerateContractByUserInfoReplyMultiError, or nil if none found.
func (m *GenerateContractByUserInfoReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GenerateContractByUserInfoReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for AsyncTaskId

	if len(errors) > 0 {
		return GenerateContractByUserInfoReplyMultiError(errors)
	}

	return nil
}

// GenerateContractByUserInfoReplyMultiError is an error wrapping multiple
// validation errors returned by GenerateContractByUserInfoReply.ValidateAll()
// if the designated constraints aren't met.
type GenerateContractByUserInfoReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GenerateContractByUserInfoReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GenerateContractByUserInfoReplyMultiError) AllErrors() []error { return m }

// GenerateContractByUserInfoReplyValidationError is the validation error
// returned by GenerateContractByUserInfoReply.Validate if the designated
// constraints aren't met.
type GenerateContractByUserInfoReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GenerateContractByUserInfoReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GenerateContractByUserInfoReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GenerateContractByUserInfoReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GenerateContractByUserInfoReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GenerateContractByUserInfoReplyValidationError) ErrorName() string {
	return "GenerateContractByUserInfoReplyValidationError"
}

// Error satisfies the builtin error interface
func (e GenerateContractByUserInfoReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGenerateContractByUserInfoReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GenerateContractByUserInfoReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GenerateContractByUserInfoReplyValidationError{}

// Validate checks the field values on ExportContractListReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ExportContractListReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ExportContractListReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ExportContractListReqMultiError, or nil if none found.
func (m *ExportContractListReq) ValidateAll() error {
	return m.validate(true)
}

func (m *ExportContractListReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ChildName

	// no validation rules for ParentPhone

	// no validation rules for Topic

	// no validation rules for Status

	// no validation rules for ActivityStartDate

	if len(errors) > 0 {
		return ExportContractListReqMultiError(errors)
	}

	return nil
}

// ExportContractListReqMultiError is an error wrapping multiple validation
// errors returned by ExportContractListReq.ValidateAll() if the designated
// constraints aren't met.
type ExportContractListReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ExportContractListReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ExportContractListReqMultiError) AllErrors() []error { return m }

// ExportContractListReqValidationError is the validation error returned by
// ExportContractListReq.Validate if the designated constraints aren't met.
type ExportContractListReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ExportContractListReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ExportContractListReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ExportContractListReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ExportContractListReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ExportContractListReqValidationError) ErrorName() string {
	return "ExportContractListReqValidationError"
}

// Error satisfies the builtin error interface
func (e ExportContractListReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sExportContractListReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ExportContractListReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ExportContractListReqValidationError{}

// Validate checks the field values on ExportContractListReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ExportContractListReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ExportContractListReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ExportContractListReplyMultiError, or nil if none found.
func (m *ExportContractListReply) ValidateAll() error {
	return m.validate(true)
}

func (m *ExportContractListReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for DownloadUrl

	if len(errors) > 0 {
		return ExportContractListReplyMultiError(errors)
	}

	return nil
}

// ExportContractListReplyMultiError is an error wrapping multiple validation
// errors returned by ExportContractListReply.ValidateAll() if the designated
// constraints aren't met.
type ExportContractListReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ExportContractListReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ExportContractListReplyMultiError) AllErrors() []error { return m }

// ExportContractListReplyValidationError is the validation error returned by
// ExportContractListReply.Validate if the designated constraints aren't met.
type ExportContractListReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ExportContractListReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ExportContractListReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ExportContractListReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ExportContractListReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ExportContractListReplyValidationError) ErrorName() string {
	return "ExportContractListReplyValidationError"
}

// Error satisfies the builtin error interface
func (e ExportContractListReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sExportContractListReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ExportContractListReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ExportContractListReplyValidationError{}

// Validate checks the field values on QueryTopicListReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *QueryTopicListReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on QueryTopicListReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// QueryTopicListReqMultiError, or nil if none found.
func (m *QueryTopicListReq) ValidateAll() error {
	return m.validate(true)
}

func (m *QueryTopicListReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return QueryTopicListReqMultiError(errors)
	}

	return nil
}

// QueryTopicListReqMultiError is an error wrapping multiple validation errors
// returned by QueryTopicListReq.ValidateAll() if the designated constraints
// aren't met.
type QueryTopicListReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m QueryTopicListReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m QueryTopicListReqMultiError) AllErrors() []error { return m }

// QueryTopicListReqValidationError is the validation error returned by
// QueryTopicListReq.Validate if the designated constraints aren't met.
type QueryTopicListReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e QueryTopicListReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e QueryTopicListReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e QueryTopicListReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e QueryTopicListReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e QueryTopicListReqValidationError) ErrorName() string {
	return "QueryTopicListReqValidationError"
}

// Error satisfies the builtin error interface
func (e QueryTopicListReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sQueryTopicListReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = QueryTopicListReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = QueryTopicListReqValidationError{}

// Validate checks the field values on QueryTopicListReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *QueryTopicListReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on QueryTopicListReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// QueryTopicListReplyMultiError, or nil if none found.
func (m *QueryTopicListReply) ValidateAll() error {
	return m.validate(true)
}

func (m *QueryTopicListReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return QueryTopicListReplyMultiError(errors)
	}

	return nil
}

// QueryTopicListReplyMultiError is an error wrapping multiple validation
// errors returned by QueryTopicListReply.ValidateAll() if the designated
// constraints aren't met.
type QueryTopicListReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m QueryTopicListReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m QueryTopicListReplyMultiError) AllErrors() []error { return m }

// QueryTopicListReplyValidationError is the validation error returned by
// QueryTopicListReply.Validate if the designated constraints aren't met.
type QueryTopicListReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e QueryTopicListReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e QueryTopicListReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e QueryTopicListReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e QueryTopicListReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e QueryTopicListReplyValidationError) ErrorName() string {
	return "QueryTopicListReplyValidationError"
}

// Error satisfies the builtin error interface
func (e QueryTopicListReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sQueryTopicListReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = QueryTopicListReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = QueryTopicListReplyValidationError{}

// Validate checks the field values on QueryContractListReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *QueryContractListReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on QueryContractListReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// QueryContractListReqMultiError, or nil if none found.
func (m *QueryContractListReq) ValidateAll() error {
	return m.validate(true)
}

func (m *QueryContractListReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ChildName

	// no validation rules for ParentPhone

	// no validation rules for Topic

	// no validation rules for Status

	// no validation rules for ActivityStartDate

	// no validation rules for ContractType

	// no validation rules for Page

	// no validation rules for PageSize

	if len(errors) > 0 {
		return QueryContractListReqMultiError(errors)
	}

	return nil
}

// QueryContractListReqMultiError is an error wrapping multiple validation
// errors returned by QueryContractListReq.ValidateAll() if the designated
// constraints aren't met.
type QueryContractListReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m QueryContractListReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m QueryContractListReqMultiError) AllErrors() []error { return m }

// QueryContractListReqValidationError is the validation error returned by
// QueryContractListReq.Validate if the designated constraints aren't met.
type QueryContractListReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e QueryContractListReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e QueryContractListReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e QueryContractListReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e QueryContractListReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e QueryContractListReqValidationError) ErrorName() string {
	return "QueryContractListReqValidationError"
}

// Error satisfies the builtin error interface
func (e QueryContractListReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sQueryContractListReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = QueryContractListReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = QueryContractListReqValidationError{}

// Validate checks the field values on ContractItem with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ContractItem) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ContractItem with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ContractItemMultiError, or
// nil if none found.
func (m *ContractItem) ValidateAll() error {
	return m.validate(true)
}

func (m *ContractItem) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for SignFlowId

	// no validation rules for ParentName

	// no validation rules for ParentPhone

	// no validation rules for ChildName

	// no validation rules for ChildPhone

	// no validation rules for ChildId

	// no validation rules for UserSource

	// no validation rules for Topic

	// no validation rules for ActivityStartDate

	// no validation rules for ActivityEndDate

	// no validation rules for PurchaseChannel

	// no validation rules for ChildGrade

	// no validation rules for ChildGender

	// no validation rules for Cost

	// no validation rules for CostCapital

	// no validation rules for PayEndDate

	// no validation rules for ContractStatus

	// no validation rules for ContractLink

	// no validation rules for ContractType

	// no validation rules for CourseAppointmentId

	// no validation rules for CreatedAt

	// no validation rules for UpdatedAt

	if len(errors) > 0 {
		return ContractItemMultiError(errors)
	}

	return nil
}

// ContractItemMultiError is an error wrapping multiple validation errors
// returned by ContractItem.ValidateAll() if the designated constraints aren't met.
type ContractItemMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ContractItemMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ContractItemMultiError) AllErrors() []error { return m }

// ContractItemValidationError is the validation error returned by
// ContractItem.Validate if the designated constraints aren't met.
type ContractItemValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ContractItemValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ContractItemValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ContractItemValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ContractItemValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ContractItemValidationError) ErrorName() string { return "ContractItemValidationError" }

// Error satisfies the builtin error interface
func (e ContractItemValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sContractItem.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ContractItemValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ContractItemValidationError{}

// Validate checks the field values on QueryContractListReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *QueryContractListReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on QueryContractListReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// QueryContractListReplyMultiError, or nil if none found.
func (m *QueryContractListReply) ValidateAll() error {
	return m.validate(true)
}

func (m *QueryContractListReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Total

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, QueryContractListReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, QueryContractListReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return QueryContractListReplyValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return QueryContractListReplyMultiError(errors)
	}

	return nil
}

// QueryContractListReplyMultiError is an error wrapping multiple validation
// errors returned by QueryContractListReply.ValidateAll() if the designated
// constraints aren't met.
type QueryContractListReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m QueryContractListReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m QueryContractListReplyMultiError) AllErrors() []error { return m }

// QueryContractListReplyValidationError is the validation error returned by
// QueryContractListReply.Validate if the designated constraints aren't met.
type QueryContractListReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e QueryContractListReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e QueryContractListReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e QueryContractListReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e QueryContractListReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e QueryContractListReplyValidationError) ErrorName() string {
	return "QueryContractListReplyValidationError"
}

// Error satisfies the builtin error interface
func (e QueryContractListReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sQueryContractListReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = QueryContractListReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = QueryContractListReplyValidationError{}

// Validate checks the field values on QueryAsyncTaskResultReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *QueryAsyncTaskResultReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on QueryAsyncTaskResultReq with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// QueryAsyncTaskResultReqMultiError, or nil if none found.
func (m *QueryAsyncTaskResultReq) ValidateAll() error {
	return m.validate(true)
}

func (m *QueryAsyncTaskResultReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetTaskId()) < 1 {
		err := QueryAsyncTaskResultReqValidationError{
			field:  "TaskId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return QueryAsyncTaskResultReqMultiError(errors)
	}

	return nil
}

// QueryAsyncTaskResultReqMultiError is an error wrapping multiple validation
// errors returned by QueryAsyncTaskResultReq.ValidateAll() if the designated
// constraints aren't met.
type QueryAsyncTaskResultReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m QueryAsyncTaskResultReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m QueryAsyncTaskResultReqMultiError) AllErrors() []error { return m }

// QueryAsyncTaskResultReqValidationError is the validation error returned by
// QueryAsyncTaskResultReq.Validate if the designated constraints aren't met.
type QueryAsyncTaskResultReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e QueryAsyncTaskResultReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e QueryAsyncTaskResultReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e QueryAsyncTaskResultReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e QueryAsyncTaskResultReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e QueryAsyncTaskResultReqValidationError) ErrorName() string {
	return "QueryAsyncTaskResultReqValidationError"
}

// Error satisfies the builtin error interface
func (e QueryAsyncTaskResultReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sQueryAsyncTaskResultReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = QueryAsyncTaskResultReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = QueryAsyncTaskResultReqValidationError{}

// Validate checks the field values on QueryAsyncTaskResultReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *QueryAsyncTaskResultReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on QueryAsyncTaskResultReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// QueryAsyncTaskResultReplyMultiError, or nil if none found.
func (m *QueryAsyncTaskResultReply) ValidateAll() error {
	return m.validate(true)
}

func (m *QueryAsyncTaskResultReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TaskId

	// no validation rules for Status

	// no validation rules for ErrorInfo

	if len(errors) > 0 {
		return QueryAsyncTaskResultReplyMultiError(errors)
	}

	return nil
}

// QueryAsyncTaskResultReplyMultiError is an error wrapping multiple validation
// errors returned by QueryAsyncTaskResultReply.ValidateAll() if the
// designated constraints aren't met.
type QueryAsyncTaskResultReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m QueryAsyncTaskResultReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m QueryAsyncTaskResultReplyMultiError) AllErrors() []error { return m }

// QueryAsyncTaskResultReplyValidationError is the validation error returned by
// QueryAsyncTaskResultReply.Validate if the designated constraints aren't met.
type QueryAsyncTaskResultReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e QueryAsyncTaskResultReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e QueryAsyncTaskResultReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e QueryAsyncTaskResultReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e QueryAsyncTaskResultReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e QueryAsyncTaskResultReplyValidationError) ErrorName() string {
	return "QueryAsyncTaskResultReplyValidationError"
}

// Error satisfies the builtin error interface
func (e QueryAsyncTaskResultReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sQueryAsyncTaskResultReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = QueryAsyncTaskResultReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = QueryAsyncTaskResultReplyValidationError{}

// Validate checks the field values on ImportContractUserInfoByCsvFileReq with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *ImportContractUserInfoByCsvFileReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ImportContractUserInfoByCsvFileReq
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// ImportContractUserInfoByCsvFileReqMultiError, or nil if none found.
func (m *ImportContractUserInfoByCsvFileReq) ValidateAll() error {
	return m.validate(true)
}

func (m *ImportContractUserInfoByCsvFileReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetFileUrl()) < 1 {
		err := ImportContractUserInfoByCsvFileReqValidationError{
			field:  "FileUrl",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ImportContractUserInfoByCsvFileReqMultiError(errors)
	}

	return nil
}

// ImportContractUserInfoByCsvFileReqMultiError is an error wrapping multiple
// validation errors returned by
// ImportContractUserInfoByCsvFileReq.ValidateAll() if the designated
// constraints aren't met.
type ImportContractUserInfoByCsvFileReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ImportContractUserInfoByCsvFileReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ImportContractUserInfoByCsvFileReqMultiError) AllErrors() []error { return m }

// ImportContractUserInfoByCsvFileReqValidationError is the validation error
// returned by ImportContractUserInfoByCsvFileReq.Validate if the designated
// constraints aren't met.
type ImportContractUserInfoByCsvFileReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ImportContractUserInfoByCsvFileReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ImportContractUserInfoByCsvFileReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ImportContractUserInfoByCsvFileReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ImportContractUserInfoByCsvFileReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ImportContractUserInfoByCsvFileReqValidationError) ErrorName() string {
	return "ImportContractUserInfoByCsvFileReqValidationError"
}

// Error satisfies the builtin error interface
func (e ImportContractUserInfoByCsvFileReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sImportContractUserInfoByCsvFileReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ImportContractUserInfoByCsvFileReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ImportContractUserInfoByCsvFileReqValidationError{}

// Validate checks the field values on ImportContractUserInfoByCsvFileReply
// with the rules defined in the proto definition for this message. If any
// rules are violated, the first error encountered is returned, or nil if
// there are no violations.
func (m *ImportContractUserInfoByCsvFileReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ImportContractUserInfoByCsvFileReply
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// ImportContractUserInfoByCsvFileReplyMultiError, or nil if none found.
func (m *ImportContractUserInfoByCsvFileReply) ValidateAll() error {
	return m.validate(true)
}

func (m *ImportContractUserInfoByCsvFileReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for AsyncTaskId

	if len(errors) > 0 {
		return ImportContractUserInfoByCsvFileReplyMultiError(errors)
	}

	return nil
}

// ImportContractUserInfoByCsvFileReplyMultiError is an error wrapping multiple
// validation errors returned by
// ImportContractUserInfoByCsvFileReply.ValidateAll() if the designated
// constraints aren't met.
type ImportContractUserInfoByCsvFileReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ImportContractUserInfoByCsvFileReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ImportContractUserInfoByCsvFileReplyMultiError) AllErrors() []error { return m }

// ImportContractUserInfoByCsvFileReplyValidationError is the validation error
// returned by ImportContractUserInfoByCsvFileReply.Validate if the designated
// constraints aren't met.
type ImportContractUserInfoByCsvFileReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ImportContractUserInfoByCsvFileReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ImportContractUserInfoByCsvFileReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ImportContractUserInfoByCsvFileReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ImportContractUserInfoByCsvFileReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ImportContractUserInfoByCsvFileReplyValidationError) ErrorName() string {
	return "ImportContractUserInfoByCsvFileReplyValidationError"
}

// Error satisfies the builtin error interface
func (e ImportContractUserInfoByCsvFileReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sImportContractUserInfoByCsvFileReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ImportContractUserInfoByCsvFileReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ImportContractUserInfoByCsvFileReplyValidationError{}

// Validate checks the field values on UrgeSignFlowReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *UrgeSignFlowReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UrgeSignFlowReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UrgeSignFlowReqMultiError, or nil if none found.
func (m *UrgeSignFlowReq) ValidateAll() error {
	return m.validate(true)
}

func (m *UrgeSignFlowReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetSignFlowId()) < 1 {
		err := UrgeSignFlowReqValidationError{
			field:  "SignFlowId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetPsnAccount()) < 1 {
		err := UrgeSignFlowReqValidationError{
			field:  "PsnAccount",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return UrgeSignFlowReqMultiError(errors)
	}

	return nil
}

// UrgeSignFlowReqMultiError is an error wrapping multiple validation errors
// returned by UrgeSignFlowReq.ValidateAll() if the designated constraints
// aren't met.
type UrgeSignFlowReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UrgeSignFlowReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UrgeSignFlowReqMultiError) AllErrors() []error { return m }

// UrgeSignFlowReqValidationError is the validation error returned by
// UrgeSignFlowReq.Validate if the designated constraints aren't met.
type UrgeSignFlowReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UrgeSignFlowReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UrgeSignFlowReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UrgeSignFlowReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UrgeSignFlowReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UrgeSignFlowReqValidationError) ErrorName() string { return "UrgeSignFlowReqValidationError" }

// Error satisfies the builtin error interface
func (e UrgeSignFlowReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUrgeSignFlowReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UrgeSignFlowReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UrgeSignFlowReqValidationError{}

// Validate checks the field values on UrgeSignFlowReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *UrgeSignFlowReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UrgeSignFlowReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UrgeSignFlowReplyMultiError, or nil if none found.
func (m *UrgeSignFlowReply) ValidateAll() error {
	return m.validate(true)
}

func (m *UrgeSignFlowReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for IsSucceed

	if len(errors) > 0 {
		return UrgeSignFlowReplyMultiError(errors)
	}

	return nil
}

// UrgeSignFlowReplyMultiError is an error wrapping multiple validation errors
// returned by UrgeSignFlowReply.ValidateAll() if the designated constraints
// aren't met.
type UrgeSignFlowReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UrgeSignFlowReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UrgeSignFlowReplyMultiError) AllErrors() []error { return m }

// UrgeSignFlowReplyValidationError is the validation error returned by
// UrgeSignFlowReply.Validate if the designated constraints aren't met.
type UrgeSignFlowReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UrgeSignFlowReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UrgeSignFlowReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UrgeSignFlowReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UrgeSignFlowReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UrgeSignFlowReplyValidationError) ErrorName() string {
	return "UrgeSignFlowReplyValidationError"
}

// Error satisfies the builtin error interface
func (e UrgeSignFlowReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUrgeSignFlowReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UrgeSignFlowReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UrgeSignFlowReplyValidationError{}

// Validate checks the field values on StoreContractTemplateReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *StoreContractTemplateReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on StoreContractTemplateReq with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// StoreContractTemplateReqMultiError, or nil if none found.
func (m *StoreContractTemplateReq) ValidateAll() error {
	return m.validate(true)
}

func (m *StoreContractTemplateReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if utf8.RuneCountInString(m.GetTemplateName()) < 1 {
		err := StoreContractTemplateReqValidationError{
			field:  "TemplateName",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetTemplateUrl()) < 1 {
		err := StoreContractTemplateReqValidationError{
			field:  "TemplateUrl",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := _StoreContractTemplateReq_TemplateType_InLookup[m.GetTemplateType()]; !ok {
		err := StoreContractTemplateReqValidationError{
			field:  "TemplateType",
			reason: "value must be in list [1 2]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return StoreContractTemplateReqMultiError(errors)
	}

	return nil
}

// StoreContractTemplateReqMultiError is an error wrapping multiple validation
// errors returned by StoreContractTemplateReq.ValidateAll() if the designated
// constraints aren't met.
type StoreContractTemplateReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m StoreContractTemplateReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m StoreContractTemplateReqMultiError) AllErrors() []error { return m }

// StoreContractTemplateReqValidationError is the validation error returned by
// StoreContractTemplateReq.Validate if the designated constraints aren't met.
type StoreContractTemplateReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StoreContractTemplateReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StoreContractTemplateReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StoreContractTemplateReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StoreContractTemplateReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StoreContractTemplateReqValidationError) ErrorName() string {
	return "StoreContractTemplateReqValidationError"
}

// Error satisfies the builtin error interface
func (e StoreContractTemplateReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStoreContractTemplateReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StoreContractTemplateReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StoreContractTemplateReqValidationError{}

var _StoreContractTemplateReq_TemplateType_InLookup = map[int32]struct{}{
	1: {},
	2: {},
}

// Validate checks the field values on StoreContractTemplateReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *StoreContractTemplateReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on StoreContractTemplateReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// StoreContractTemplateReplyMultiError, or nil if none found.
func (m *StoreContractTemplateReply) ValidateAll() error {
	return m.validate(true)
}

func (m *StoreContractTemplateReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return StoreContractTemplateReplyMultiError(errors)
	}

	return nil
}

// StoreContractTemplateReplyMultiError is an error wrapping multiple
// validation errors returned by StoreContractTemplateReply.ValidateAll() if
// the designated constraints aren't met.
type StoreContractTemplateReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m StoreContractTemplateReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m StoreContractTemplateReplyMultiError) AllErrors() []error { return m }

// StoreContractTemplateReplyValidationError is the validation error returned
// by StoreContractTemplateReply.Validate if the designated constraints aren't met.
type StoreContractTemplateReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StoreContractTemplateReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StoreContractTemplateReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StoreContractTemplateReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StoreContractTemplateReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StoreContractTemplateReplyValidationError) ErrorName() string {
	return "StoreContractTemplateReplyValidationError"
}

// Error satisfies the builtin error interface
func (e StoreContractTemplateReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStoreContractTemplateReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StoreContractTemplateReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StoreContractTemplateReplyValidationError{}

// Validate checks the field values on UpdateContractTemplateStatusReq with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateContractTemplateStatusReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateContractTemplateStatusReq with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// UpdateContractTemplateStatusReqMultiError, or nil if none found.
func (m *UpdateContractTemplateStatusReq) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateContractTemplateStatusReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetId()) < 1 {
		err := UpdateContractTemplateStatusReqValidationError{
			field:  "Id",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Status

	if len(errors) > 0 {
		return UpdateContractTemplateStatusReqMultiError(errors)
	}

	return nil
}

// UpdateContractTemplateStatusReqMultiError is an error wrapping multiple
// validation errors returned by UpdateContractTemplateStatusReq.ValidateAll()
// if the designated constraints aren't met.
type UpdateContractTemplateStatusReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateContractTemplateStatusReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateContractTemplateStatusReqMultiError) AllErrors() []error { return m }

// UpdateContractTemplateStatusReqValidationError is the validation error
// returned by UpdateContractTemplateStatusReq.Validate if the designated
// constraints aren't met.
type UpdateContractTemplateStatusReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateContractTemplateStatusReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateContractTemplateStatusReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateContractTemplateStatusReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateContractTemplateStatusReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateContractTemplateStatusReqValidationError) ErrorName() string {
	return "UpdateContractTemplateStatusReqValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateContractTemplateStatusReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateContractTemplateStatusReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateContractTemplateStatusReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateContractTemplateStatusReqValidationError{}

// Validate checks the field values on UpdateContractTemplateStatusReply with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *UpdateContractTemplateStatusReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateContractTemplateStatusReply
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// UpdateContractTemplateStatusReplyMultiError, or nil if none found.
func (m *UpdateContractTemplateStatusReply) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateContractTemplateStatusReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for IsSucceed

	if len(errors) > 0 {
		return UpdateContractTemplateStatusReplyMultiError(errors)
	}

	return nil
}

// UpdateContractTemplateStatusReplyMultiError is an error wrapping multiple
// validation errors returned by
// UpdateContractTemplateStatusReply.ValidateAll() if the designated
// constraints aren't met.
type UpdateContractTemplateStatusReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateContractTemplateStatusReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateContractTemplateStatusReplyMultiError) AllErrors() []error { return m }

// UpdateContractTemplateStatusReplyValidationError is the validation error
// returned by UpdateContractTemplateStatusReply.Validate if the designated
// constraints aren't met.
type UpdateContractTemplateStatusReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateContractTemplateStatusReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateContractTemplateStatusReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateContractTemplateStatusReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateContractTemplateStatusReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateContractTemplateStatusReplyValidationError) ErrorName() string {
	return "UpdateContractTemplateStatusReplyValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateContractTemplateStatusReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateContractTemplateStatusReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateContractTemplateStatusReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateContractTemplateStatusReplyValidationError{}

// Validate checks the field values on QueryContractTemplateListReq with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *QueryContractTemplateListReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on QueryContractTemplateListReq with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// QueryContractTemplateListReqMultiError, or nil if none found.
func (m *QueryContractTemplateListReq) ValidateAll() error {
	return m.validate(true)
}

func (m *QueryContractTemplateListReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TemplateName

	// no validation rules for Page

	// no validation rules for PageSize

	if len(errors) > 0 {
		return QueryContractTemplateListReqMultiError(errors)
	}

	return nil
}

// QueryContractTemplateListReqMultiError is an error wrapping multiple
// validation errors returned by QueryContractTemplateListReq.ValidateAll() if
// the designated constraints aren't met.
type QueryContractTemplateListReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m QueryContractTemplateListReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m QueryContractTemplateListReqMultiError) AllErrors() []error { return m }

// QueryContractTemplateListReqValidationError is the validation error returned
// by QueryContractTemplateListReq.Validate if the designated constraints
// aren't met.
type QueryContractTemplateListReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e QueryContractTemplateListReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e QueryContractTemplateListReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e QueryContractTemplateListReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e QueryContractTemplateListReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e QueryContractTemplateListReqValidationError) ErrorName() string {
	return "QueryContractTemplateListReqValidationError"
}

// Error satisfies the builtin error interface
func (e QueryContractTemplateListReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sQueryContractTemplateListReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = QueryContractTemplateListReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = QueryContractTemplateListReqValidationError{}

// Validate checks the field values on ContractTemplateItem with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ContractTemplateItem) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ContractTemplateItem with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ContractTemplateItemMultiError, or nil if none found.
func (m *ContractTemplateItem) ValidateAll() error {
	return m.validate(true)
}

func (m *ContractTemplateItem) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for TemplateType

	// no validation rules for TemplateName

	// no validation rules for TemplateUrl

	// no validation rules for Status

	// no validation rules for CreatedAt

	// no validation rules for UpdatedAt

	// no validation rules for UpdatedBy

	// no validation rules for UpdatedByName

	if len(errors) > 0 {
		return ContractTemplateItemMultiError(errors)
	}

	return nil
}

// ContractTemplateItemMultiError is an error wrapping multiple validation
// errors returned by ContractTemplateItem.ValidateAll() if the designated
// constraints aren't met.
type ContractTemplateItemMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ContractTemplateItemMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ContractTemplateItemMultiError) AllErrors() []error { return m }

// ContractTemplateItemValidationError is the validation error returned by
// ContractTemplateItem.Validate if the designated constraints aren't met.
type ContractTemplateItemValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ContractTemplateItemValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ContractTemplateItemValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ContractTemplateItemValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ContractTemplateItemValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ContractTemplateItemValidationError) ErrorName() string {
	return "ContractTemplateItemValidationError"
}

// Error satisfies the builtin error interface
func (e ContractTemplateItemValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sContractTemplateItem.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ContractTemplateItemValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ContractTemplateItemValidationError{}

// Validate checks the field values on QueryContractTemplateListReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *QueryContractTemplateListReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on QueryContractTemplateListReply with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// QueryContractTemplateListReplyMultiError, or nil if none found.
func (m *QueryContractTemplateListReply) ValidateAll() error {
	return m.validate(true)
}

func (m *QueryContractTemplateListReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, QueryContractTemplateListReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, QueryContractTemplateListReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return QueryContractTemplateListReplyValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Total

	if len(errors) > 0 {
		return QueryContractTemplateListReplyMultiError(errors)
	}

	return nil
}

// QueryContractTemplateListReplyMultiError is an error wrapping multiple
// validation errors returned by QueryContractTemplateListReply.ValidateAll()
// if the designated constraints aren't met.
type QueryContractTemplateListReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m QueryContractTemplateListReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m QueryContractTemplateListReplyMultiError) AllErrors() []error { return m }

// QueryContractTemplateListReplyValidationError is the validation error
// returned by QueryContractTemplateListReply.Validate if the designated
// constraints aren't met.
type QueryContractTemplateListReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e QueryContractTemplateListReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e QueryContractTemplateListReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e QueryContractTemplateListReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e QueryContractTemplateListReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e QueryContractTemplateListReplyValidationError) ErrorName() string {
	return "QueryContractTemplateListReplyValidationError"
}

// Error satisfies the builtin error interface
func (e QueryContractTemplateListReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sQueryContractTemplateListReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = QueryContractTemplateListReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = QueryContractTemplateListReplyValidationError{}

// Validate checks the field values on RevokeSignFlowReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *RevokeSignFlowReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RevokeSignFlowReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RevokeSignFlowReqMultiError, or nil if none found.
func (m *RevokeSignFlowReq) ValidateAll() error {
	return m.validate(true)
}

func (m *RevokeSignFlowReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetSignFlowId()) < 1 {
		err := RevokeSignFlowReqValidationError{
			field:  "SignFlowId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetRevokeReason()) < 1 {
		err := RevokeSignFlowReqValidationError{
			field:  "RevokeReason",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return RevokeSignFlowReqMultiError(errors)
	}

	return nil
}

// RevokeSignFlowReqMultiError is an error wrapping multiple validation errors
// returned by RevokeSignFlowReq.ValidateAll() if the designated constraints
// aren't met.
type RevokeSignFlowReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RevokeSignFlowReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RevokeSignFlowReqMultiError) AllErrors() []error { return m }

// RevokeSignFlowReqValidationError is the validation error returned by
// RevokeSignFlowReq.Validate if the designated constraints aren't met.
type RevokeSignFlowReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RevokeSignFlowReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RevokeSignFlowReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RevokeSignFlowReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RevokeSignFlowReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RevokeSignFlowReqValidationError) ErrorName() string {
	return "RevokeSignFlowReqValidationError"
}

// Error satisfies the builtin error interface
func (e RevokeSignFlowReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRevokeSignFlowReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RevokeSignFlowReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RevokeSignFlowReqValidationError{}

// Validate checks the field values on RevokeSignFlowReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RevokeSignFlowReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RevokeSignFlowReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RevokeSignFlowReplyMultiError, or nil if none found.
func (m *RevokeSignFlowReply) ValidateAll() error {
	return m.validate(true)
}

func (m *RevokeSignFlowReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for IsSucceed

	if len(errors) > 0 {
		return RevokeSignFlowReplyMultiError(errors)
	}

	return nil
}

// RevokeSignFlowReplyMultiError is an error wrapping multiple validation
// errors returned by RevokeSignFlowReply.ValidateAll() if the designated
// constraints aren't met.
type RevokeSignFlowReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RevokeSignFlowReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RevokeSignFlowReplyMultiError) AllErrors() []error { return m }

// RevokeSignFlowReplyValidationError is the validation error returned by
// RevokeSignFlowReply.Validate if the designated constraints aren't met.
type RevokeSignFlowReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RevokeSignFlowReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RevokeSignFlowReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RevokeSignFlowReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RevokeSignFlowReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RevokeSignFlowReplyValidationError) ErrorName() string {
	return "RevokeSignFlowReplyValidationError"
}

// Error satisfies the builtin error interface
func (e RevokeSignFlowReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRevokeSignFlowReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RevokeSignFlowReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RevokeSignFlowReplyValidationError{}
