syntax = "proto3";

package shadow.v1;

import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";
import "validate/validate.proto";

option go_package = "gitlab.yc345.tv/backend/yanxue/api/shadow/v1;v1";

// 课程库存
service CourseStock {
  //课程库存-创建一条数据
  rpc CreateCourseStock(CreateCourseStockReq) returns (CreateCourseStockReply) {
    option (google.api.http) = {
      post: "/yanxue/api/shadow/v1/course_stock/create"
      body: "*"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      parameters: {
        headers: {
          name: "Authorization"
          description: "TOKEN"
          type: STRING
          required: true
        }
      }
    };
  }
  //课程库存-更新一条数据
  rpc UpdateCourseStock(UpdateCourseStockReq) returns (UpdateCourseStockReply) {
    option (google.api.http) = {
      post: "/yanxue/api/shadow/v1/course_stock/update"
      body: "*"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      parameters: {
        headers: {
          name: "Authorization"
          description: "TOKEN"
          type: STRING
          required: true
        }
      }
    };
  }
  //课程库存-更新一条数据状态
  rpc UpdateCourseStockStatus(UpdateCourseStockStatusReq) returns (UpdateCourseStockStatusReply) {
    option (google.api.http) = {
      post: "/yanxue/api/shadow/v1/course_stock/update_status"
      body: "*"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      parameters: {
        headers: {
          name: "Authorization"
          description: "TOKEN"
          type: STRING
          required: true
        }
      }
    };
  }
  //课程库存-删除多条数据
  rpc DeleteCourseStock(DeleteCourseStockReq) returns (DeleteCourseStockReply) {
    option (google.api.http) = {
      post: "/yanxue/api/shadow/v1/course_stock/delete"
      body: "*"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      parameters: {
        headers: {
          name: "Authorization"
          description: "TOKEN"
          type: STRING
          required: true
        }
      }
    };
  }
  //课程库存-单条数据查询
  rpc GetCourseStockInfo(GetCourseStockInfoReq) returns (GetCourseStockInfoReply) {
    option (google.api.http) = {get: "/yanxue/api/shadow/v1/course_stock/info"};
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      parameters: {
        headers: {
          name: "Authorization"
          description: "TOKEN"
          type: STRING
          required: true
        }
      }
    };
  }
  //课程库存-列表数据查询
  rpc GetCourseStockList(GetCourseStockListReq) returns (GetCourseStockListReply) {
    option (google.api.http) = {
      post: "/yanxue/api/shadow/v1/course_stock/list"
      body: "*"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      parameters: {
        headers: {
          name: "Authorization"
          description: "TOKEN"
          type: STRING
          required: true
        }
      }
    };
  }
  // 课程库存-通过课程查询可以预约的日期和时间段
  rpc GetCourseStockSelector(GetCourseStockSelectorReq) returns (GetCourseStockSelectorReply) {
    option (google.api.http) = {get: "/yanxue/api/shadow/v1/course_stock/selector"};
  }
  //课程库存-更新群聊二维码
  rpc UpdateCourseStockGroupQrCode(UpdateCourseStockGroupQrCodeReq) returns (UpdateCourseStockGroupQrCodeReply) {
    option (google.api.http) = {
      post: "/yanxue/api/shadow/v1/course_stock/updateGroupQrCode"
      body: "*"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      parameters: {
        headers: {
          name: "Authorization"
          description: "TOKEN"
          type: STRING
          required: true
        }
      }
    };
  }
}

//请求--更新一条数据
message UpdateCourseStockGroupQrCodeReq {
  string id = 1 [(validate.rules).string = {min_len: 1}]; // id
  string groupQrCode = 2 [(validate.rules).string = {min_len: 1}]; // 二维码
}

//响应--更新一条数据
message UpdateCourseStockGroupQrCodeReply {}

//课程库存-信息
message CourseStockInfo {
  string id = 1; // id
  string courseId = 2; // 课程Id
  string date = 3; // 课程日期 格式：2025-01-01
  string period = 4; // 课程时间 格式：10:00-12:00
  int32 stock = 5; // 库存
  string status = 6; // 状态 上架putOn 下架putOff
  string createdAt = 7; // 开始时间
  string updatedAt = 8; // 更新时间
  string updatedBy = 9; // 更新人
  string updatedByName = 10; // 更新人名称
  string courseName = 11; // 课程名称
  int32 stockSuccess = 12; // 已预约库存
  int32 stockRemain = 13; // 剩余库存
  string groupQrCode = 14; // 群聊二维码
}

//请求--创建一条数据
message CreateCourseStockReq {
  option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_schema) = {
    json_schema: {
      required: [
        "courseId",
        "dates",
        "periods",
        "stock"
      ]
    }
  };
  string courseId = 1 [(validate.rules).string = {min_len: 1}]; // 课程Id
  repeated string dates = 2 [(validate.rules).repeated = {min_items: 1}]; // 课程日期
  repeated string periods = 3; // 如果是单日营，课程时间 最少 1 个，最多 5 个
  int32 stock = 4 [(validate.rules).int32 = {gt: 0}]; // 库存
  string courseType = 5; // 课程类型：单日营：single;多日营：multi
}

//响应--创建一条数据
message CreateCourseStockReply {
  string id = 1; // id
}

//请求--更新一条数据
message UpdateCourseStockReq {
  option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_schema) = {
    json_schema: {
      required: [
        "id",
        "courseId",
        "date",
        "period",
        "stock"
      ]
    }
  };
  string id = 1 [(validate.rules).string = {min_len: 1}]; // id
  int32 stock = 3 [(validate.rules).int32 = {gte: 0}]; // 库存
}

//响应--更新一条数据
message UpdateCourseStockReply {}

//请求--更新一条数据状态
message UpdateCourseStockStatusReq {
  option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_schema) = {
    json_schema: {
      required: [
        "ids",
        "status"
      ]
    }
  };
  repeated string ids = 1 [(validate.rules).repeated = {min_items: 1}]; // id集合
  string status = 2 [(validate.rules).string = {min_len: 1}]; // 状态 上架putOn 下架putOff
}

//响应--更新一条数据状态
message UpdateCourseStockStatusReply {}

//请求--删除多条数据
message DeleteCourseStockReq {
  option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_schema) = {
    json_schema: {
      required: ["ids"]
    }
  };
  repeated string ids = 1 [(validate.rules).repeated = {min_items: 1}]; // id集合
}

//响应--删除多条数据
message DeleteCourseStockReply {}

//请求--单条数据查询
message GetCourseStockInfoReq {
  option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_schema) = {
    json_schema: {
      required: ["id"]
    }
  };
  string id = 1 [(validate.rules).string = {min_len: 1}]; // id
}

//响应--单条数据查询
message GetCourseStockInfoReply {
  CourseStockInfo info = 1;
}

//请求--列表数据查询
message GetCourseStockListReq {
  option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_schema) = {
    json_schema: {
      required: [
        "page",
        "pageSize"
      ]
    }
  };
  int32 page = 1 [(validate.rules).int32 = {gt: 0}]; //页码
  int32 pageSize = 2 [(validate.rules).int32 = {gt: 0}]; //页数
  string courseId = 3; // 课程Id
  string startDate = 4; // 开始日期 格式：2025-01-01
  string endDate = 5; // 结束日期 格式：2025-02-01
  string status = 6; // 状态 上架putOn 下架putOff
  string courseType = 7; // 课程类型：单日营：single;多日营：multi
}

//响应--列表数据查询
message GetCourseStockListReply {
  int32 total = 1; //总数
  repeated CourseStockInfo list = 2; // 列表数据
}

// 课程库存-通过课程查询可以预约的日期和时间段
message CourseStockSelectorItem {
  string date = 1; // 日期 格式：2025-01-01
  string period = 2; // 时间段 格式：10:00-12:00
  int32 stock = 3; // 库存
  int32 stockRemain = 4; // 剩余库存
}

// 请求--通过课程查询可以预约的日期和时间段
message GetCourseStockSelectorReq {
  option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_schema) = {
    json_schema: {
      required: ["courseId"]
    }
  };
  string courseId = 1 [(validate.rules).string = {min_len: 1}]; // 课程Id
  string startDate = 2; // 开始日期 格式：2025-01-01
  string endDate = 3; // 结束日期 格式：2025-02-01
}

// 响应--通过课程查询可以预约的日期和时间段
message GetCourseStockSelectorReply {
  repeated CourseStockSelectorItem items = 1; // 日期和时间段
}
