syntax = "proto3";

package shadow.v1;

import "google/api/annotations.proto";
import "validate/validate.proto";

option go_package = "gitlab.yc345.tv/backend/yanxue/api/shadow/v1;v1";

//评价模版
service EvaluationTemplate {
  //评价模版-创建一条数据
  rpc CreateEvaluationTemplate(CreateEvaluationTemplateReq) returns (CreateEvaluationTemplateReply) {
    option (google.api.http) = {
      post: "/yanxue/api/shadow/v1/evaluation_template/create"
      body: "*"
    };
  }
  //评价模版-更新一条数据
  rpc UpdateEvaluationTemplate(UpdateEvaluationTemplateReq) returns (UpdateEvaluationTemplateReply) {
    option (google.api.http) = {
      post: "/yanxue/api/shadow/v1/evaluation_template/update"
      body: "*"
    };
  }
  //评价模版-删除多条数据
  rpc DeleteEvaluationTemplate(DeleteEvaluationTemplateReq) returns (DeleteEvaluationTemplateReply) {
    option (google.api.http) = {
      post: "/yanxue/api/shadow/v1/evaluation_template/delete"
      body: "*"
    };
  }
  //评价模版-单条数据查询
  rpc GetEvaluationTemplateInfo(GetEvaluationTemplateInfoReq) returns (GetEvaluationTemplateInfoReply) {
    option (google.api.http) = {get: "/yanxue/api/shadow/v1/evaluation_template/info"};
  }
  //评价模版-列表数据查询
  rpc GetEvaluationTemplateList(GetEvaluationTemplateListReq) returns (GetEvaluationTemplateListReply) {
    option (google.api.http) = {
      post: "/yanxue/api/shadow/v1/evaluation_template/list"
      body: "*"
    };
  }
}

//评价模版信息
message EvaluationTemplateInfo {
  string id = 1; // id
  string templateName = 2; // 模版名称
  string evaluationObject = 3; // 评价对象
  string business = 4; // 所属业务
  repeated string evaluationDimension = 5; // 评价维度
  repeated string evaluationLabel = 6; // 评价标签
  string tips = 7; // 温馨提示
  string createdAt = 8; // 创建时间
  string updatedAt = 9; // 更新时间
  string updatedBy = 10; // 操作人
  string updatedByName = 11; // 操作人名称
}

//请求-评价模版-创建一条数据
message CreateEvaluationTemplateReq {
  string templateName = 1 [(validate.rules).string = {min_len: 1}]; // 模版名称
  string evaluationObject = 2 [(validate.rules).string = {min_len: 1}]; // 评价对象
  string business = 3 [(validate.rules).string = {min_len: 1}]; // 所属业务
  repeated string evaluationDimension = 4 [(validate.rules).repeated = {
    min_items: 1
    items: {
      string: {min_len: 1}
    }
  }]; // 评价维度
  repeated string evaluationLabel = 5 [(validate.rules).repeated = {
    min_items: 1
    items: {
      string: {min_len: 1}
    }
  }]; // 评价标签
  string tips = 6; // 温馨提示
}

//响应-评价模版-创建一条数据
message CreateEvaluationTemplateReply {
  string id = 1; // id
}

//请求-评价模版-更新一条数据
message UpdateEvaluationTemplateReq {
  string id = 1; // id
  string templateName = 2; // 模版名称
  string evaluationObject = 3; // 评价对象
  string business = 4; // 所属业务
  repeated string evaluationDimension = 5; // 评价维度
  repeated string evaluationLabel = 6; // 评价标签
  string tips = 7; // 温馨提示
}

//响应-评价模版-更新一条数据
message UpdateEvaluationTemplateReply {}

//请求-评价模版-删除一条数据
message DeleteEvaluationTemplateReq {
  string id = 1; // id
}

//响应-评价模版-删除一条数据
message DeleteEvaluationTemplateReply {}

//请求-评价模版-单条数据查询
message GetEvaluationTemplateInfoReq {
  string id = 1; // id
}

//响应-评价模版-单条数据查询
message GetEvaluationTemplateInfoReply {
  EvaluationTemplateInfo info = 1;
}

//请求-评价模版-列表数据查询
message GetEvaluationTemplateListReq {
  int32 page = 1; //页码
  int32 pageSize = 2; //页数
  string templateName = 3; // 模版名称
}

//响应-评价模版-列表数据查询
message GetEvaluationTemplateListReply {
  int32 total = 1; //总数
  repeated EvaluationTemplateInfo list = 2; // 列表数据
}
