// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: shadow/v1/good.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GoodInfo with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GoodInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GoodInfo with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GoodInfoMultiError, or nil
// if none found.
func (m *GoodInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *GoodInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Price

	if all {
		switch v := interface{}(m.GetContent()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GoodInfoValidationError{
					field:  "Content",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GoodInfoValidationError{
					field:  "Content",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetContent()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GoodInfoValidationError{
				field:  "Content",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Sales

	// no validation rules for Status

	// no validation rules for AppointmentRules

	// no validation rules for Channel

	// no validation rules for ChannelId

	// no validation rules for ChannelGoodId

	// no validation rules for PlatformGoodId

	// no validation rules for CreatedAt

	// no validation rules for UpdatedAt

	// no validation rules for UpdatedBy

	// no validation rules for UpdatedByName

	// no validation rules for IsPushAppointmentInfo

	// no validation rules for GoodType

	// no validation rules for PurchaseAgreementName

	// no validation rules for PurchaseAgreementLink

	// no validation rules for Stock

	if len(errors) > 0 {
		return GoodInfoMultiError(errors)
	}

	return nil
}

// GoodInfoMultiError is an error wrapping multiple validation errors returned
// by GoodInfo.ValidateAll() if the designated constraints aren't met.
type GoodInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GoodInfoMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GoodInfoMultiError) AllErrors() []error { return m }

// GoodInfoValidationError is the validation error returned by
// GoodInfo.Validate if the designated constraints aren't met.
type GoodInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GoodInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GoodInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GoodInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GoodInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GoodInfoValidationError) ErrorName() string { return "GoodInfoValidationError" }

// Error satisfies the builtin error interface
func (e GoodInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGoodInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GoodInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GoodInfoValidationError{}

// Validate checks the field values on CourseItem with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *CourseItem) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CourseItem with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in CourseItemMultiError, or
// nil if none found.
func (m *CourseItem) ValidateAll() error {
	return m.validate(true)
}

func (m *CourseItem) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for CourseId

	// no validation rules for CourseName

	// no validation rules for CoursePrice

	// no validation rules for IsAppointment

	if len(errors) > 0 {
		return CourseItemMultiError(errors)
	}

	return nil
}

// CourseItemMultiError is an error wrapping multiple validation errors
// returned by CourseItem.ValidateAll() if the designated constraints aren't met.
type CourseItemMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CourseItemMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CourseItemMultiError) AllErrors() []error { return m }

// CourseItemValidationError is the validation error returned by
// CourseItem.Validate if the designated constraints aren't met.
type CourseItemValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CourseItemValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CourseItemValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CourseItemValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CourseItemValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CourseItemValidationError) ErrorName() string { return "CourseItemValidationError" }

// Error satisfies the builtin error interface
func (e CourseItemValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCourseItem.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CourseItemValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CourseItemValidationError{}

// Validate checks the field values on GoodCategory with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GoodCategory) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GoodCategory with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GoodCategoryMultiError, or
// nil if none found.
func (m *GoodCategory) ValidateAll() error {
	return m.validate(true)
}

func (m *GoodCategory) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for CategoryId

	// no validation rules for CategoryName

	// no validation rules for UseTimes

	// no validation rules for AlreadyAppointmentUseTimes

	for idx, item := range m.GetCourses() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GoodCategoryValidationError{
						field:  fmt.Sprintf("Courses[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GoodCategoryValidationError{
						field:  fmt.Sprintf("Courses[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GoodCategoryValidationError{
					field:  fmt.Sprintf("Courses[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GoodCategoryMultiError(errors)
	}

	return nil
}

// GoodCategoryMultiError is an error wrapping multiple validation errors
// returned by GoodCategory.ValidateAll() if the designated constraints aren't met.
type GoodCategoryMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GoodCategoryMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GoodCategoryMultiError) AllErrors() []error { return m }

// GoodCategoryValidationError is the validation error returned by
// GoodCategory.Validate if the designated constraints aren't met.
type GoodCategoryValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GoodCategoryValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GoodCategoryValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GoodCategoryValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GoodCategoryValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GoodCategoryValidationError) ErrorName() string { return "GoodCategoryValidationError" }

// Error satisfies the builtin error interface
func (e GoodCategoryValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGoodCategory.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GoodCategoryValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GoodCategoryValidationError{}

// Validate checks the field values on GoodContent with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GoodContent) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GoodContent with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GoodContentMultiError, or
// nil if none found.
func (m *GoodContent) ValidateAll() error {
	return m.validate(true)
}

func (m *GoodContent) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetGoodCategories() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GoodContentValidationError{
						field:  fmt.Sprintf("GoodCategories[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GoodContentValidationError{
						field:  fmt.Sprintf("GoodCategories[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GoodContentValidationError{
					field:  fmt.Sprintf("GoodCategories[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GoodContentMultiError(errors)
	}

	return nil
}

// GoodContentMultiError is an error wrapping multiple validation errors
// returned by GoodContent.ValidateAll() if the designated constraints aren't met.
type GoodContentMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GoodContentMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GoodContentMultiError) AllErrors() []error { return m }

// GoodContentValidationError is the validation error returned by
// GoodContent.Validate if the designated constraints aren't met.
type GoodContentValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GoodContentValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GoodContentValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GoodContentValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GoodContentValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GoodContentValidationError) ErrorName() string { return "GoodContentValidationError" }

// Error satisfies the builtin error interface
func (e GoodContentValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGoodContent.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GoodContentValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GoodContentValidationError{}

// Validate checks the field values on CreateGoodReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *CreateGoodReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateGoodReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in CreateGoodReqMultiError, or
// nil if none found.
func (m *CreateGoodReq) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateGoodReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetPlatformGoodId()) < 1 {
		err := CreateGoodReqValidationError{
			field:  "PlatformGoodId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(m.GetMainImages()) < 1 {
		err := CreateGoodReqValidationError{
			field:  "MainImages",
			reason: "value must contain at least 1 item(s)",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	for idx, item := range m.GetMainImages() {
		_, _ = idx, item

		if utf8.RuneCountInString(item) < 1 {
			err := CreateGoodReqValidationError{
				field:  fmt.Sprintf("MainImages[%v]", idx),
				reason: "value length must be at least 1 runes",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if len(m.GetDetailImages()) < 1 {
		err := CreateGoodReqValidationError{
			field:  "DetailImages",
			reason: "value must contain at least 1 item(s)",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	for idx, item := range m.GetDetailImages() {
		_, _ = idx, item

		if utf8.RuneCountInString(item) < 1 {
			err := CreateGoodReqValidationError{
				field:  fmt.Sprintf("DetailImages[%v]", idx),
				reason: "value length must be at least 1 runes",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if m.GetPrice() <= 0 {
		err := CreateGoodReqValidationError{
			field:  "Price",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetContent() == nil {
		err := CreateGoodReqValidationError{
			field:  "Content",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetContent()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateGoodReqValidationError{
					field:  "Content",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateGoodReqValidationError{
					field:  "Content",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetContent()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateGoodReqValidationError{
				field:  "Content",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for AppointmentRules

	if utf8.RuneCountInString(m.GetChannelId()) < 1 {
		err := CreateGoodReqValidationError{
			field:  "ChannelId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for ChannelGoodId

	// no validation rules for IsPushAppointmentInfo

	// no validation rules for PurchaseAgreementName

	// no validation rules for PurchaseAgreementLink

	// no validation rules for Stock

	if len(errors) > 0 {
		return CreateGoodReqMultiError(errors)
	}

	return nil
}

// CreateGoodReqMultiError is an error wrapping multiple validation errors
// returned by CreateGoodReq.ValidateAll() if the designated constraints
// aren't met.
type CreateGoodReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateGoodReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateGoodReqMultiError) AllErrors() []error { return m }

// CreateGoodReqValidationError is the validation error returned by
// CreateGoodReq.Validate if the designated constraints aren't met.
type CreateGoodReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateGoodReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateGoodReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateGoodReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateGoodReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateGoodReqValidationError) ErrorName() string { return "CreateGoodReqValidationError" }

// Error satisfies the builtin error interface
func (e CreateGoodReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateGoodReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateGoodReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateGoodReqValidationError{}

// Validate checks the field values on CreateGoodReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *CreateGoodReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateGoodReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateGoodReplyMultiError, or nil if none found.
func (m *CreateGoodReply) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateGoodReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return CreateGoodReplyMultiError(errors)
	}

	return nil
}

// CreateGoodReplyMultiError is an error wrapping multiple validation errors
// returned by CreateGoodReply.ValidateAll() if the designated constraints
// aren't met.
type CreateGoodReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateGoodReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateGoodReplyMultiError) AllErrors() []error { return m }

// CreateGoodReplyValidationError is the validation error returned by
// CreateGoodReply.Validate if the designated constraints aren't met.
type CreateGoodReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateGoodReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateGoodReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateGoodReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateGoodReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateGoodReplyValidationError) ErrorName() string { return "CreateGoodReplyValidationError" }

// Error satisfies the builtin error interface
func (e CreateGoodReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateGoodReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateGoodReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateGoodReplyValidationError{}

// Validate checks the field values on UpdateGoodReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *UpdateGoodReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateGoodReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in UpdateGoodReqMultiError, or
// nil if none found.
func (m *UpdateGoodReq) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateGoodReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetId()) < 1 {
		err := UpdateGoodReqValidationError{
			field:  "Id",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetPlatformGoodId()) < 1 {
		err := UpdateGoodReqValidationError{
			field:  "PlatformGoodId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Price

	if all {
		switch v := interface{}(m.GetContent()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateGoodReqValidationError{
					field:  "Content",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateGoodReqValidationError{
					field:  "Content",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetContent()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateGoodReqValidationError{
				field:  "Content",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for AppointmentRules

	if utf8.RuneCountInString(m.GetChannelId()) < 1 {
		err := UpdateGoodReqValidationError{
			field:  "ChannelId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for ChannelGoodId

	// no validation rules for IsPushAppointmentInfo

	// no validation rules for PurchaseAgreementName

	// no validation rules for PurchaseAgreementLink

	// no validation rules for Stock

	if len(errors) > 0 {
		return UpdateGoodReqMultiError(errors)
	}

	return nil
}

// UpdateGoodReqMultiError is an error wrapping multiple validation errors
// returned by UpdateGoodReq.ValidateAll() if the designated constraints
// aren't met.
type UpdateGoodReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateGoodReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateGoodReqMultiError) AllErrors() []error { return m }

// UpdateGoodReqValidationError is the validation error returned by
// UpdateGoodReq.Validate if the designated constraints aren't met.
type UpdateGoodReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateGoodReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateGoodReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateGoodReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateGoodReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateGoodReqValidationError) ErrorName() string { return "UpdateGoodReqValidationError" }

// Error satisfies the builtin error interface
func (e UpdateGoodReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateGoodReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateGoodReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateGoodReqValidationError{}

// Validate checks the field values on UpdateGoodReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *UpdateGoodReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateGoodReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateGoodReplyMultiError, or nil if none found.
func (m *UpdateGoodReply) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateGoodReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for IsSucceed

	if len(errors) > 0 {
		return UpdateGoodReplyMultiError(errors)
	}

	return nil
}

// UpdateGoodReplyMultiError is an error wrapping multiple validation errors
// returned by UpdateGoodReply.ValidateAll() if the designated constraints
// aren't met.
type UpdateGoodReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateGoodReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateGoodReplyMultiError) AllErrors() []error { return m }

// UpdateGoodReplyValidationError is the validation error returned by
// UpdateGoodReply.Validate if the designated constraints aren't met.
type UpdateGoodReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateGoodReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateGoodReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateGoodReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateGoodReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateGoodReplyValidationError) ErrorName() string { return "UpdateGoodReplyValidationError" }

// Error satisfies the builtin error interface
func (e UpdateGoodReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateGoodReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateGoodReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateGoodReplyValidationError{}

// Validate checks the field values on UpdateGoodStatusReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateGoodStatusReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateGoodStatusReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateGoodStatusReqMultiError, or nil if none found.
func (m *UpdateGoodStatusReq) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateGoodStatusReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetId()) < 1 {
		err := UpdateGoodStatusReqValidationError{
			field:  "Id",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetStatus()) < 1 {
		err := UpdateGoodStatusReqValidationError{
			field:  "Status",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return UpdateGoodStatusReqMultiError(errors)
	}

	return nil
}

// UpdateGoodStatusReqMultiError is an error wrapping multiple validation
// errors returned by UpdateGoodStatusReq.ValidateAll() if the designated
// constraints aren't met.
type UpdateGoodStatusReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateGoodStatusReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateGoodStatusReqMultiError) AllErrors() []error { return m }

// UpdateGoodStatusReqValidationError is the validation error returned by
// UpdateGoodStatusReq.Validate if the designated constraints aren't met.
type UpdateGoodStatusReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateGoodStatusReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateGoodStatusReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateGoodStatusReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateGoodStatusReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateGoodStatusReqValidationError) ErrorName() string {
	return "UpdateGoodStatusReqValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateGoodStatusReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateGoodStatusReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateGoodStatusReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateGoodStatusReqValidationError{}

// Validate checks the field values on UpdateGoodStatusReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateGoodStatusReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateGoodStatusReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateGoodStatusReplyMultiError, or nil if none found.
func (m *UpdateGoodStatusReply) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateGoodStatusReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for IsSucceed

	if len(errors) > 0 {
		return UpdateGoodStatusReplyMultiError(errors)
	}

	return nil
}

// UpdateGoodStatusReplyMultiError is an error wrapping multiple validation
// errors returned by UpdateGoodStatusReply.ValidateAll() if the designated
// constraints aren't met.
type UpdateGoodStatusReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateGoodStatusReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateGoodStatusReplyMultiError) AllErrors() []error { return m }

// UpdateGoodStatusReplyValidationError is the validation error returned by
// UpdateGoodStatusReply.Validate if the designated constraints aren't met.
type UpdateGoodStatusReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateGoodStatusReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateGoodStatusReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateGoodStatusReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateGoodStatusReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateGoodStatusReplyValidationError) ErrorName() string {
	return "UpdateGoodStatusReplyValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateGoodStatusReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateGoodStatusReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateGoodStatusReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateGoodStatusReplyValidationError{}

// Validate checks the field values on GetGoodInfoReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetGoodInfoReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetGoodInfoReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetGoodInfoReqMultiError,
// or nil if none found.
func (m *GetGoodInfoReq) ValidateAll() error {
	return m.validate(true)
}

func (m *GetGoodInfoReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetId()) < 1 {
		err := GetGoodInfoReqValidationError{
			field:  "Id",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetGoodInfoReqMultiError(errors)
	}

	return nil
}

// GetGoodInfoReqMultiError is an error wrapping multiple validation errors
// returned by GetGoodInfoReq.ValidateAll() if the designated constraints
// aren't met.
type GetGoodInfoReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetGoodInfoReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetGoodInfoReqMultiError) AllErrors() []error { return m }

// GetGoodInfoReqValidationError is the validation error returned by
// GetGoodInfoReq.Validate if the designated constraints aren't met.
type GetGoodInfoReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetGoodInfoReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetGoodInfoReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetGoodInfoReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetGoodInfoReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetGoodInfoReqValidationError) ErrorName() string { return "GetGoodInfoReqValidationError" }

// Error satisfies the builtin error interface
func (e GetGoodInfoReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetGoodInfoReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetGoodInfoReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetGoodInfoReqValidationError{}

// Validate checks the field values on GetGoodInfoReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetGoodInfoReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetGoodInfoReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetGoodInfoReplyMultiError, or nil if none found.
func (m *GetGoodInfoReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetGoodInfoReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetInfo()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetGoodInfoReplyValidationError{
					field:  "Info",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetGoodInfoReplyValidationError{
					field:  "Info",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetInfo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetGoodInfoReplyValidationError{
				field:  "Info",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetGoodInfoReplyMultiError(errors)
	}

	return nil
}

// GetGoodInfoReplyMultiError is an error wrapping multiple validation errors
// returned by GetGoodInfoReply.ValidateAll() if the designated constraints
// aren't met.
type GetGoodInfoReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetGoodInfoReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetGoodInfoReplyMultiError) AllErrors() []error { return m }

// GetGoodInfoReplyValidationError is the validation error returned by
// GetGoodInfoReply.Validate if the designated constraints aren't met.
type GetGoodInfoReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetGoodInfoReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetGoodInfoReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetGoodInfoReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetGoodInfoReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetGoodInfoReplyValidationError) ErrorName() string { return "GetGoodInfoReplyValidationError" }

// Error satisfies the builtin error interface
func (e GetGoodInfoReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetGoodInfoReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetGoodInfoReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetGoodInfoReplyValidationError{}

// Validate checks the field values on GetGoodListReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetGoodListReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetGoodListReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetGoodListReqMultiError,
// or nil if none found.
func (m *GetGoodListReq) ValidateAll() error {
	return m.validate(true)
}

func (m *GetGoodListReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Page

	// no validation rules for PageSize

	// no validation rules for PlatformGoodId

	// no validation rules for ChannelName

	// no validation rules for GoodName

	// no validation rules for Status

	if len(errors) > 0 {
		return GetGoodListReqMultiError(errors)
	}

	return nil
}

// GetGoodListReqMultiError is an error wrapping multiple validation errors
// returned by GetGoodListReq.ValidateAll() if the designated constraints
// aren't met.
type GetGoodListReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetGoodListReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetGoodListReqMultiError) AllErrors() []error { return m }

// GetGoodListReqValidationError is the validation error returned by
// GetGoodListReq.Validate if the designated constraints aren't met.
type GetGoodListReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetGoodListReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetGoodListReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetGoodListReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetGoodListReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetGoodListReqValidationError) ErrorName() string { return "GetGoodListReqValidationError" }

// Error satisfies the builtin error interface
func (e GetGoodListReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetGoodListReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetGoodListReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetGoodListReqValidationError{}

// Validate checks the field values on GetGoodListReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetGoodListReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetGoodListReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetGoodListReplyMultiError, or nil if none found.
func (m *GetGoodListReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetGoodListReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Total

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetGoodListReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetGoodListReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetGoodListReplyValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetGoodListReplyMultiError(errors)
	}

	return nil
}

// GetGoodListReplyMultiError is an error wrapping multiple validation errors
// returned by GetGoodListReply.ValidateAll() if the designated constraints
// aren't met.
type GetGoodListReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetGoodListReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetGoodListReplyMultiError) AllErrors() []error { return m }

// GetGoodListReplyValidationError is the validation error returned by
// GetGoodListReply.Validate if the designated constraints aren't met.
type GetGoodListReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetGoodListReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetGoodListReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetGoodListReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetGoodListReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetGoodListReplyValidationError) ErrorName() string { return "GetGoodListReplyValidationError" }

// Error satisfies the builtin error interface
func (e GetGoodListReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetGoodListReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetGoodListReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetGoodListReplyValidationError{}
