// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.5.3
// - protoc             v3.21.9
// source: shadow/v1/order.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationOrderDouYinOrderInfoCallback = "/shadow.v1.Order/DouYinOrderInfoCallback"
const OperationOrderExportOrderList = "/shadow.v1.Order/ExportOrderList"
const OperationOrderExportWechatPayBill = "/shadow.v1.Order/ExportWechatPayBill"
const OperationOrderGetOrderGoodInfo = "/shadow.v1.Order/GetOrderGoodInfo"
const OperationOrderGetOrderList = "/shadow.v1.Order/GetOrderList"
const OperationOrderGetOrderListByPhone = "/shadow.v1.Order/GetOrderListByPhone"
const OperationOrderGetOrderVerificationProgressList = "/shadow.v1.Order/GetOrderVerificationProgressList"
const OperationOrderImportOrderInfoByCsvFile = "/shadow.v1.Order/ImportOrderInfoByCsvFile"
const OperationOrderImportPhoneByCsvFile = "/shadow.v1.Order/ImportPhoneByCsvFile"
const OperationOrderMiniProgramOrderRefund = "/shadow.v1.Order/MiniProgramOrderRefund"
const OperationOrderRefreshGoodType = "/shadow.v1.Order/RefreshGoodType"
const OperationOrderRefreshServiceStatus = "/shadow.v1.Order/RefreshServiceStatus"
const OperationOrderSplitSubOrder = "/shadow.v1.Order/SplitSubOrder"
const OperationOrderSyncDouYinCertificateId = "/shadow.v1.Order/SyncDouYinCertificateId"
const OperationOrderSyncDouYinSettleInfo = "/shadow.v1.Order/SyncDouYinSettleInfo"
const OperationOrderSyncHistoryOrderFee = "/shadow.v1.Order/SyncHistoryOrderFee"
const OperationOrderSyncWeiDianOrder = "/shadow.v1.Order/SyncWeiDianOrder"
const OperationOrderUpdateOrderDetail = "/shadow.v1.Order/UpdateOrderDetail"

type OrderHTTPServer interface {
	DouYinOrderInfoCallback(context.Context, *DouYinOrderInfoCallbackReq) (*DouYinOrderInfoCallbackReply, error)
	ExportOrderList(context.Context, *ExportOrderListReq) (*ExportOrderListReply, error)
	ExportWechatPayBill(context.Context, *ExportWechatPayBillReq) (*ExportWechatPayBillReply, error)
	GetOrderGoodInfo(context.Context, *GetOrderGoodInfoReq) (*GetOrderGoodInfoReply, error)
	GetOrderList(context.Context, *GetOrderListReq) (*GetOrderListReply, error)
	GetOrderListByPhone(context.Context, *GetOrderListByPhoneReq) (*GetOrderListByPhoneReply, error)
	GetOrderVerificationProgressList(context.Context, *GetOrderVerificationProgressListReq) (*GetOrderVerificationProgressListReply, error)
	ImportOrderInfoByCsvFile(context.Context, *ImportOrderInfoByCsvFileReq) (*ImportOrderInfoByCsvFileReply, error)
	ImportPhoneByCsvFile(context.Context, *ImportPhoneByCsvFileReq) (*ImportPhoneByCsvFileReply, error)
	MiniProgramOrderRefund(context.Context, *MiniProgramOrderRefundReq) (*MiniProgramOrderRefundReply, error)
	RefreshGoodType(context.Context, *RefreshGoodTypeReq) (*RefreshGoodTypeReply, error)
	RefreshServiceStatus(context.Context, *RefreshServiceStatusReq) (*RefreshServiceStatusReply, error)
	SplitSubOrder(context.Context, *SplitSubOrderReq) (*SplitSubOrderReply, error)
	SyncDouYinCertificateId(context.Context, *SyncDouYinCertificateIdReq) (*SyncDouYinCertificateIdReply, error)
	SyncDouYinSettleInfo(context.Context, *SyncDouYinSettleInfoReq) (*SyncDouYinSettleInfoReply, error)
	SyncHistoryOrderFee(context.Context, *SyncHistoryOrderFeeReq) (*SyncHistoryOrderFeeReply, error)
	SyncWeiDianOrder(context.Context, *SyncWeiDianOrderReq) (*SyncWeiDianOrderReply, error)
	UpdateOrderDetail(context.Context, *UpdateOrderDetailReq) (*UpdateOrderDetailReply, error)
}

func RegisterOrderHTTPServer(s *http.Server, srv OrderHTTPServer) {
	r := s.Route("/")
	r.POST("/yanxue/api/shadow/v1/order/getOrderList", _Order_GetOrderList0_HTTP_Handler(srv))
	r.POST("/yanxue/api/shadow/v1/order/importContractUserInfoByCsvFile", _Order_ImportOrderInfoByCsvFile0_HTTP_Handler(srv))
	r.POST("/yanxue/api/shadow/v1/order/exportOrderList", _Order_ExportOrderList0_HTTP_Handler(srv))
	r.POST("/yanxue/api/shadow/v1/order/goodinfo", _Order_GetOrderGoodInfo0_HTTP_Handler(srv))
	r.POST("/yanxue/api/shadow/v1/order/getOrderListByPhone", _Order_GetOrderListByPhone0_HTTP_Handler(srv))
	r.GET("/yanxue/api/shadow/v1/order/getOrderVerificationProgressList", _Order_GetOrderVerificationProgressList0_HTTP_Handler(srv))
	r.POST("/yanxue/api/shadow/v1/order/updateOrderDetail", _Order_UpdateOrderDetail0_HTTP_Handler(srv))
	r.POST("/yanxue/api/shadow/v1/order/importPhoneByCsvFile", _Order_ImportPhoneByCsvFile0_HTTP_Handler(srv))
	r.POST("/yanxue/api/shadow/v1/order/douYinOrderInfoCallback", _Order_DouYinOrderInfoCallback0_HTTP_Handler(srv))
	r.POST("/yanxue/api/shadow/v1/order/syncWeiDianOrder", _Order_SyncWeiDianOrder0_HTTP_Handler(srv))
	r.POST("/yanxue/api/shadow/v1/order/miniProgramOrderRefund", _Order_MiniProgramOrderRefund0_HTTP_Handler(srv))
	r.POST("/yanxue/api/shadow/v1/order/exportWechatPayBill", _Order_ExportWechatPayBill0_HTTP_Handler(srv))
	r.POST("/yanxue/api/shadow/v1/order/splitSubOrder", _Order_SplitSubOrder0_HTTP_Handler(srv))
	r.POST("/yanxue/api/shadow/v1/order/refreshServiceStatus", _Order_RefreshServiceStatus0_HTTP_Handler(srv))
	r.POST("/yanxue/api/shadow/v1/order/refreshGoodType", _Order_RefreshGoodType0_HTTP_Handler(srv))
	r.POST("/yanxue/api/shadow/v1/order/syncDouYinSettleInfo", _Order_SyncDouYinSettleInfo0_HTTP_Handler(srv))
	r.POST("/yanxue/api/shadow/v1/order/syncHistoryOrderFee", _Order_SyncHistoryOrderFee0_HTTP_Handler(srv))
	r.POST("/yanxue/api/shadow/v1/order/syncDouYinCertificateId", _Order_SyncDouYinCertificateId0_HTTP_Handler(srv))
}

func _Order_GetOrderList0_HTTP_Handler(srv OrderHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetOrderListReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderGetOrderList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetOrderList(ctx, req.(*GetOrderListReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetOrderListReply)
		return ctx.Result(200, reply)
	}
}

func _Order_ImportOrderInfoByCsvFile0_HTTP_Handler(srv OrderHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ImportOrderInfoByCsvFileReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderImportOrderInfoByCsvFile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ImportOrderInfoByCsvFile(ctx, req.(*ImportOrderInfoByCsvFileReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ImportOrderInfoByCsvFileReply)
		return ctx.Result(200, reply)
	}
}

func _Order_ExportOrderList0_HTTP_Handler(srv OrderHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ExportOrderListReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderExportOrderList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ExportOrderList(ctx, req.(*ExportOrderListReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ExportOrderListReply)
		return ctx.Result(200, reply)
	}
}

func _Order_GetOrderGoodInfo0_HTTP_Handler(srv OrderHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetOrderGoodInfoReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderGetOrderGoodInfo)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetOrderGoodInfo(ctx, req.(*GetOrderGoodInfoReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetOrderGoodInfoReply)
		return ctx.Result(200, reply)
	}
}

func _Order_GetOrderListByPhone0_HTTP_Handler(srv OrderHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetOrderListByPhoneReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderGetOrderListByPhone)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetOrderListByPhone(ctx, req.(*GetOrderListByPhoneReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetOrderListByPhoneReply)
		return ctx.Result(200, reply)
	}
}

func _Order_GetOrderVerificationProgressList0_HTTP_Handler(srv OrderHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetOrderVerificationProgressListReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderGetOrderVerificationProgressList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetOrderVerificationProgressList(ctx, req.(*GetOrderVerificationProgressListReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetOrderVerificationProgressListReply)
		return ctx.Result(200, reply)
	}
}

func _Order_UpdateOrderDetail0_HTTP_Handler(srv OrderHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateOrderDetailReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderUpdateOrderDetail)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateOrderDetail(ctx, req.(*UpdateOrderDetailReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateOrderDetailReply)
		return ctx.Result(200, reply)
	}
}

func _Order_ImportPhoneByCsvFile0_HTTP_Handler(srv OrderHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ImportPhoneByCsvFileReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderImportPhoneByCsvFile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ImportPhoneByCsvFile(ctx, req.(*ImportPhoneByCsvFileReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ImportPhoneByCsvFileReply)
		return ctx.Result(200, reply)
	}
}

func _Order_DouYinOrderInfoCallback0_HTTP_Handler(srv OrderHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DouYinOrderInfoCallbackReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderDouYinOrderInfoCallback)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DouYinOrderInfoCallback(ctx, req.(*DouYinOrderInfoCallbackReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DouYinOrderInfoCallbackReply)
		return ctx.Result(200, reply)
	}
}

func _Order_SyncWeiDianOrder0_HTTP_Handler(srv OrderHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SyncWeiDianOrderReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderSyncWeiDianOrder)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SyncWeiDianOrder(ctx, req.(*SyncWeiDianOrderReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SyncWeiDianOrderReply)
		return ctx.Result(200, reply)
	}
}

func _Order_MiniProgramOrderRefund0_HTTP_Handler(srv OrderHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in MiniProgramOrderRefundReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderMiniProgramOrderRefund)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.MiniProgramOrderRefund(ctx, req.(*MiniProgramOrderRefundReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*MiniProgramOrderRefundReply)
		return ctx.Result(200, reply)
	}
}

func _Order_ExportWechatPayBill0_HTTP_Handler(srv OrderHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ExportWechatPayBillReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderExportWechatPayBill)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ExportWechatPayBill(ctx, req.(*ExportWechatPayBillReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ExportWechatPayBillReply)
		return ctx.Result(200, reply)
	}
}

func _Order_SplitSubOrder0_HTTP_Handler(srv OrderHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SplitSubOrderReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderSplitSubOrder)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SplitSubOrder(ctx, req.(*SplitSubOrderReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SplitSubOrderReply)
		return ctx.Result(200, reply)
	}
}

func _Order_RefreshServiceStatus0_HTTP_Handler(srv OrderHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RefreshServiceStatusReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderRefreshServiceStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RefreshServiceStatus(ctx, req.(*RefreshServiceStatusReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RefreshServiceStatusReply)
		return ctx.Result(200, reply)
	}
}

func _Order_RefreshGoodType0_HTTP_Handler(srv OrderHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RefreshGoodTypeReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderRefreshGoodType)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RefreshGoodType(ctx, req.(*RefreshGoodTypeReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RefreshGoodTypeReply)
		return ctx.Result(200, reply)
	}
}

func _Order_SyncDouYinSettleInfo0_HTTP_Handler(srv OrderHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SyncDouYinSettleInfoReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderSyncDouYinSettleInfo)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SyncDouYinSettleInfo(ctx, req.(*SyncDouYinSettleInfoReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SyncDouYinSettleInfoReply)
		return ctx.Result(200, reply)
	}
}

func _Order_SyncHistoryOrderFee0_HTTP_Handler(srv OrderHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SyncHistoryOrderFeeReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderSyncHistoryOrderFee)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SyncHistoryOrderFee(ctx, req.(*SyncHistoryOrderFeeReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SyncHistoryOrderFeeReply)
		return ctx.Result(200, reply)
	}
}

func _Order_SyncDouYinCertificateId0_HTTP_Handler(srv OrderHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SyncDouYinCertificateIdReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderSyncDouYinCertificateId)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SyncDouYinCertificateId(ctx, req.(*SyncDouYinCertificateIdReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SyncDouYinCertificateIdReply)
		return ctx.Result(200, reply)
	}
}

type OrderHTTPClient interface {
	DouYinOrderInfoCallback(ctx context.Context, req *DouYinOrderInfoCallbackReq, opts ...http.CallOption) (rsp *DouYinOrderInfoCallbackReply, err error)
	ExportOrderList(ctx context.Context, req *ExportOrderListReq, opts ...http.CallOption) (rsp *ExportOrderListReply, err error)
	ExportWechatPayBill(ctx context.Context, req *ExportWechatPayBillReq, opts ...http.CallOption) (rsp *ExportWechatPayBillReply, err error)
	GetOrderGoodInfo(ctx context.Context, req *GetOrderGoodInfoReq, opts ...http.CallOption) (rsp *GetOrderGoodInfoReply, err error)
	GetOrderList(ctx context.Context, req *GetOrderListReq, opts ...http.CallOption) (rsp *GetOrderListReply, err error)
	GetOrderListByPhone(ctx context.Context, req *GetOrderListByPhoneReq, opts ...http.CallOption) (rsp *GetOrderListByPhoneReply, err error)
	GetOrderVerificationProgressList(ctx context.Context, req *GetOrderVerificationProgressListReq, opts ...http.CallOption) (rsp *GetOrderVerificationProgressListReply, err error)
	ImportOrderInfoByCsvFile(ctx context.Context, req *ImportOrderInfoByCsvFileReq, opts ...http.CallOption) (rsp *ImportOrderInfoByCsvFileReply, err error)
	ImportPhoneByCsvFile(ctx context.Context, req *ImportPhoneByCsvFileReq, opts ...http.CallOption) (rsp *ImportPhoneByCsvFileReply, err error)
	MiniProgramOrderRefund(ctx context.Context, req *MiniProgramOrderRefundReq, opts ...http.CallOption) (rsp *MiniProgramOrderRefundReply, err error)
	RefreshGoodType(ctx context.Context, req *RefreshGoodTypeReq, opts ...http.CallOption) (rsp *RefreshGoodTypeReply, err error)
	RefreshServiceStatus(ctx context.Context, req *RefreshServiceStatusReq, opts ...http.CallOption) (rsp *RefreshServiceStatusReply, err error)
	SplitSubOrder(ctx context.Context, req *SplitSubOrderReq, opts ...http.CallOption) (rsp *SplitSubOrderReply, err error)
	SyncDouYinCertificateId(ctx context.Context, req *SyncDouYinCertificateIdReq, opts ...http.CallOption) (rsp *SyncDouYinCertificateIdReply, err error)
	SyncDouYinSettleInfo(ctx context.Context, req *SyncDouYinSettleInfoReq, opts ...http.CallOption) (rsp *SyncDouYinSettleInfoReply, err error)
	SyncHistoryOrderFee(ctx context.Context, req *SyncHistoryOrderFeeReq, opts ...http.CallOption) (rsp *SyncHistoryOrderFeeReply, err error)
	SyncWeiDianOrder(ctx context.Context, req *SyncWeiDianOrderReq, opts ...http.CallOption) (rsp *SyncWeiDianOrderReply, err error)
	UpdateOrderDetail(ctx context.Context, req *UpdateOrderDetailReq, opts ...http.CallOption) (rsp *UpdateOrderDetailReply, err error)
}

type OrderHTTPClientImpl struct {
	cc *http.Client
}

func NewOrderHTTPClient(client *http.Client) OrderHTTPClient {
	return &OrderHTTPClientImpl{client}
}

func (c *OrderHTTPClientImpl) DouYinOrderInfoCallback(ctx context.Context, in *DouYinOrderInfoCallbackReq, opts ...http.CallOption) (*DouYinOrderInfoCallbackReply, error) {
	var out DouYinOrderInfoCallbackReply
	pattern := "/yanxue/api/shadow/v1/order/douYinOrderInfoCallback"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOrderDouYinOrderInfoCallback))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *OrderHTTPClientImpl) ExportOrderList(ctx context.Context, in *ExportOrderListReq, opts ...http.CallOption) (*ExportOrderListReply, error) {
	var out ExportOrderListReply
	pattern := "/yanxue/api/shadow/v1/order/exportOrderList"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOrderExportOrderList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *OrderHTTPClientImpl) ExportWechatPayBill(ctx context.Context, in *ExportWechatPayBillReq, opts ...http.CallOption) (*ExportWechatPayBillReply, error) {
	var out ExportWechatPayBillReply
	pattern := "/yanxue/api/shadow/v1/order/exportWechatPayBill"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOrderExportWechatPayBill))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *OrderHTTPClientImpl) GetOrderGoodInfo(ctx context.Context, in *GetOrderGoodInfoReq, opts ...http.CallOption) (*GetOrderGoodInfoReply, error) {
	var out GetOrderGoodInfoReply
	pattern := "/yanxue/api/shadow/v1/order/goodinfo"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOrderGetOrderGoodInfo))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *OrderHTTPClientImpl) GetOrderList(ctx context.Context, in *GetOrderListReq, opts ...http.CallOption) (*GetOrderListReply, error) {
	var out GetOrderListReply
	pattern := "/yanxue/api/shadow/v1/order/getOrderList"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOrderGetOrderList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *OrderHTTPClientImpl) GetOrderListByPhone(ctx context.Context, in *GetOrderListByPhoneReq, opts ...http.CallOption) (*GetOrderListByPhoneReply, error) {
	var out GetOrderListByPhoneReply
	pattern := "/yanxue/api/shadow/v1/order/getOrderListByPhone"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOrderGetOrderListByPhone))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *OrderHTTPClientImpl) GetOrderVerificationProgressList(ctx context.Context, in *GetOrderVerificationProgressListReq, opts ...http.CallOption) (*GetOrderVerificationProgressListReply, error) {
	var out GetOrderVerificationProgressListReply
	pattern := "/yanxue/api/shadow/v1/order/getOrderVerificationProgressList"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationOrderGetOrderVerificationProgressList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *OrderHTTPClientImpl) ImportOrderInfoByCsvFile(ctx context.Context, in *ImportOrderInfoByCsvFileReq, opts ...http.CallOption) (*ImportOrderInfoByCsvFileReply, error) {
	var out ImportOrderInfoByCsvFileReply
	pattern := "/yanxue/api/shadow/v1/order/importContractUserInfoByCsvFile"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOrderImportOrderInfoByCsvFile))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *OrderHTTPClientImpl) ImportPhoneByCsvFile(ctx context.Context, in *ImportPhoneByCsvFileReq, opts ...http.CallOption) (*ImportPhoneByCsvFileReply, error) {
	var out ImportPhoneByCsvFileReply
	pattern := "/yanxue/api/shadow/v1/order/importPhoneByCsvFile"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOrderImportPhoneByCsvFile))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *OrderHTTPClientImpl) MiniProgramOrderRefund(ctx context.Context, in *MiniProgramOrderRefundReq, opts ...http.CallOption) (*MiniProgramOrderRefundReply, error) {
	var out MiniProgramOrderRefundReply
	pattern := "/yanxue/api/shadow/v1/order/miniProgramOrderRefund"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOrderMiniProgramOrderRefund))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *OrderHTTPClientImpl) RefreshGoodType(ctx context.Context, in *RefreshGoodTypeReq, opts ...http.CallOption) (*RefreshGoodTypeReply, error) {
	var out RefreshGoodTypeReply
	pattern := "/yanxue/api/shadow/v1/order/refreshGoodType"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOrderRefreshGoodType))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *OrderHTTPClientImpl) RefreshServiceStatus(ctx context.Context, in *RefreshServiceStatusReq, opts ...http.CallOption) (*RefreshServiceStatusReply, error) {
	var out RefreshServiceStatusReply
	pattern := "/yanxue/api/shadow/v1/order/refreshServiceStatus"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOrderRefreshServiceStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *OrderHTTPClientImpl) SplitSubOrder(ctx context.Context, in *SplitSubOrderReq, opts ...http.CallOption) (*SplitSubOrderReply, error) {
	var out SplitSubOrderReply
	pattern := "/yanxue/api/shadow/v1/order/splitSubOrder"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOrderSplitSubOrder))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *OrderHTTPClientImpl) SyncDouYinCertificateId(ctx context.Context, in *SyncDouYinCertificateIdReq, opts ...http.CallOption) (*SyncDouYinCertificateIdReply, error) {
	var out SyncDouYinCertificateIdReply
	pattern := "/yanxue/api/shadow/v1/order/syncDouYinCertificateId"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOrderSyncDouYinCertificateId))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *OrderHTTPClientImpl) SyncDouYinSettleInfo(ctx context.Context, in *SyncDouYinSettleInfoReq, opts ...http.CallOption) (*SyncDouYinSettleInfoReply, error) {
	var out SyncDouYinSettleInfoReply
	pattern := "/yanxue/api/shadow/v1/order/syncDouYinSettleInfo"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOrderSyncDouYinSettleInfo))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *OrderHTTPClientImpl) SyncHistoryOrderFee(ctx context.Context, in *SyncHistoryOrderFeeReq, opts ...http.CallOption) (*SyncHistoryOrderFeeReply, error) {
	var out SyncHistoryOrderFeeReply
	pattern := "/yanxue/api/shadow/v1/order/syncHistoryOrderFee"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOrderSyncHistoryOrderFee))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *OrderHTTPClientImpl) SyncWeiDianOrder(ctx context.Context, in *SyncWeiDianOrderReq, opts ...http.CallOption) (*SyncWeiDianOrderReply, error) {
	var out SyncWeiDianOrderReply
	pattern := "/yanxue/api/shadow/v1/order/syncWeiDianOrder"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOrderSyncWeiDianOrder))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *OrderHTTPClientImpl) UpdateOrderDetail(ctx context.Context, in *UpdateOrderDetailReq, opts ...http.CallOption) (*UpdateOrderDetailReply, error) {
	var out UpdateOrderDetailReply
	pattern := "/yanxue/api/shadow/v1/order/updateOrderDetail"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOrderUpdateOrderDetail))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
