// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.5.3
// - protoc             v3.21.9
// source: shadow/v1/platform_good.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationPlatformGoodCreatePlatformGood = "/shadow.v1.PlatformGood/CreatePlatformGood"
const OperationPlatformGoodGetPlatformGoodList = "/shadow.v1.PlatformGood/GetPlatformGoodList"
const OperationPlatformGoodUpdatePlatformGood = "/shadow.v1.PlatformGood/UpdatePlatformGood"

type PlatformGoodHTTPServer interface {
	CreatePlatformGood(context.Context, *CreatePlatformGoodReq) (*CreatePlatformGoodReply, error)
	GetPlatformGoodList(context.Context, *GetPlatformGoodListReq) (*GetPlatformGoodListReply, error)
	UpdatePlatformGood(context.Context, *UpdatePlatformGoodReq) (*UpdatePlatformGoodReply, error)
}

func RegisterPlatformGoodHTTPServer(s *http.Server, srv PlatformGoodHTTPServer) {
	r := s.Route("/")
	r.POST("/yanxue/api/shadow/v1/platformGood/create", _PlatformGood_CreatePlatformGood0_HTTP_Handler(srv))
	r.POST("/yanxue/api/shadow/v1/platformGood/update", _PlatformGood_UpdatePlatformGood0_HTTP_Handler(srv))
	r.POST("/yanxue/api/shadow/v1/platformGood/list", _PlatformGood_GetPlatformGoodList0_HTTP_Handler(srv))
}

func _PlatformGood_CreatePlatformGood0_HTTP_Handler(srv PlatformGoodHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreatePlatformGoodReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPlatformGoodCreatePlatformGood)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreatePlatformGood(ctx, req.(*CreatePlatformGoodReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreatePlatformGoodReply)
		return ctx.Result(200, reply)
	}
}

func _PlatformGood_UpdatePlatformGood0_HTTP_Handler(srv PlatformGoodHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdatePlatformGoodReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPlatformGoodUpdatePlatformGood)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdatePlatformGood(ctx, req.(*UpdatePlatformGoodReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdatePlatformGoodReply)
		return ctx.Result(200, reply)
	}
}

func _PlatformGood_GetPlatformGoodList0_HTTP_Handler(srv PlatformGoodHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetPlatformGoodListReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPlatformGoodGetPlatformGoodList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetPlatformGoodList(ctx, req.(*GetPlatformGoodListReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetPlatformGoodListReply)
		return ctx.Result(200, reply)
	}
}

type PlatformGoodHTTPClient interface {
	CreatePlatformGood(ctx context.Context, req *CreatePlatformGoodReq, opts ...http.CallOption) (rsp *CreatePlatformGoodReply, err error)
	GetPlatformGoodList(ctx context.Context, req *GetPlatformGoodListReq, opts ...http.CallOption) (rsp *GetPlatformGoodListReply, err error)
	UpdatePlatformGood(ctx context.Context, req *UpdatePlatformGoodReq, opts ...http.CallOption) (rsp *UpdatePlatformGoodReply, err error)
}

type PlatformGoodHTTPClientImpl struct {
	cc *http.Client
}

func NewPlatformGoodHTTPClient(client *http.Client) PlatformGoodHTTPClient {
	return &PlatformGoodHTTPClientImpl{client}
}

func (c *PlatformGoodHTTPClientImpl) CreatePlatformGood(ctx context.Context, in *CreatePlatformGoodReq, opts ...http.CallOption) (*CreatePlatformGoodReply, error) {
	var out CreatePlatformGoodReply
	pattern := "/yanxue/api/shadow/v1/platformGood/create"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPlatformGoodCreatePlatformGood))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *PlatformGoodHTTPClientImpl) GetPlatformGoodList(ctx context.Context, in *GetPlatformGoodListReq, opts ...http.CallOption) (*GetPlatformGoodListReply, error) {
	var out GetPlatformGoodListReply
	pattern := "/yanxue/api/shadow/v1/platformGood/list"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPlatformGoodGetPlatformGoodList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *PlatformGoodHTTPClientImpl) UpdatePlatformGood(ctx context.Context, in *UpdatePlatformGoodReq, opts ...http.CallOption) (*UpdatePlatformGoodReply, error) {
	var out UpdatePlatformGoodReply
	pattern := "/yanxue/api/shadow/v1/platformGood/update"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPlatformGoodUpdatePlatformGood))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
