// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: shadow/v1/sys_admin.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// define the regex for a UUID once up-front
var _sys_admin_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on SysAdminRoleInfo with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *SysAdminRoleInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SysAdminRoleInfo with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SysAdminRoleInfoMultiError, or nil if none found.
func (m *SysAdminRoleInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *SysAdminRoleInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for RoleId

	// no validation rules for RoleName

	if len(errors) > 0 {
		return SysAdminRoleInfoMultiError(errors)
	}

	return nil
}

// SysAdminRoleInfoMultiError is an error wrapping multiple validation errors
// returned by SysAdminRoleInfo.ValidateAll() if the designated constraints
// aren't met.
type SysAdminRoleInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SysAdminRoleInfoMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SysAdminRoleInfoMultiError) AllErrors() []error { return m }

// SysAdminRoleInfoValidationError is the validation error returned by
// SysAdminRoleInfo.Validate if the designated constraints aren't met.
type SysAdminRoleInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SysAdminRoleInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SysAdminRoleInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SysAdminRoleInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SysAdminRoleInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SysAdminRoleInfoValidationError) ErrorName() string { return "SysAdminRoleInfoValidationError" }

// Error satisfies the builtin error interface
func (e SysAdminRoleInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSysAdminRoleInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SysAdminRoleInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SysAdminRoleInfoValidationError{}

// Validate checks the field values on SysAdminDeptInfo with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *SysAdminDeptInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SysAdminDeptInfo with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SysAdminDeptInfoMultiError, or nil if none found.
func (m *SysAdminDeptInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *SysAdminDeptInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for DeptId

	// no validation rules for DeptName

	if len(errors) > 0 {
		return SysAdminDeptInfoMultiError(errors)
	}

	return nil
}

// SysAdminDeptInfoMultiError is an error wrapping multiple validation errors
// returned by SysAdminDeptInfo.ValidateAll() if the designated constraints
// aren't met.
type SysAdminDeptInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SysAdminDeptInfoMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SysAdminDeptInfoMultiError) AllErrors() []error { return m }

// SysAdminDeptInfoValidationError is the validation error returned by
// SysAdminDeptInfo.Validate if the designated constraints aren't met.
type SysAdminDeptInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SysAdminDeptInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SysAdminDeptInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SysAdminDeptInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SysAdminDeptInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SysAdminDeptInfoValidationError) ErrorName() string { return "SysAdminDeptInfoValidationError" }

// Error satisfies the builtin error interface
func (e SysAdminDeptInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSysAdminDeptInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SysAdminDeptInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SysAdminDeptInfoValidationError{}

// Validate checks the field values on SysAdminInfo with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SysAdminInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SysAdminInfo with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SysAdminInfoMultiError, or
// nil if none found.
func (m *SysAdminInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *SysAdminInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Phone

	// no validation rules for Nickname

	// no validation rules for Avatar

	// no validation rules for Status

	// no validation rules for IsChangePwd

	// no validation rules for CreatedAt

	// no validation rules for UpdatedAt

	for idx, item := range m.GetRoleList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, SysAdminInfoValidationError{
						field:  fmt.Sprintf("RoleList[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, SysAdminInfoValidationError{
						field:  fmt.Sprintf("RoleList[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return SysAdminInfoValidationError{
					field:  fmt.Sprintf("RoleList[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	for idx, item := range m.GetDeptList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, SysAdminInfoValidationError{
						field:  fmt.Sprintf("DeptList[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, SysAdminInfoValidationError{
						field:  fmt.Sprintf("DeptList[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return SysAdminInfoValidationError{
					field:  fmt.Sprintf("DeptList[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return SysAdminInfoMultiError(errors)
	}

	return nil
}

// SysAdminInfoMultiError is an error wrapping multiple validation errors
// returned by SysAdminInfo.ValidateAll() if the designated constraints aren't met.
type SysAdminInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SysAdminInfoMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SysAdminInfoMultiError) AllErrors() []error { return m }

// SysAdminInfoValidationError is the validation error returned by
// SysAdminInfo.Validate if the designated constraints aren't met.
type SysAdminInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SysAdminInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SysAdminInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SysAdminInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SysAdminInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SysAdminInfoValidationError) ErrorName() string { return "SysAdminInfoValidationError" }

// Error satisfies the builtin error interface
func (e SysAdminInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSysAdminInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SysAdminInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SysAdminInfoValidationError{}

// Validate checks the field values on SysAdminListReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *SysAdminListReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SysAdminListReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SysAdminListReqMultiError, or nil if none found.
func (m *SysAdminListReq) ValidateAll() error {
	return m.validate(true)
}

func (m *SysAdminListReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetPage() < 1 {
		err := SysAdminListReqValidationError{
			field:  "Page",
			reason: "value must be greater than or equal to 1",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if val := m.GetPageSize(); val < 1 || val > 1000 {
		err := SysAdminListReqValidationError{
			field:  "PageSize",
			reason: "value must be inside range [1, 1000]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Phone

	// no validation rules for Nickname

	// no validation rules for Status

	if len(errors) > 0 {
		return SysAdminListReqMultiError(errors)
	}

	return nil
}

// SysAdminListReqMultiError is an error wrapping multiple validation errors
// returned by SysAdminListReq.ValidateAll() if the designated constraints
// aren't met.
type SysAdminListReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SysAdminListReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SysAdminListReqMultiError) AllErrors() []error { return m }

// SysAdminListReqValidationError is the validation error returned by
// SysAdminListReq.Validate if the designated constraints aren't met.
type SysAdminListReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SysAdminListReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SysAdminListReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SysAdminListReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SysAdminListReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SysAdminListReqValidationError) ErrorName() string { return "SysAdminListReqValidationError" }

// Error satisfies the builtin error interface
func (e SysAdminListReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSysAdminListReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SysAdminListReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SysAdminListReqValidationError{}

// Validate checks the field values on SysAdminListReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *SysAdminListReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SysAdminListReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SysAdminListReplyMultiError, or nil if none found.
func (m *SysAdminListReply) ValidateAll() error {
	return m.validate(true)
}

func (m *SysAdminListReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Total

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, SysAdminListReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, SysAdminListReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return SysAdminListReplyValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return SysAdminListReplyMultiError(errors)
	}

	return nil
}

// SysAdminListReplyMultiError is an error wrapping multiple validation errors
// returned by SysAdminListReply.ValidateAll() if the designated constraints
// aren't met.
type SysAdminListReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SysAdminListReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SysAdminListReplyMultiError) AllErrors() []error { return m }

// SysAdminListReplyValidationError is the validation error returned by
// SysAdminListReply.Validate if the designated constraints aren't met.
type SysAdminListReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SysAdminListReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SysAdminListReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SysAdminListReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SysAdminListReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SysAdminListReplyValidationError) ErrorName() string {
	return "SysAdminListReplyValidationError"
}

// Error satisfies the builtin error interface
func (e SysAdminListReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSysAdminListReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SysAdminListReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SysAdminListReplyValidationError{}

// Validate checks the field values on SysAdminStoreReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *SysAdminStoreReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SysAdminStoreReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SysAdminStoreReqMultiError, or nil if none found.
func (m *SysAdminStoreReq) ValidateAll() error {
	return m.validate(true)
}

func (m *SysAdminStoreReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetId() != "" {

		if err := m._validateUuid(m.GetId()); err != nil {
			err = SysAdminStoreReqValidationError{
				field:  "Id",
				reason: "value must be a valid UUID",
				cause:  err,
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if !_SysAdminStoreReq_Phone_Pattern.MatchString(m.GetPhone()) {
		err := SysAdminStoreReqValidationError{
			field:  "Phone",
			reason: "value does not match regex pattern \"^[a-zA-Z0-9_-]{4,16}$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetNickname()); l < 1 || l > 50 {
		err := SysAdminStoreReqValidationError{
			field:  "Nickname",
			reason: "value length must be between 1 and 50 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Avatar

	if _, ok := _SysAdminStoreReq_Status_InLookup[m.GetStatus()]; !ok {
		err := SysAdminStoreReqValidationError{
			field:  "Status",
			reason: "value must be in list [-1 1]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return SysAdminStoreReqMultiError(errors)
	}

	return nil
}

func (m *SysAdminStoreReq) _validateUuid(uuid string) error {
	if matched := _sys_admin_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// SysAdminStoreReqMultiError is an error wrapping multiple validation errors
// returned by SysAdminStoreReq.ValidateAll() if the designated constraints
// aren't met.
type SysAdminStoreReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SysAdminStoreReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SysAdminStoreReqMultiError) AllErrors() []error { return m }

// SysAdminStoreReqValidationError is the validation error returned by
// SysAdminStoreReq.Validate if the designated constraints aren't met.
type SysAdminStoreReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SysAdminStoreReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SysAdminStoreReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SysAdminStoreReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SysAdminStoreReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SysAdminStoreReqValidationError) ErrorName() string { return "SysAdminStoreReqValidationError" }

// Error satisfies the builtin error interface
func (e SysAdminStoreReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSysAdminStoreReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SysAdminStoreReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SysAdminStoreReqValidationError{}

var _SysAdminStoreReq_Phone_Pattern = regexp.MustCompile("^[a-zA-Z0-9_-]{4,16}$")

var _SysAdminStoreReq_Status_InLookup = map[int32]struct{}{
	-1: {},
	1:  {},
}

// Validate checks the field values on SysAdminStoreReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SysAdminStoreReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SysAdminStoreReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SysAdminStoreReplyMultiError, or nil if none found.
func (m *SysAdminStoreReply) ValidateAll() error {
	return m.validate(true)
}

func (m *SysAdminStoreReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return SysAdminStoreReplyMultiError(errors)
	}

	return nil
}

// SysAdminStoreReplyMultiError is an error wrapping multiple validation errors
// returned by SysAdminStoreReply.ValidateAll() if the designated constraints
// aren't met.
type SysAdminStoreReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SysAdminStoreReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SysAdminStoreReplyMultiError) AllErrors() []error { return m }

// SysAdminStoreReplyValidationError is the validation error returned by
// SysAdminStoreReply.Validate if the designated constraints aren't met.
type SysAdminStoreReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SysAdminStoreReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SysAdminStoreReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SysAdminStoreReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SysAdminStoreReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SysAdminStoreReplyValidationError) ErrorName() string {
	return "SysAdminStoreReplyValidationError"
}

// Error satisfies the builtin error interface
func (e SysAdminStoreReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSysAdminStoreReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SysAdminStoreReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SysAdminStoreReplyValidationError{}

// Validate checks the field values on SysAdminStatusReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *SysAdminStatusReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SysAdminStatusReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SysAdminStatusReqMultiError, or nil if none found.
func (m *SysAdminStatusReq) ValidateAll() error {
	return m.validate(true)
}

func (m *SysAdminStatusReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetId()); err != nil {
		err = SysAdminStatusReqValidationError{
			field:  "Id",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := _SysAdminStatusReq_Status_InLookup[m.GetStatus()]; !ok {
		err := SysAdminStatusReqValidationError{
			field:  "Status",
			reason: "value must be in list [-1 1]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return SysAdminStatusReqMultiError(errors)
	}

	return nil
}

func (m *SysAdminStatusReq) _validateUuid(uuid string) error {
	if matched := _sys_admin_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// SysAdminStatusReqMultiError is an error wrapping multiple validation errors
// returned by SysAdminStatusReq.ValidateAll() if the designated constraints
// aren't met.
type SysAdminStatusReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SysAdminStatusReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SysAdminStatusReqMultiError) AllErrors() []error { return m }

// SysAdminStatusReqValidationError is the validation error returned by
// SysAdminStatusReq.Validate if the designated constraints aren't met.
type SysAdminStatusReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SysAdminStatusReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SysAdminStatusReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SysAdminStatusReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SysAdminStatusReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SysAdminStatusReqValidationError) ErrorName() string {
	return "SysAdminStatusReqValidationError"
}

// Error satisfies the builtin error interface
func (e SysAdminStatusReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSysAdminStatusReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SysAdminStatusReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SysAdminStatusReqValidationError{}

var _SysAdminStatusReq_Status_InLookup = map[int32]struct{}{
	-1: {},
	1:  {},
}

// Validate checks the field values on SysAdminStatusReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SysAdminStatusReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SysAdminStatusReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SysAdminStatusReplyMultiError, or nil if none found.
func (m *SysAdminStatusReply) ValidateAll() error {
	return m.validate(true)
}

func (m *SysAdminStatusReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return SysAdminStatusReplyMultiError(errors)
	}

	return nil
}

// SysAdminStatusReplyMultiError is an error wrapping multiple validation
// errors returned by SysAdminStatusReply.ValidateAll() if the designated
// constraints aren't met.
type SysAdminStatusReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SysAdminStatusReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SysAdminStatusReplyMultiError) AllErrors() []error { return m }

// SysAdminStatusReplyValidationError is the validation error returned by
// SysAdminStatusReply.Validate if the designated constraints aren't met.
type SysAdminStatusReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SysAdminStatusReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SysAdminStatusReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SysAdminStatusReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SysAdminStatusReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SysAdminStatusReplyValidationError) ErrorName() string {
	return "SysAdminStatusReplyValidationError"
}

// Error satisfies the builtin error interface
func (e SysAdminStatusReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSysAdminStatusReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SysAdminStatusReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SysAdminStatusReplyValidationError{}

// Validate checks the field values on SysAdminChangePwdReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SysAdminChangePwdReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SysAdminChangePwdReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SysAdminChangePwdReqMultiError, or nil if none found.
func (m *SysAdminChangePwdReq) ValidateAll() error {
	return m.validate(true)
}

func (m *SysAdminChangePwdReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetOldPassword()) < 6 {
		err := SysAdminChangePwdReqValidationError{
			field:  "OldPassword",
			reason: "value length must be at least 6 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetPassword()) < 6 {
		err := SysAdminChangePwdReqValidationError{
			field:  "Password",
			reason: "value length must be at least 6 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return SysAdminChangePwdReqMultiError(errors)
	}

	return nil
}

// SysAdminChangePwdReqMultiError is an error wrapping multiple validation
// errors returned by SysAdminChangePwdReq.ValidateAll() if the designated
// constraints aren't met.
type SysAdminChangePwdReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SysAdminChangePwdReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SysAdminChangePwdReqMultiError) AllErrors() []error { return m }

// SysAdminChangePwdReqValidationError is the validation error returned by
// SysAdminChangePwdReq.Validate if the designated constraints aren't met.
type SysAdminChangePwdReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SysAdminChangePwdReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SysAdminChangePwdReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SysAdminChangePwdReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SysAdminChangePwdReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SysAdminChangePwdReqValidationError) ErrorName() string {
	return "SysAdminChangePwdReqValidationError"
}

// Error satisfies the builtin error interface
func (e SysAdminChangePwdReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSysAdminChangePwdReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SysAdminChangePwdReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SysAdminChangePwdReqValidationError{}

// Validate checks the field values on SysAdminChangePwdReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SysAdminChangePwdReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SysAdminChangePwdReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SysAdminChangePwdReplyMultiError, or nil if none found.
func (m *SysAdminChangePwdReply) ValidateAll() error {
	return m.validate(true)
}

func (m *SysAdminChangePwdReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return SysAdminChangePwdReplyMultiError(errors)
	}

	return nil
}

// SysAdminChangePwdReplyMultiError is an error wrapping multiple validation
// errors returned by SysAdminChangePwdReply.ValidateAll() if the designated
// constraints aren't met.
type SysAdminChangePwdReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SysAdminChangePwdReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SysAdminChangePwdReplyMultiError) AllErrors() []error { return m }

// SysAdminChangePwdReplyValidationError is the validation error returned by
// SysAdminChangePwdReply.Validate if the designated constraints aren't met.
type SysAdminChangePwdReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SysAdminChangePwdReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SysAdminChangePwdReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SysAdminChangePwdReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SysAdminChangePwdReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SysAdminChangePwdReplyValidationError) ErrorName() string {
	return "SysAdminChangePwdReplyValidationError"
}

// Error satisfies the builtin error interface
func (e SysAdminChangePwdReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSysAdminChangePwdReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SysAdminChangePwdReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SysAdminChangePwdReplyValidationError{}

// Validate checks the field values on SysAdminResetPwdReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SysAdminResetPwdReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SysAdminResetPwdReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SysAdminResetPwdReqMultiError, or nil if none found.
func (m *SysAdminResetPwdReq) ValidateAll() error {
	return m.validate(true)
}

func (m *SysAdminResetPwdReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetId()); err != nil {
		err = SysAdminResetPwdReqValidationError{
			field:  "Id",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return SysAdminResetPwdReqMultiError(errors)
	}

	return nil
}

func (m *SysAdminResetPwdReq) _validateUuid(uuid string) error {
	if matched := _sys_admin_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// SysAdminResetPwdReqMultiError is an error wrapping multiple validation
// errors returned by SysAdminResetPwdReq.ValidateAll() if the designated
// constraints aren't met.
type SysAdminResetPwdReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SysAdminResetPwdReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SysAdminResetPwdReqMultiError) AllErrors() []error { return m }

// SysAdminResetPwdReqValidationError is the validation error returned by
// SysAdminResetPwdReq.Validate if the designated constraints aren't met.
type SysAdminResetPwdReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SysAdminResetPwdReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SysAdminResetPwdReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SysAdminResetPwdReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SysAdminResetPwdReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SysAdminResetPwdReqValidationError) ErrorName() string {
	return "SysAdminResetPwdReqValidationError"
}

// Error satisfies the builtin error interface
func (e SysAdminResetPwdReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSysAdminResetPwdReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SysAdminResetPwdReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SysAdminResetPwdReqValidationError{}

// Validate checks the field values on SysAdminResetPwdReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SysAdminResetPwdReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SysAdminResetPwdReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SysAdminResetPwdReplyMultiError, or nil if none found.
func (m *SysAdminResetPwdReply) ValidateAll() error {
	return m.validate(true)
}

func (m *SysAdminResetPwdReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return SysAdminResetPwdReplyMultiError(errors)
	}

	return nil
}

// SysAdminResetPwdReplyMultiError is an error wrapping multiple validation
// errors returned by SysAdminResetPwdReply.ValidateAll() if the designated
// constraints aren't met.
type SysAdminResetPwdReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SysAdminResetPwdReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SysAdminResetPwdReplyMultiError) AllErrors() []error { return m }

// SysAdminResetPwdReplyValidationError is the validation error returned by
// SysAdminResetPwdReply.Validate if the designated constraints aren't met.
type SysAdminResetPwdReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SysAdminResetPwdReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SysAdminResetPwdReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SysAdminResetPwdReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SysAdminResetPwdReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SysAdminResetPwdReplyValidationError) ErrorName() string {
	return "SysAdminResetPwdReplyValidationError"
}

// Error satisfies the builtin error interface
func (e SysAdminResetPwdReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSysAdminResetPwdReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SysAdminResetPwdReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SysAdminResetPwdReplyValidationError{}

// Validate checks the field values on SysAdminDelReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SysAdminDelReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SysAdminDelReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SysAdminDelReqMultiError,
// or nil if none found.
func (m *SysAdminDelReq) ValidateAll() error {
	return m.validate(true)
}

func (m *SysAdminDelReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetId()); err != nil {
		err = SysAdminDelReqValidationError{
			field:  "Id",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return SysAdminDelReqMultiError(errors)
	}

	return nil
}

func (m *SysAdminDelReq) _validateUuid(uuid string) error {
	if matched := _sys_admin_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// SysAdminDelReqMultiError is an error wrapping multiple validation errors
// returned by SysAdminDelReq.ValidateAll() if the designated constraints
// aren't met.
type SysAdminDelReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SysAdminDelReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SysAdminDelReqMultiError) AllErrors() []error { return m }

// SysAdminDelReqValidationError is the validation error returned by
// SysAdminDelReq.Validate if the designated constraints aren't met.
type SysAdminDelReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SysAdminDelReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SysAdminDelReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SysAdminDelReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SysAdminDelReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SysAdminDelReqValidationError) ErrorName() string { return "SysAdminDelReqValidationError" }

// Error satisfies the builtin error interface
func (e SysAdminDelReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSysAdminDelReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SysAdminDelReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SysAdminDelReqValidationError{}

// Validate checks the field values on SysAdminDelReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *SysAdminDelReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SysAdminDelReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SysAdminDelReplyMultiError, or nil if none found.
func (m *SysAdminDelReply) ValidateAll() error {
	return m.validate(true)
}

func (m *SysAdminDelReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return SysAdminDelReplyMultiError(errors)
	}

	return nil
}

// SysAdminDelReplyMultiError is an error wrapping multiple validation errors
// returned by SysAdminDelReply.ValidateAll() if the designated constraints
// aren't met.
type SysAdminDelReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SysAdminDelReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SysAdminDelReplyMultiError) AllErrors() []error { return m }

// SysAdminDelReplyValidationError is the validation error returned by
// SysAdminDelReply.Validate if the designated constraints aren't met.
type SysAdminDelReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SysAdminDelReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SysAdminDelReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SysAdminDelReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SysAdminDelReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SysAdminDelReplyValidationError) ErrorName() string { return "SysAdminDelReplyValidationError" }

// Error satisfies the builtin error interface
func (e SysAdminDelReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSysAdminDelReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SysAdminDelReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SysAdminDelReplyValidationError{}

// Validate checks the field values on SysAdminInfoReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *SysAdminInfoReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SysAdminInfoReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SysAdminInfoReqMultiError, or nil if none found.
func (m *SysAdminInfoReq) ValidateAll() error {
	return m.validate(true)
}

func (m *SysAdminInfoReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return SysAdminInfoReqMultiError(errors)
	}

	return nil
}

// SysAdminInfoReqMultiError is an error wrapping multiple validation errors
// returned by SysAdminInfoReq.ValidateAll() if the designated constraints
// aren't met.
type SysAdminInfoReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SysAdminInfoReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SysAdminInfoReqMultiError) AllErrors() []error { return m }

// SysAdminInfoReqValidationError is the validation error returned by
// SysAdminInfoReq.Validate if the designated constraints aren't met.
type SysAdminInfoReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SysAdminInfoReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SysAdminInfoReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SysAdminInfoReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SysAdminInfoReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SysAdminInfoReqValidationError) ErrorName() string { return "SysAdminInfoReqValidationError" }

// Error satisfies the builtin error interface
func (e SysAdminInfoReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSysAdminInfoReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SysAdminInfoReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SysAdminInfoReqValidationError{}

// Validate checks the field values on SysAdminInfoReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *SysAdminInfoReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SysAdminInfoReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SysAdminInfoReplyMultiError, or nil if none found.
func (m *SysAdminInfoReply) ValidateAll() error {
	return m.validate(true)
}

func (m *SysAdminInfoReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetInfo()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SysAdminInfoReplyValidationError{
					field:  "Info",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SysAdminInfoReplyValidationError{
					field:  "Info",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetInfo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SysAdminInfoReplyValidationError{
				field:  "Info",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return SysAdminInfoReplyMultiError(errors)
	}

	return nil
}

// SysAdminInfoReplyMultiError is an error wrapping multiple validation errors
// returned by SysAdminInfoReply.ValidateAll() if the designated constraints
// aren't met.
type SysAdminInfoReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SysAdminInfoReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SysAdminInfoReplyMultiError) AllErrors() []error { return m }

// SysAdminInfoReplyValidationError is the validation error returned by
// SysAdminInfoReply.Validate if the designated constraints aren't met.
type SysAdminInfoReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SysAdminInfoReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SysAdminInfoReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SysAdminInfoReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SysAdminInfoReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SysAdminInfoReplyValidationError) ErrorName() string {
	return "SysAdminInfoReplyValidationError"
}

// Error satisfies the builtin error interface
func (e SysAdminInfoReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSysAdminInfoReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SysAdminInfoReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SysAdminInfoReplyValidationError{}

// Validate checks the field values on SysAdminPermissionReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SysAdminPermissionReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SysAdminPermissionReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SysAdminPermissionReqMultiError, or nil if none found.
func (m *SysAdminPermissionReq) ValidateAll() error {
	return m.validate(true)
}

func (m *SysAdminPermissionReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return SysAdminPermissionReqMultiError(errors)
	}

	return nil
}

// SysAdminPermissionReqMultiError is an error wrapping multiple validation
// errors returned by SysAdminPermissionReq.ValidateAll() if the designated
// constraints aren't met.
type SysAdminPermissionReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SysAdminPermissionReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SysAdminPermissionReqMultiError) AllErrors() []error { return m }

// SysAdminPermissionReqValidationError is the validation error returned by
// SysAdminPermissionReq.Validate if the designated constraints aren't met.
type SysAdminPermissionReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SysAdminPermissionReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SysAdminPermissionReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SysAdminPermissionReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SysAdminPermissionReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SysAdminPermissionReqValidationError) ErrorName() string {
	return "SysAdminPermissionReqValidationError"
}

// Error satisfies the builtin error interface
func (e SysAdminPermissionReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSysAdminPermissionReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SysAdminPermissionReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SysAdminPermissionReqValidationError{}

// Validate checks the field values on SysAdminPermissionReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SysAdminPermissionReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SysAdminPermissionReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SysAdminPermissionReplyMultiError, or nil if none found.
func (m *SysAdminPermissionReply) ValidateAll() error {
	return m.validate(true)
}

func (m *SysAdminPermissionReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, SysAdminPermissionReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, SysAdminPermissionReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return SysAdminPermissionReplyValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return SysAdminPermissionReplyMultiError(errors)
	}

	return nil
}

// SysAdminPermissionReplyMultiError is an error wrapping multiple validation
// errors returned by SysAdminPermissionReply.ValidateAll() if the designated
// constraints aren't met.
type SysAdminPermissionReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SysAdminPermissionReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SysAdminPermissionReplyMultiError) AllErrors() []error { return m }

// SysAdminPermissionReplyValidationError is the validation error returned by
// SysAdminPermissionReply.Validate if the designated constraints aren't met.
type SysAdminPermissionReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SysAdminPermissionReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SysAdminPermissionReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SysAdminPermissionReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SysAdminPermissionReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SysAdminPermissionReplyValidationError) ErrorName() string {
	return "SysAdminPermissionReplyValidationError"
}

// Error satisfies the builtin error interface
func (e SysAdminPermissionReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSysAdminPermissionReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SysAdminPermissionReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SysAdminPermissionReplyValidationError{}

// Validate checks the field values on SysAdminDeptListReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SysAdminDeptListReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SysAdminDeptListReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SysAdminDeptListReqMultiError, or nil if none found.
func (m *SysAdminDeptListReq) ValidateAll() error {
	return m.validate(true)
}

func (m *SysAdminDeptListReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return SysAdminDeptListReqMultiError(errors)
	}

	return nil
}

// SysAdminDeptListReqMultiError is an error wrapping multiple validation
// errors returned by SysAdminDeptListReq.ValidateAll() if the designated
// constraints aren't met.
type SysAdminDeptListReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SysAdminDeptListReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SysAdminDeptListReqMultiError) AllErrors() []error { return m }

// SysAdminDeptListReqValidationError is the validation error returned by
// SysAdminDeptListReq.Validate if the designated constraints aren't met.
type SysAdminDeptListReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SysAdminDeptListReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SysAdminDeptListReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SysAdminDeptListReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SysAdminDeptListReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SysAdminDeptListReqValidationError) ErrorName() string {
	return "SysAdminDeptListReqValidationError"
}

// Error satisfies the builtin error interface
func (e SysAdminDeptListReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSysAdminDeptListReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SysAdminDeptListReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SysAdminDeptListReqValidationError{}

// Validate checks the field values on SysAdminDeptListReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SysAdminDeptListReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SysAdminDeptListReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SysAdminDeptListReplyMultiError, or nil if none found.
func (m *SysAdminDeptListReply) ValidateAll() error {
	return m.validate(true)
}

func (m *SysAdminDeptListReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, SysAdminDeptListReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, SysAdminDeptListReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return SysAdminDeptListReplyValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return SysAdminDeptListReplyMultiError(errors)
	}

	return nil
}

// SysAdminDeptListReplyMultiError is an error wrapping multiple validation
// errors returned by SysAdminDeptListReply.ValidateAll() if the designated
// constraints aren't met.
type SysAdminDeptListReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SysAdminDeptListReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SysAdminDeptListReplyMultiError) AllErrors() []error { return m }

// SysAdminDeptListReplyValidationError is the validation error returned by
// SysAdminDeptListReply.Validate if the designated constraints aren't met.
type SysAdminDeptListReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SysAdminDeptListReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SysAdminDeptListReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SysAdminDeptListReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SysAdminDeptListReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SysAdminDeptListReplyValidationError) ErrorName() string {
	return "SysAdminDeptListReplyValidationError"
}

// Error satisfies the builtin error interface
func (e SysAdminDeptListReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSysAdminDeptListReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SysAdminDeptListReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SysAdminDeptListReplyValidationError{}
