syntax = "proto3";

package shadow.v1;

import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";
import "validate/validate.proto";

option go_package = "gitlab.yc345.tv/backend/yanxue/api/shadow/v1;v1";

// 变量的命名一律使用小驼峰命名法，例如：firstName、lastName等。
// 后缀定义:请求req,响应reply

// 角色模块
service SysRole {
  //角色-列表
  rpc SysRoleList(SysRoleListReq) returns (SysRoleListResp) {
    option (google.api.http) = {get: "/yanxue/shadow/v1/sysRole/list"};
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      parameters: {
        headers: {
          name: "Authorization"
          description: "TOKEN"
          type: STRING
          required: true
        }
      }
    };
  }
  //角色-保存角色
  rpc SysRoleStore(SysRoleStoreReq) returns (SysRoleStoreResp) {
    option (google.api.http) = {
      post: "/yanxue/shadow/v1/sysRole/store"
      body: "*"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      parameters: {
        headers: {
          name: "Authorization"
          description: "TOKEN"
          type: STRING
          required: true
        }
      }
    };
  }
  //角色-删除角色
  rpc SysRoleDel(SysRoleDelReq) returns (SysRoleDelResp) {
    option (google.api.http) = {
      post: "/yanxue/shadow/v1/sysRole/del"
      body: "*"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      parameters: {
        headers: {
          name: "Authorization"
          description: "TOKEN"
          type: STRING
          required: true
        }
      }
    };
  }
  //角色-修改状态
  rpc SysRoleStatus(SysRoleStatusReq) returns (SysRoleStatusResp) {
    option (google.api.http) = {
      post: "/yanxue/shadow/v1/sysRole/status"
      body: "*"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      parameters: {
        headers: {
          name: "Authorization"
          description: "TOKEN"
          type: STRING
          required: true
        }
      }
    };
  }
  //角色-下拉选择列表
  rpc SysRoleSelect(SysRoleSelectReq) returns (SysRoleSelectResp) {
    option (google.api.http) = {get: "/yanxue/shadow/v1/sysRole/select"};
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      parameters: {
        headers: {
          name: "Authorization"
          description: "TOKEN"
          type: STRING
          required: true
        }
      }
    };
  }
}

//角色-信息
message SysRoleInfo {
  string id = 1; //角色Id
  string name = 2; //角色名称
  string remark = 3; //备注
  string dataPermission = 4; //数据权限  全部数据:all  本部门数据:dept  本部门及以下数据:deptAndBelow  仅本人数据:self
  int32 status = 5; // 状态:-1=禁用,1=启用
  string createdAt = 6; //创建时间
  string updatedAt = 7; //更新时间
  repeated string permissionIds = 8; //菜单角色集合
}

//角色-列表-请求
message SysRoleListReq {
  int32 page = 1 [(validate.rules).int32 = {gt: 0}]; //页码
  int32 pageSize = 2 [(validate.rules).int32 = {
    gt: 0
    lt: 1000
  }]; //每页数量
  string name = 3 [(validate.rules).string = {
    ignore_empty: true
    min_len: 1
    max_len: 50
  }]; //角色名称
  string dataPermission = 4 [(validate.rules).string = {
    ignore_empty: true
    in: [
      "all",
      "dept",
      "deptAndBelow",
      "self"
    ]
  }]; //数据权限  全部数据:all  本部门数据:dept  本部门及以下数据:deptAndBelow  仅本人数据:self
  int32 status = 5 [(validate.rules).int32 = {
    ignore_empty: true
    in: [
      -1,
      1
    ]
  }]; //状态:-1=禁用,1=启用
}

//角色-列表-响应
message SysRoleListResp {
  int32 total = 1; //总数
  repeated SysRoleInfo list = 2; //列表
}

//角色-保存角色-请求
message SysRoleStoreReq {
  option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_schema) = {
    json_schema: {
      required: [
        "name",
        "remark",
        "dataPermission",
        "status",
        "permissionIds"
      ]
    }
  };
  string id = 1 [(validate.rules).string = {
    uuid: true
    ignore_empty: true
  }]; //角色Id
  string name = 2 [(validate.rules).string = {
    min_len: 1
    max_len: 50
  }]; //角色名称
  string remark = 3 [(validate.rules).string = {
    ignore_empty: true
    min_len: 1
    max_len: 200
  }]; //备注
  string dataPermission = 4 [(validate.rules).string = {
    ignore_empty: true
    in: [
      "all",
      "dept",
      "deptAndBelow",
      "self"
    ]
  }]; //数据权限  全部数据:all  本部门数据:dept  本部门及以下数据:deptAndBelow  仅本人数据:self
  int32 status = 5 [(validate.rules).int32 = {
    in: [
      -1,
      1
    ]
  }]; // 状态:-1=禁用,1=启用
  repeated string permissionIds = 7; //菜单角色集合
}

//角色-保存角色-响应
message SysRoleStoreResp {
  string id = 1; // Id
}

//角色-删除角色-请求
message SysRoleDelReq {
  option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_schema) = {
    json_schema: {
      required: ["id"]
    }
  };
  string id = 1 [(validate.rules).string = {uuid: true}]; //Id
}

//角色-删除角色-响应
message SysRoleDelResp {}

//角色-修改状态-请求
message SysRoleStatusReq {
  option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_schema) = {
    json_schema: {
      required: [
        "id",
        "status"
      ]
    }
  };
  string id = 1 [(validate.rules).string = {uuid: true}]; //角色Id
  int32 status = 2 [(validate.rules).int32 = {
    in: [
      -1,
      1
    ]
  }]; // 状态:-1=禁用,1=启用
}

//角色-修改状态-响应
message SysRoleStatusResp {}

//角色-下拉选择列表-请求
message SysRoleSelectReq {
  string dataPermission = 1 [(validate.rules).string = {
    ignore_empty: true
    in: [
      "all",
      "dept",
      "deptAndBelow",
      "self"
    ]
  }]; //数据权限  全部数据:all  本部门数据:dept  本部门及以下数据:deptAndBelow  仅本人数据:self
  int32 status = 2 [(validate.rules).int32 = {
    ignore_empty: true
    in: [
      -1,
      1
    ]
  }]; // 状态:-1=禁用,1=启用
}

//角色-下拉选择列表-响应
message SysRoleSelectResp {
  repeated SysRoleInfo list = 1; //列表
}
