# 配置文档
# https://guanghe.feishu.cn/docs/doccn7x1etOkjKfKZL9mwQjtpzf#

# Harbor
# https://docker.yc345.tv/harbor/projects/5/repositories

# k8s 管理UI
# https://rancher.yc345.tv/

# 定义项目构建或部署过程中使用的环境变量
variables:
  DOCKER_REGISTRY: docker.yc345.tv
  K8S_DEPLOYMENT: yanxue
  NAMESPACE: 7to12
  HOME: /builds

stages:
  - build_test
  - deploy_test
  - deploy_test_rollback
  - build_stage
  - deploy_stage
  - deploy_stage_rollback
  - build_pro

.tag_testenv_k8s: &testenv_k8s_tag
  tags:
    - testenv
    - kubernetes

.before_script: &before_script
  before_script:
    - export GO111MODULE=on
    - export GOPROXY=https://goproxy.cn,direct
    - export GOPRIVATE=gitlab.yc345.tv
    - |
      cat <<-EOF >> ~/.gitconfig
      [url "git@github.com:"]
          insteadOf = https://github.com/
      [url "git@gitlab.yc345.tv:"]
          insteadOf = https://gitlab.yc345.tv/
      EOF
    - mkdir ~/.ssh && chmod 700 ~/.ssh && cat $PRIVATE_KEY > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
    - |
      cat <<-EOF >> ~/.ssh/config
      Host *
      StrictHostKeyChecking no
      UserKnownHostsFile=/dev/null
      EOF
    - chmod 600 ~/.ssh/config

#golangci-lint:
#  stage: golangci_lint
#  image: golangci/golangci-lint:v1.55.0
#  timeout: 30m
#  cache:
#    key: golangci-lint-cache
#    paths:
#      - ~/.cache/golangci-lint
#  script:
#    - go env -w GO111MODULE=on
#    - go env -w GOOS=linux
#    - go env -w GOARCH=amd64
#    - go env -w GOPROXY=https://goproxy.cn,direct
#    - go env -w GOPRIVATE=gitlab.yc345.tv
#    - git config --global url."https://gitlab-ci-token:hhSC6Ndj8Jxo4EyHxMyA@gitlab.yc345.tv".insteadof "https://gitlab.yc345.tv"
#    - go env
#    - go mod tidy
#    - make lint

【测试环境】镜像构建:
  stage: build_test
  image: docker.yc345.tv/7to12/docker:19.03.13
  only:
    - test
  before_script:
    - mkdir .ssh && chmod 700 .ssh && cat $Private_REPO_SSHKey > .ssh/id_rsa && chmod 600 .ssh/id_rsa
  script:
    - echo $CI_PROJECT_DIR
    - docker login --username=$DOCKER_USERNAME $DOCKER_REGISTRY -p $DOCKER_PASSWORD
    - docker build -t $DOCKER_REGISTRY/$NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA .
    - docker push $DOCKER_REGISTRY/$NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA
  tags:
    - cluster
    - kubernetes

【测试环境】容器发布:
  stage: deploy_test
  image: docker.yc345.tv/7to12/kubectl:1.20.1-bitnami
  only:
    - test
  script:
    - kubectl config set-cluster test-cluster --server=$KUBE_HOST_TEST --insecure-skip-tls-verify=true
    - kubectl config set-credentials gitlab-ci --token=$KUBE_TOKEN_TEST
    - kubectl config set-context testenv --cluster=test-cluster --user=gitlab-ci && kubectl config use-context testenv
    - kubectl -n $NAMESPACE set image deployment $CI_PROJECT_NAME $CI_PROJECT_NAME=$DOCKER_REGISTRY/$NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA
    - kubectl -n $NAMESPACE rollout status deployment $CI_PROJECT_NAME

【测试环境】容器回滚:
  stage: deploy_test_rollback
  image: bitnami/kubectl:1.20.1
  only:
    - test
  when: manual
  script:
    - kubectl config set-cluster test-cluster --server=$KUBE_HOST_TEST --insecure-skip-tls-verify=true
    - kubectl config set-credentials gitlab-ci --token=$KUBE_TOKEN_TEST
    - kubectl config set-context testenv --cluster=test-cluster --user=gitlab-ci && kubectl config use-context testen
    - kubectl -n $NAMESPACE rollout undo deployment $CI_PROJECT_NAME

【预发布】镜像构建:
  stage: build_stage
  image: docker.yc345.tv/7to12/docker:19.03.13
  only:
    - stage
  before_script:
    - mkdir .ssh && chmod 700 .ssh && cat $Private_REPO_SSHKey > .ssh/id_rsa && chmod 600 .ssh/id_rsa
  script:
    - docker login --username=$DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REGISTRY
    - docker build -t $DOCKER_REGISTRY/$NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA .
    - docker push $DOCKER_REGISTRY/$NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA
  tags:
    - cluster
    - kubernetes

【预发布】容器发布:
  stage: deploy_stage
  image: docker.yc345.tv/7to12/kubectl:1.20.1-bitnami
  only:
    - stage
  script:
    - kubectl config set-cluster stage-cluster --server=$KUBE_HOST_STAGE_VOLCENGINE --insecure-skip-tls-verify=true
    - kubectl config set-credentials gitlab-ci --token=$KUBE_TOKEN_STAGE_VOLCENGINE
    - kubectl config set-context stagenv --cluster=stage-cluster --user=gitlab-ci && kubectl config use-context stagenv
    - kubectl -n $NAMESPACE set image deployment $CI_PROJECT_NAME $CI_PROJECT_NAME=$DOCKER_REGISTRY/$NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA --record
    - kubectl -n $NAMESPACE rollout status deployment $CI_PROJECT_NAME
  tags:
    - kubernetes
    - cluster

【预发布】容器回滚:
  stage: deploy_stage_rollback
  image: bitnami/kubectl:1.20.1
  only:
    - stage
  when: manual
  script:
    - kubectl config set-cluster stage-cluster --server=$KUBE_HOST_STAGE_VOLCENGINE --insecure-skip-tls-verify=true
    - kubectl config set-credentials gitlab-ci --token=$KUBE_TOKEN_STAGE_VOLCENGINE
    - kubectl config set-context stagenv --cluster=stage-cluster --user=gitlab-ci && kubectl config use-context stagenv
    - kubectl -n $NAMESPACE rollout undo deployment $CI_PROJECT_NAME
  tags:
    - kubernetes
    - cluster

【正式环境】镜像构建:
  stage: build_pro
  image: docker.yc345.tv/7to12/docker:19.03.13
  only:
    - /^[v]?\d+\.\d+\.\d+$/
  before_script:
    - mkdir .ssh && chmod 700 .ssh && cat $Private_REPO_SSHKey > .ssh/id_rsa && chmod 600 .ssh/id_rsa
  script:
    - docker login --username=$DOCKER_USERNAME $DOCKER_REGISTRY -p $DOCKER_PASSWORD
    - docker build -t $DOCKER_REGISTRY/$NAMESPACE/$K8S_DEPLOYMENT:${CI_COMMIT_REF_NAME} --build-arg buildENV=production .
    - docker push $DOCKER_REGISTRY/$NAMESPACE/$K8S_DEPLOYMENT:${CI_COMMIT_REF_NAME}
  tags:
    - cluster
    - kubernetes