sonar.projectKey= TODO:
sonar.sources=.
sonar.host.url=https://sonarqube.yc345.tv
sonar.login= TODO:
sonar.go.coverage.reportPaths =./test-coverage.txt
sonar.test.inclusions=**/*_test.go,**/wire.go,**/*.gen.go
