// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package devices_learn_model

import (
	"time"

	"gorm.io/datatypes"
)

const TableNameUserLearnTarget = "user_learn_target"

// UserLearnTarget mapped from table <user_learn_target>
type UserLearnTarget struct {
	ID                 string         `gorm:"column:id;type:uuid;primaryKey;default:uuid_generate_v4();comment:记录ID" json:"id"`         // 记录ID
	UserID             string         `gorm:"column:userId;type:character varying(64);not null;comment:用户ID" json:"userId"`             // 用户ID
	SchoolID           string         `gorm:"column:schoolId;type:character varying(64);not null;comment:学校配置ID" json:"schoolId"`       // 学校配置ID
	SchoolName         string         `gorm:"column:schoolName;type:character varying(125);not null;comment:学校名称" json:"schoolName"`    // 学校名称
	SchoolSystem       int64          `gorm:"column:schoolSystem;type:bigint;comment:学制年限" json:"schoolSystem"`                         // 学制年限
	ScoresTotal        int64          `gorm:"column:scoresTotal;type:bigint;comment:最近一年中考总分" json:"scoresTotal"`                       // 最近一年中考总分
	ScoresAdmission    int64          `gorm:"column:scoresAdmission;type:bigint;comment:最近一年录取分数线" json:"scoresAdmission"`              // 最近一年录取分数线
	ScoresTarget       int64          `gorm:"column:scoresTarget;type:bigint;comment:用户目标分数线" json:"scoresTarget"`                      // 用户目标分数线
	ScoresTotalSubject datatypes.JSON `gorm:"column:scoresTotalSubject;type:jsonb;comment:各科满分分数" json:"scoresTotalSubject"`            // 各科满分分数
	Status             int64          `gorm:"column:status;type:bigint;comment:状态 -1:删除 0:无效 1:有效" json:"status"`                       // 状态 -1:删除 0:无效 1:有效
	CreatedAt          time.Time      `gorm:"column:createdAt;type:timestamp(6) with time zone;not null;comment:创建时间" json:"createdAt"` // 创建时间
	UpdatedAt          time.Time      `gorm:"column:updatedAt;type:timestamp(6) with time zone;not null;comment:更新时间" json:"updatedAt"` // 更新时间
}

// TableName UserLearnTarget's table name
func (*UserLearnTarget) TableName() string {
	return TableNameUserLearnTarget
}
