package service

import (
	"github.com/google/wire"
)

// ProviderSet is service providers.
var ProviderSet = wire.NewSet(
	NewShadowV1ChannelService,
	NewShadowV1ContractService,
	NewShadowV1CouponService,
	NewShadowV1CourseAppointmentService,
	NewShadowV1CourseService,
	NewShadowV1CourseStockService,
	NewShadowV1DynamicFieldMappingService,
	NewShadowV1EvaluationService,
	NewShadowV1EvaluationTemplateService,
	NewShadowV1GoodRecommendationCategoryService,
	NewShadowV1GoodService,
	NewShadowV1GrabTicketSiteConfigService,
	NewShadowV1GrabTicketTaskConfigService,
	NewShadowV1OrderService,
	NewShadowV1PlatformGoodService,
	NewShadowV1SubOrderService,
	NewShadowV1SysAdminService,
	NewShadowV1SysAuthService,
	NewShadowV1SysDataLogService,
	NewShadowV1SysDeptService,
	NewShadowV1SysOperationLogService,
	NewShadowV1SysPermissionService,
	NewShadowV1SysRoleService,
	NewShadowV1UserBindStudentService,
	NewShadowV1UserCouponService,
	NewShadowV1UserMessageService,
	NewShadowV1UserOperationLogService,
	NewShadowV1UserService,
	NewShadowV1UserWxService,
	NewWechatV1CouponService,
	NewWechatV1CourseService,
	NewWechatV1EvaluationService,
	NewWechatV1EvaluationTemplateService,
	NewWechatV1GoodRecommendationCategoryService,
	NewWechatV1GoodService,
	NewWechatV1OrderService,
	NewWechatV1UserBindStudentService,
	NewWechatV1UserCouponService,
	NewWechatV1UserService,
	NewWechatV1WxXcxQrcodeService,
	NewYanxueV1AsyncService,
)
