// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package devices_learn_dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gitlab.yc345.tv/backend/devices-learn/internal/data/gorm/devices_learn_model"
)

func newHomeworkAssistantCorrectionRecord(db *gorm.DB, opts ...gen.DOOption) homeworkAssistantCorrectionRecord {
	_homeworkAssistantCorrectionRecord := homeworkAssistantCorrectionRecord{}

	_homeworkAssistantCorrectionRecord.homeworkAssistantCorrectionRecordDo.UseDB(db, opts...)
	_homeworkAssistantCorrectionRecord.homeworkAssistantCorrectionRecordDo.UseModel(&devices_learn_model.HomeworkAssistantCorrectionRecord{})

	tableName := _homeworkAssistantCorrectionRecord.homeworkAssistantCorrectionRecordDo.TableName()
	_homeworkAssistantCorrectionRecord.ALL = field.NewAsterisk(tableName)
	_homeworkAssistantCorrectionRecord.ID = field.NewString(tableName, "id")
	_homeworkAssistantCorrectionRecord.SNID = field.NewString(tableName, "SNId")
	_homeworkAssistantCorrectionRecord.UserID = field.NewString(tableName, "userId")
	_homeworkAssistantCorrectionRecord.Subject = field.NewString(tableName, "subject")
	_homeworkAssistantCorrectionRecord.Data = field.NewField(tableName, "data")
	_homeworkAssistantCorrectionRecord.ImageUrls = field.NewField(tableName, "imageUrls")
	_homeworkAssistantCorrectionRecord.CreatedAt = field.NewTime(tableName, "createdAt")
	_homeworkAssistantCorrectionRecord.UpdatedAt = field.NewTime(tableName, "updatedAt")
	_homeworkAssistantCorrectionRecord.ProcessedImageUrls = field.NewField(tableName, "processedImageUrls")

	_homeworkAssistantCorrectionRecord.fillFieldMap()

	return _homeworkAssistantCorrectionRecord
}

type homeworkAssistantCorrectionRecord struct {
	homeworkAssistantCorrectionRecordDo homeworkAssistantCorrectionRecordDo

	ALL                field.Asterisk
	ID                 field.String // uuid
	SNID               field.String // SNId
	UserID             field.String // userId
	Subject            field.String // 科目
	Data               field.Field  // 批改结果
	ImageUrls          field.Field  // 原图url列表
	CreatedAt          field.Time   // 创建时间
	UpdatedAt          field.Time   // 更新时间
	ProcessedImageUrls field.Field  // 矫正后的图片列表

	fieldMap map[string]field.Expr
}

func (h homeworkAssistantCorrectionRecord) Table(newTableName string) *homeworkAssistantCorrectionRecord {
	h.homeworkAssistantCorrectionRecordDo.UseTable(newTableName)
	return h.updateTableName(newTableName)
}

func (h homeworkAssistantCorrectionRecord) As(alias string) *homeworkAssistantCorrectionRecord {
	h.homeworkAssistantCorrectionRecordDo.DO = *(h.homeworkAssistantCorrectionRecordDo.As(alias).(*gen.DO))
	return h.updateTableName(alias)
}

func (h *homeworkAssistantCorrectionRecord) updateTableName(table string) *homeworkAssistantCorrectionRecord {
	h.ALL = field.NewAsterisk(table)
	h.ID = field.NewString(table, "id")
	h.SNID = field.NewString(table, "SNId")
	h.UserID = field.NewString(table, "userId")
	h.Subject = field.NewString(table, "subject")
	h.Data = field.NewField(table, "data")
	h.ImageUrls = field.NewField(table, "imageUrls")
	h.CreatedAt = field.NewTime(table, "createdAt")
	h.UpdatedAt = field.NewTime(table, "updatedAt")
	h.ProcessedImageUrls = field.NewField(table, "processedImageUrls")

	h.fillFieldMap()

	return h
}

func (h *homeworkAssistantCorrectionRecord) WithContext(ctx context.Context) *homeworkAssistantCorrectionRecordDo {
	return h.homeworkAssistantCorrectionRecordDo.WithContext(ctx)
}

func (h homeworkAssistantCorrectionRecord) TableName() string {
	return h.homeworkAssistantCorrectionRecordDo.TableName()
}

func (h homeworkAssistantCorrectionRecord) Alias() string {
	return h.homeworkAssistantCorrectionRecordDo.Alias()
}

func (h homeworkAssistantCorrectionRecord) Columns(cols ...field.Expr) gen.Columns {
	return h.homeworkAssistantCorrectionRecordDo.Columns(cols...)
}

func (h *homeworkAssistantCorrectionRecord) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := h.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (h *homeworkAssistantCorrectionRecord) fillFieldMap() {
	h.fieldMap = make(map[string]field.Expr, 9)
	h.fieldMap["id"] = h.ID
	h.fieldMap["SNId"] = h.SNID
	h.fieldMap["userId"] = h.UserID
	h.fieldMap["subject"] = h.Subject
	h.fieldMap["data"] = h.Data
	h.fieldMap["imageUrls"] = h.ImageUrls
	h.fieldMap["createdAt"] = h.CreatedAt
	h.fieldMap["updatedAt"] = h.UpdatedAt
	h.fieldMap["processedImageUrls"] = h.ProcessedImageUrls
}

func (h homeworkAssistantCorrectionRecord) clone(db *gorm.DB) homeworkAssistantCorrectionRecord {
	h.homeworkAssistantCorrectionRecordDo.ReplaceConnPool(db.Statement.ConnPool)
	return h
}

func (h homeworkAssistantCorrectionRecord) replaceDB(db *gorm.DB) homeworkAssistantCorrectionRecord {
	h.homeworkAssistantCorrectionRecordDo.ReplaceDB(db)
	return h
}

type homeworkAssistantCorrectionRecordDo struct{ gen.DO }

func (h homeworkAssistantCorrectionRecordDo) Debug() *homeworkAssistantCorrectionRecordDo {
	return h.withDO(h.DO.Debug())
}

func (h homeworkAssistantCorrectionRecordDo) WithContext(ctx context.Context) *homeworkAssistantCorrectionRecordDo {
	return h.withDO(h.DO.WithContext(ctx))
}

func (h homeworkAssistantCorrectionRecordDo) ReadDB() *homeworkAssistantCorrectionRecordDo {
	return h.Clauses(dbresolver.Read)
}

func (h homeworkAssistantCorrectionRecordDo) WriteDB() *homeworkAssistantCorrectionRecordDo {
	return h.Clauses(dbresolver.Write)
}

func (h homeworkAssistantCorrectionRecordDo) Session(config *gorm.Session) *homeworkAssistantCorrectionRecordDo {
	return h.withDO(h.DO.Session(config))
}

func (h homeworkAssistantCorrectionRecordDo) Clauses(conds ...clause.Expression) *homeworkAssistantCorrectionRecordDo {
	return h.withDO(h.DO.Clauses(conds...))
}

func (h homeworkAssistantCorrectionRecordDo) Returning(value interface{}, columns ...string) *homeworkAssistantCorrectionRecordDo {
	return h.withDO(h.DO.Returning(value, columns...))
}

func (h homeworkAssistantCorrectionRecordDo) Not(conds ...gen.Condition) *homeworkAssistantCorrectionRecordDo {
	return h.withDO(h.DO.Not(conds...))
}

func (h homeworkAssistantCorrectionRecordDo) Or(conds ...gen.Condition) *homeworkAssistantCorrectionRecordDo {
	return h.withDO(h.DO.Or(conds...))
}

func (h homeworkAssistantCorrectionRecordDo) Select(conds ...field.Expr) *homeworkAssistantCorrectionRecordDo {
	return h.withDO(h.DO.Select(conds...))
}

func (h homeworkAssistantCorrectionRecordDo) Where(conds ...gen.Condition) *homeworkAssistantCorrectionRecordDo {
	return h.withDO(h.DO.Where(conds...))
}

func (h homeworkAssistantCorrectionRecordDo) Order(conds ...field.Expr) *homeworkAssistantCorrectionRecordDo {
	return h.withDO(h.DO.Order(conds...))
}

func (h homeworkAssistantCorrectionRecordDo) Distinct(cols ...field.Expr) *homeworkAssistantCorrectionRecordDo {
	return h.withDO(h.DO.Distinct(cols...))
}

func (h homeworkAssistantCorrectionRecordDo) Omit(cols ...field.Expr) *homeworkAssistantCorrectionRecordDo {
	return h.withDO(h.DO.Omit(cols...))
}

func (h homeworkAssistantCorrectionRecordDo) Join(table schema.Tabler, on ...field.Expr) *homeworkAssistantCorrectionRecordDo {
	return h.withDO(h.DO.Join(table, on...))
}

func (h homeworkAssistantCorrectionRecordDo) LeftJoin(table schema.Tabler, on ...field.Expr) *homeworkAssistantCorrectionRecordDo {
	return h.withDO(h.DO.LeftJoin(table, on...))
}

func (h homeworkAssistantCorrectionRecordDo) RightJoin(table schema.Tabler, on ...field.Expr) *homeworkAssistantCorrectionRecordDo {
	return h.withDO(h.DO.RightJoin(table, on...))
}

func (h homeworkAssistantCorrectionRecordDo) Group(cols ...field.Expr) *homeworkAssistantCorrectionRecordDo {
	return h.withDO(h.DO.Group(cols...))
}

func (h homeworkAssistantCorrectionRecordDo) Having(conds ...gen.Condition) *homeworkAssistantCorrectionRecordDo {
	return h.withDO(h.DO.Having(conds...))
}

func (h homeworkAssistantCorrectionRecordDo) Limit(limit int) *homeworkAssistantCorrectionRecordDo {
	return h.withDO(h.DO.Limit(limit))
}

func (h homeworkAssistantCorrectionRecordDo) Offset(offset int) *homeworkAssistantCorrectionRecordDo {
	return h.withDO(h.DO.Offset(offset))
}

func (h homeworkAssistantCorrectionRecordDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *homeworkAssistantCorrectionRecordDo {
	return h.withDO(h.DO.Scopes(funcs...))
}

func (h homeworkAssistantCorrectionRecordDo) Unscoped() *homeworkAssistantCorrectionRecordDo {
	return h.withDO(h.DO.Unscoped())
}

func (h homeworkAssistantCorrectionRecordDo) Create(values ...*devices_learn_model.HomeworkAssistantCorrectionRecord) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Create(values)
}

func (h homeworkAssistantCorrectionRecordDo) CreateInBatches(values []*devices_learn_model.HomeworkAssistantCorrectionRecord, batchSize int) error {
	return h.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (h homeworkAssistantCorrectionRecordDo) Save(values ...*devices_learn_model.HomeworkAssistantCorrectionRecord) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Save(values)
}

func (h homeworkAssistantCorrectionRecordDo) First() (*devices_learn_model.HomeworkAssistantCorrectionRecord, error) {
	if result, err := h.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*devices_learn_model.HomeworkAssistantCorrectionRecord), nil
	}
}

func (h homeworkAssistantCorrectionRecordDo) Take() (*devices_learn_model.HomeworkAssistantCorrectionRecord, error) {
	if result, err := h.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*devices_learn_model.HomeworkAssistantCorrectionRecord), nil
	}
}

func (h homeworkAssistantCorrectionRecordDo) Last() (*devices_learn_model.HomeworkAssistantCorrectionRecord, error) {
	if result, err := h.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*devices_learn_model.HomeworkAssistantCorrectionRecord), nil
	}
}

func (h homeworkAssistantCorrectionRecordDo) Find() ([]*devices_learn_model.HomeworkAssistantCorrectionRecord, error) {
	result, err := h.DO.Find()
	return result.([]*devices_learn_model.HomeworkAssistantCorrectionRecord), err
}

func (h homeworkAssistantCorrectionRecordDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*devices_learn_model.HomeworkAssistantCorrectionRecord, err error) {
	buf := make([]*devices_learn_model.HomeworkAssistantCorrectionRecord, 0, batchSize)
	err = h.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (h homeworkAssistantCorrectionRecordDo) FindInBatches(result *[]*devices_learn_model.HomeworkAssistantCorrectionRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return h.DO.FindInBatches(result, batchSize, fc)
}

func (h homeworkAssistantCorrectionRecordDo) Attrs(attrs ...field.AssignExpr) *homeworkAssistantCorrectionRecordDo {
	return h.withDO(h.DO.Attrs(attrs...))
}

func (h homeworkAssistantCorrectionRecordDo) Assign(attrs ...field.AssignExpr) *homeworkAssistantCorrectionRecordDo {
	return h.withDO(h.DO.Assign(attrs...))
}

func (h homeworkAssistantCorrectionRecordDo) Joins(fields ...field.RelationField) *homeworkAssistantCorrectionRecordDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Joins(_f))
	}
	return &h
}

func (h homeworkAssistantCorrectionRecordDo) Preload(fields ...field.RelationField) *homeworkAssistantCorrectionRecordDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Preload(_f))
	}
	return &h
}

func (h homeworkAssistantCorrectionRecordDo) FirstOrInit() (*devices_learn_model.HomeworkAssistantCorrectionRecord, error) {
	if result, err := h.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*devices_learn_model.HomeworkAssistantCorrectionRecord), nil
	}
}

func (h homeworkAssistantCorrectionRecordDo) FirstOrCreate() (*devices_learn_model.HomeworkAssistantCorrectionRecord, error) {
	if result, err := h.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*devices_learn_model.HomeworkAssistantCorrectionRecord), nil
	}
}

func (h homeworkAssistantCorrectionRecordDo) FindByPage(offset int, limit int) (result []*devices_learn_model.HomeworkAssistantCorrectionRecord, count int64, err error) {
	result, err = h.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = h.Offset(-1).Limit(-1).Count()
	return
}

func (h homeworkAssistantCorrectionRecordDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = h.Count()
	if err != nil {
		return
	}

	err = h.Offset(offset).Limit(limit).Scan(result)
	return
}

func (h homeworkAssistantCorrectionRecordDo) Scan(result interface{}) (err error) {
	return h.DO.Scan(result)
}

func (h homeworkAssistantCorrectionRecordDo) Delete(models ...*devices_learn_model.HomeworkAssistantCorrectionRecord) (result gen.ResultInfo, err error) {
	return h.DO.Delete(models)
}

func (h *homeworkAssistantCorrectionRecordDo) withDO(do gen.Dao) *homeworkAssistantCorrectionRecordDo {
	h.DO = *do.(*gen.DO)
	return h
}
