// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package devices_learn_dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gitlab.yc345.tv/backend/devices-learn/internal/data/gorm/devices_learn_model"
)

func newNp(db *gorm.DB, opts ...gen.DOOption) np {
	_np := np{}

	_np.npDo.UseDB(db, opts...)
	_np.npDo.UseModel(&devices_learn_model.Np{})

	tableName := _np.npDo.TableName()
	_np.ALL = field.NewAsterisk(tableName)
	_np.ID = field.NewString(tableName, "id")
	_np.SNID = field.NewString(tableName, "SNId")
	_np.DeviceModel = field.NewString(tableName, "deviceModel")
	_np.PopupKey = field.NewString(tableName, "popupKey")
	_np.PopupCaseKey = field.NewString(tableName, "popupCaseKey")
	_np.PopupCaseGroup = field.NewString(tableName, "popupCaseGroup")
	_np.UserTimeTypeDesc = field.NewString(tableName, "userTimeTypeDesc")
	_np.UserAttribute = field.NewString(tableName, "userAttribute")
	_np.CaseConditionDesc = field.NewString(tableName, "caseConditionDesc")
	_np.LastScene = field.NewString(tableName, "lastScene")
	_np.LastSceneDesc = field.NewString(tableName, "lastSceneDesc")
	_np.LastPopupTime = field.NewField(tableName, "lastPopupTime")
	_np.IsPopup = field.NewBool(tableName, "isPopup")
	_np.UserID = field.NewString(tableName, "userId")
	_np.Stage = field.NewInt64(tableName, "stage")
	_np.Grade = field.NewInt64(tableName, "grade")
	_np.SubmitTime = field.NewField(tableName, "submitTime")
	_np.SubmitAppVision = field.NewString(tableName, "submitAppVision")
	_np.SubmitAnswer = field.NewField(tableName, "submitAnswer")
	_np.CreatedAt = field.NewTime(tableName, "createdAt")
	_np.UpdatedAt = field.NewTime(tableName, "updatedAt")
	_np.StageDesc = field.NewString(tableName, "stageDesc")
	_np.GradeDesc = field.NewString(tableName, "gradeDesc")
	_np.SubmitDesktopVersion = field.NewString(tableName, "submitDesktopVersion")

	_np.fillFieldMap()

	return _np
}

type np struct {
	npDo npDo

	ALL                  field.Asterisk
	ID                   field.String // 记录ID
	SNID                 field.String // 设备SNId
	DeviceModel          field.String // 设备型号
	PopupKey             field.String // 弹窗唯一标识
	PopupCaseKey         field.String // 触发弹窗case唯一标识
	PopupCaseGroup       field.String // 触发弹窗case分组
	UserTimeTypeDesc     field.String // 用户时间描述
	UserAttribute        field.String // 用户特性
	CaseConditionDesc    field.String // 触发条件
	LastScene            field.String // 触发弹窗时最后一次进入到的场景
	LastSceneDesc        field.String // 触发弹窗时最后一次进入到场景描述
	LastPopupTime        field.Field  // 设备最后一次弹窗时间
	IsPopup              field.Bool   // 是否需要弹窗
	UserID               field.String // 提交反馈的用户ID
	Stage                field.Int64  // 提交反馈时用户学段
	Grade                field.Int64  // 提交反馈时用户年级
	SubmitTime           field.Field  // 用户提交时间
	SubmitAppVision      field.String // 用户提交反馈时App版本号
	SubmitAnswer         field.Field  // 用户提交答案
	CreatedAt            field.Time   // 创建时间
	UpdatedAt            field.Time   // 更新时间
	StageDesc            field.String // 提交反馈时用户学段描述
	GradeDesc            field.String // 提交反馈时用户年级描述
	SubmitDesktopVersion field.String // 用户提交反馈时桌面版本号

	fieldMap map[string]field.Expr
}

func (n np) Table(newTableName string) *np {
	n.npDo.UseTable(newTableName)
	return n.updateTableName(newTableName)
}

func (n np) As(alias string) *np {
	n.npDo.DO = *(n.npDo.As(alias).(*gen.DO))
	return n.updateTableName(alias)
}

func (n *np) updateTableName(table string) *np {
	n.ALL = field.NewAsterisk(table)
	n.ID = field.NewString(table, "id")
	n.SNID = field.NewString(table, "SNId")
	n.DeviceModel = field.NewString(table, "deviceModel")
	n.PopupKey = field.NewString(table, "popupKey")
	n.PopupCaseKey = field.NewString(table, "popupCaseKey")
	n.PopupCaseGroup = field.NewString(table, "popupCaseGroup")
	n.UserTimeTypeDesc = field.NewString(table, "userTimeTypeDesc")
	n.UserAttribute = field.NewString(table, "userAttribute")
	n.CaseConditionDesc = field.NewString(table, "caseConditionDesc")
	n.LastScene = field.NewString(table, "lastScene")
	n.LastSceneDesc = field.NewString(table, "lastSceneDesc")
	n.LastPopupTime = field.NewField(table, "lastPopupTime")
	n.IsPopup = field.NewBool(table, "isPopup")
	n.UserID = field.NewString(table, "userId")
	n.Stage = field.NewInt64(table, "stage")
	n.Grade = field.NewInt64(table, "grade")
	n.SubmitTime = field.NewField(table, "submitTime")
	n.SubmitAppVision = field.NewString(table, "submitAppVision")
	n.SubmitAnswer = field.NewField(table, "submitAnswer")
	n.CreatedAt = field.NewTime(table, "createdAt")
	n.UpdatedAt = field.NewTime(table, "updatedAt")
	n.StageDesc = field.NewString(table, "stageDesc")
	n.GradeDesc = field.NewString(table, "gradeDesc")
	n.SubmitDesktopVersion = field.NewString(table, "submitDesktopVersion")

	n.fillFieldMap()

	return n
}

func (n *np) WithContext(ctx context.Context) *npDo { return n.npDo.WithContext(ctx) }

func (n np) TableName() string { return n.npDo.TableName() }

func (n np) Alias() string { return n.npDo.Alias() }

func (n np) Columns(cols ...field.Expr) gen.Columns { return n.npDo.Columns(cols...) }

func (n *np) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := n.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (n *np) fillFieldMap() {
	n.fieldMap = make(map[string]field.Expr, 24)
	n.fieldMap["id"] = n.ID
	n.fieldMap["SNId"] = n.SNID
	n.fieldMap["deviceModel"] = n.DeviceModel
	n.fieldMap["popupKey"] = n.PopupKey
	n.fieldMap["popupCaseKey"] = n.PopupCaseKey
	n.fieldMap["popupCaseGroup"] = n.PopupCaseGroup
	n.fieldMap["userTimeTypeDesc"] = n.UserTimeTypeDesc
	n.fieldMap["userAttribute"] = n.UserAttribute
	n.fieldMap["caseConditionDesc"] = n.CaseConditionDesc
	n.fieldMap["lastScene"] = n.LastScene
	n.fieldMap["lastSceneDesc"] = n.LastSceneDesc
	n.fieldMap["lastPopupTime"] = n.LastPopupTime
	n.fieldMap["isPopup"] = n.IsPopup
	n.fieldMap["userId"] = n.UserID
	n.fieldMap["stage"] = n.Stage
	n.fieldMap["grade"] = n.Grade
	n.fieldMap["submitTime"] = n.SubmitTime
	n.fieldMap["submitAppVision"] = n.SubmitAppVision
	n.fieldMap["submitAnswer"] = n.SubmitAnswer
	n.fieldMap["createdAt"] = n.CreatedAt
	n.fieldMap["updatedAt"] = n.UpdatedAt
	n.fieldMap["stageDesc"] = n.StageDesc
	n.fieldMap["gradeDesc"] = n.GradeDesc
	n.fieldMap["submitDesktopVersion"] = n.SubmitDesktopVersion
}

func (n np) clone(db *gorm.DB) np {
	n.npDo.ReplaceConnPool(db.Statement.ConnPool)
	return n
}

func (n np) replaceDB(db *gorm.DB) np {
	n.npDo.ReplaceDB(db)
	return n
}

type npDo struct{ gen.DO }

func (n npDo) Debug() *npDo {
	return n.withDO(n.DO.Debug())
}

func (n npDo) WithContext(ctx context.Context) *npDo {
	return n.withDO(n.DO.WithContext(ctx))
}

func (n npDo) ReadDB() *npDo {
	return n.Clauses(dbresolver.Read)
}

func (n npDo) WriteDB() *npDo {
	return n.Clauses(dbresolver.Write)
}

func (n npDo) Session(config *gorm.Session) *npDo {
	return n.withDO(n.DO.Session(config))
}

func (n npDo) Clauses(conds ...clause.Expression) *npDo {
	return n.withDO(n.DO.Clauses(conds...))
}

func (n npDo) Returning(value interface{}, columns ...string) *npDo {
	return n.withDO(n.DO.Returning(value, columns...))
}

func (n npDo) Not(conds ...gen.Condition) *npDo {
	return n.withDO(n.DO.Not(conds...))
}

func (n npDo) Or(conds ...gen.Condition) *npDo {
	return n.withDO(n.DO.Or(conds...))
}

func (n npDo) Select(conds ...field.Expr) *npDo {
	return n.withDO(n.DO.Select(conds...))
}

func (n npDo) Where(conds ...gen.Condition) *npDo {
	return n.withDO(n.DO.Where(conds...))
}

func (n npDo) Order(conds ...field.Expr) *npDo {
	return n.withDO(n.DO.Order(conds...))
}

func (n npDo) Distinct(cols ...field.Expr) *npDo {
	return n.withDO(n.DO.Distinct(cols...))
}

func (n npDo) Omit(cols ...field.Expr) *npDo {
	return n.withDO(n.DO.Omit(cols...))
}

func (n npDo) Join(table schema.Tabler, on ...field.Expr) *npDo {
	return n.withDO(n.DO.Join(table, on...))
}

func (n npDo) LeftJoin(table schema.Tabler, on ...field.Expr) *npDo {
	return n.withDO(n.DO.LeftJoin(table, on...))
}

func (n npDo) RightJoin(table schema.Tabler, on ...field.Expr) *npDo {
	return n.withDO(n.DO.RightJoin(table, on...))
}

func (n npDo) Group(cols ...field.Expr) *npDo {
	return n.withDO(n.DO.Group(cols...))
}

func (n npDo) Having(conds ...gen.Condition) *npDo {
	return n.withDO(n.DO.Having(conds...))
}

func (n npDo) Limit(limit int) *npDo {
	return n.withDO(n.DO.Limit(limit))
}

func (n npDo) Offset(offset int) *npDo {
	return n.withDO(n.DO.Offset(offset))
}

func (n npDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *npDo {
	return n.withDO(n.DO.Scopes(funcs...))
}

func (n npDo) Unscoped() *npDo {
	return n.withDO(n.DO.Unscoped())
}

func (n npDo) Create(values ...*devices_learn_model.Np) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Create(values)
}

func (n npDo) CreateInBatches(values []*devices_learn_model.Np, batchSize int) error {
	return n.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (n npDo) Save(values ...*devices_learn_model.Np) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Save(values)
}

func (n npDo) First() (*devices_learn_model.Np, error) {
	if result, err := n.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*devices_learn_model.Np), nil
	}
}

func (n npDo) Take() (*devices_learn_model.Np, error) {
	if result, err := n.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*devices_learn_model.Np), nil
	}
}

func (n npDo) Last() (*devices_learn_model.Np, error) {
	if result, err := n.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*devices_learn_model.Np), nil
	}
}

func (n npDo) Find() ([]*devices_learn_model.Np, error) {
	result, err := n.DO.Find()
	return result.([]*devices_learn_model.Np), err
}

func (n npDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*devices_learn_model.Np, err error) {
	buf := make([]*devices_learn_model.Np, 0, batchSize)
	err = n.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (n npDo) FindInBatches(result *[]*devices_learn_model.Np, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return n.DO.FindInBatches(result, batchSize, fc)
}

func (n npDo) Attrs(attrs ...field.AssignExpr) *npDo {
	return n.withDO(n.DO.Attrs(attrs...))
}

func (n npDo) Assign(attrs ...field.AssignExpr) *npDo {
	return n.withDO(n.DO.Assign(attrs...))
}

func (n npDo) Joins(fields ...field.RelationField) *npDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Joins(_f))
	}
	return &n
}

func (n npDo) Preload(fields ...field.RelationField) *npDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Preload(_f))
	}
	return &n
}

func (n npDo) FirstOrInit() (*devices_learn_model.Np, error) {
	if result, err := n.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*devices_learn_model.Np), nil
	}
}

func (n npDo) FirstOrCreate() (*devices_learn_model.Np, error) {
	if result, err := n.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*devices_learn_model.Np), nil
	}
}

func (n npDo) FindByPage(offset int, limit int) (result []*devices_learn_model.Np, count int64, err error) {
	result, err = n.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = n.Offset(-1).Limit(-1).Count()
	return
}

func (n npDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = n.Count()
	if err != nil {
		return
	}

	err = n.Offset(offset).Limit(limit).Scan(result)
	return
}

func (n npDo) Scan(result interface{}) (err error) {
	return n.DO.Scan(result)
}

func (n npDo) Delete(models ...*devices_learn_model.Np) (result gen.ResultInfo, err error) {
	return n.DO.Delete(models)
}

func (n *npDo) withDO(do gen.Dao) *npDo {
	n.DO = *do.(*gen.DO)
	return n
}
