import type { AgentToolConfig } from '@/api/business-lines'
import {
  resolvePreferredAgentCliConfigId,
  resolvePreferredAgentCliToolId,
} from '@shared/utils/agent-cli-defaults'
import type {
  WorkflowTemplateNode,
  WorkflowTemplateNodeInput,
} from '@/types/api/workflow'
import { PROJECT_DETAIL_SUPPORTED_CLI_TOOLS } from './projects-detail-workflow.constants'
import type {
  ProjectDetailSupportedCliToolId,
  WorkflowTemplateNodeForm,
  WorkflowTemplateNodeInputForm,
} from './projects-detail-workflow.types'

export function isProjectDetailSupportedCliToolId(
  toolId: string,
): toolId is ProjectDetailSupportedCliToolId {
  return PROJECT_DETAIL_SUPPORTED_CLI_TOOLS.some((tool) => tool.id === toolId)
}

export function createEmptyWorkflowNodeInput(): WorkflowTemplateNodeInputForm {
  return {
    prompt: '',
    agentCliId: '',
    agentCliConfigId: '',
    loopEnabled: false,
    earlyExitMarkerEnabled: false,
    earlyExitMarkerFileName: '',
  }
}

export function normalizeWorkflowNodeInput(
  input: WorkflowTemplateNodeInput | WorkflowTemplateNodeInputForm | undefined,
): WorkflowTemplateNodeInputForm {
  if (!input || typeof input !== 'object') {
    return createEmptyWorkflowNodeInput()
  }

  const rawInput = input as Record<string, unknown>
  const prompt = typeof rawInput.prompt === 'string' ? rawInput.prompt : ''
  const rawAgentCliId =
    typeof rawInput.agentCliId === 'string'
      ? rawInput.agentCliId
      : typeof rawInput.cliToolId === 'string'
        ? rawInput.cliToolId
        : ''
  const agentCliId = isProjectDetailSupportedCliToolId(rawAgentCliId) ? rawAgentCliId : ''
  const agentCliConfigId =
    typeof rawInput.agentCliConfigId === 'string'
      ? rawInput.agentCliConfigId
      : typeof rawInput.agentToolConfigId === 'string'
        ? rawInput.agentToolConfigId
        : ''
  const loopEnabled =
    typeof rawInput.loopEnabled === 'boolean'
      ? rawInput.loopEnabled
      : Boolean(
          rawInput.earlyExitMarkerEnabled ||
            (typeof rawInput.maxLoops === 'number' && rawInput.maxLoops > 1),
        )
  const earlyExitMarkerEnabled = Boolean(rawInput.earlyExitMarkerEnabled)
  const earlyExitMarkerFileName =
    typeof rawInput.earlyExitMarkerFileName === 'string' ? rawInput.earlyExitMarkerFileName : ''

  return {
    prompt,
    agentCliId,
    agentCliConfigId,
    loopEnabled,
    earlyExitMarkerEnabled,
    earlyExitMarkerFileName,
  }
}

export function resolveWorkflowNodeInputByContext(
  input: WorkflowTemplateNodeInput | WorkflowTemplateNodeInputForm | undefined,
  configuredTools: Array<{ id: ProjectDetailSupportedCliToolId; label: string }>,
  configsByTool: Partial<Record<ProjectDetailSupportedCliToolId, AgentToolConfig[]>>,
  defaultToolId?: string | null,
): WorkflowTemplateNodeInputForm {
  if (configuredTools.length === 0) {
    return {
      ...normalizeWorkflowNodeInput(input),
      agentCliId: '',
      agentCliConfigId: '',
    }
  }

  const nextInput = normalizeWorkflowNodeInput(input)
  const agentCliId = resolvePreferredAgentCliToolId({
    currentToolId: nextInput.agentCliId as ProjectDetailSupportedCliToolId | '',
    defaultToolId,
    configuredTools,
  })

  if (!agentCliId) {
    return {
      ...nextInput,
      agentCliId: '',
      agentCliConfigId: '',
    }
  }

  const toolConfigs = configsByTool[agentCliId] ?? []

  return {
    ...nextInput,
    agentCliId,
    agentCliConfigId: resolvePreferredAgentCliConfigId(
      toolConfigs,
      nextInput.agentCliConfigId,
    ),
  }
}

function isAutoGeneratedNodeName(name: string): boolean {
  return /^step-\d+$/.test(name.trim())
}

export function normalizeWorkflowNodes(nodes: WorkflowTemplateNodeForm[]) {
  return [...nodes]
    .sort((left, right) => left.nodeOrder - right.nodeOrder)
    .map((node, index) => ({
      ...node,
      nodeOrder: index + 1,
      name:
        !node.name.trim() || isAutoGeneratedNodeName(node.name)
          ? `step-${index + 1}`
          : node.name.trim(),
      requiresApproval: Boolean(node.requiresApproval),
      requiresArtifact: Boolean(node.requiresArtifact),
      maxLoops: Math.max(Number(node.maxLoops) || 1, 1),
      input: normalizeWorkflowNodeInput(node.input),
    }))
}

export function serializeWorkflowNodeInput(
  input: WorkflowTemplateNodeInputForm,
): WorkflowTemplateNodeInput | undefined {
  const normalizedPrompt = input.prompt.trim()
  const normalizedConfigId = input.agentCliConfigId.trim()
  const normalizedMarkerFileName = input.earlyExitMarkerFileName.trim()
  const payload: WorkflowTemplateNodeInput = {}

  if (normalizedPrompt) {
    payload.prompt = normalizedPrompt
  }

  if (input.agentCliId) {
    payload.agentCliId = input.agentCliId
    if (normalizedConfigId) {
      payload.agentCliConfigId = normalizedConfigId
    }
  }

  if (input.loopEnabled) {
    payload.loopEnabled = true
    payload.earlyExitMarkerEnabled = true
  }

  if (input.loopEnabled && normalizedMarkerFileName) {
    payload.earlyExitMarkerFileName = normalizedMarkerFileName
  }

  return Object.keys(payload).length > 0 ? payload : undefined
}

export function buildWorkflowNodesForSubmit(
  nodes: WorkflowTemplateNodeForm[],
): WorkflowTemplateNode[] {
  return normalizeWorkflowNodes(nodes).map((node) => ({
    ...node,
    input: {
      ...serializeWorkflowNodeInput(node.input),
      ...(node.input.loopEnabled &&
      node.maxLoops !== undefined &&
      node.maxLoops > 1
        ? { maxLoops: node.maxLoops }
        : {}),
    },
  }))
}

export function validateWorkflowNodesPlain(
  nodes: WorkflowTemplateNode[],
  options: {
    configuredCliToolIdSet: Set<ProjectDetailSupportedCliToolId>
    hasConfiguredCliTools: boolean
  },
): string {
  if (nodes.length === 0) {
    return '至少需要一个节点'
  }

  if (!options.hasConfiguredCliTools) {
    return '当前业务线暂无已配置 Agent CLI，请先在业务线设置中配置'
  }

  for (let index = 0; index < nodes.length; index += 1) {
    const node = nodes[index]
    if (!node || !node.name.trim()) {
      return `节点 #${index + 1} 名称不能为空`
    }

    const nodeInput = normalizeWorkflowNodeInput(node.input)
    if (!nodeInput.agentCliId) {
      return `节点 #${index + 1} 请选择 Agent CLI`
    }

    if (
      !options.configuredCliToolIdSet.has(nodeInput.agentCliId as ProjectDetailSupportedCliToolId)
    ) {
      return `节点 #${index + 1} 的 Agent CLI 不可用，请重新选择`
    }

    if (nodeInput.loopEnabled && !nodeInput.earlyExitMarkerFileName.trim()) {
      return `节点 #${index + 1} 已启用循环，请填写 Marker 文件名`
    }
  }

  return ''
}

/**
 * Validates a business-line workflow template before copying it into the current project.
 * Skeleton templates (no Agent CLI / config) must be completed in business line management first.
 */
export function validateBusinessLineWorkflowTemplateForProjectCopy(
  nodes: WorkflowTemplateNode[],
  options: {
    configuredCliToolIdSet: Set<ProjectDetailSupportedCliToolId>
    configsByTool: Partial<Record<ProjectDetailSupportedCliToolId, AgentToolConfig[]>>
    hasConfiguredCliTools: boolean
  },
): string {
  const plainError = validateWorkflowNodesPlain(nodes, {
    configuredCliToolIdSet: options.configuredCliToolIdSet,
    hasConfiguredCliTools: options.hasConfiguredCliTools,
  })

  if (plainError) {
    if (plainError.includes('请选择 Agent CLI')) {
      return '该业务线工作流模板尚未配置 Agent CLI，请先到业务线工作流管理中完善各节点后再复制'
    }
    if (plainError.includes('暂无已配置 Agent CLI')) {
      return '当前业务线尚未配置 Agent CLI，请先在业务线设置中配置后再复制'
    }
    return plainError
  }

  for (let index = 0; index < nodes.length; index += 1) {
    const nodeInput = normalizeWorkflowNodeInput(nodes[index]?.input)
    if (!nodeInput.agentCliId) {
      continue
    }

    const toolId = nodeInput.agentCliId as ProjectDetailSupportedCliToolId
    const configs = options.configsByTool[toolId] ?? []
    const configValid =
      Boolean(nodeInput.agentCliConfigId.trim()) &&
      configs.some((config) => config.id === nodeInput.agentCliConfigId)

    if (!configValid) {
      return `节点 #${index + 1} 缺少有效的 Agent CLI 配置，请先到业务线工作流管理中完善后再复制`
    }
  }

  return ''
}
