// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: desktop/v1/desktop.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DesktopClient is the client API for Desktop service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DesktopClient interface {
	// 查询每日数据
	QueryDailyData(ctx context.Context, in *QueryDailyDataRequest, opts ...grpc.CallOption) (*QueryDailyDataReply, error)
}

type desktopClient struct {
	cc grpc.ClientConnInterface
}

func NewDesktopClient(cc grpc.ClientConnInterface) DesktopClient {
	return &desktopClient{cc}
}

func (c *desktopClient) QueryDailyData(ctx context.Context, in *QueryDailyDataRequest, opts ...grpc.CallOption) (*QueryDailyDataReply, error) {
	out := new(QueryDailyDataReply)
	err := c.cc.Invoke(ctx, "/api.desktop.v1.Desktop/QueryDailyData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DesktopServer is the server API for Desktop service.
// All implementations must embed UnimplementedDesktopServer
// for forward compatibility
type DesktopServer interface {
	// 查询每日数据
	QueryDailyData(context.Context, *QueryDailyDataRequest) (*QueryDailyDataReply, error)
	mustEmbedUnimplementedDesktopServer()
}

// UnimplementedDesktopServer must be embedded to have forward compatible implementations.
type UnimplementedDesktopServer struct {
}

func (UnimplementedDesktopServer) QueryDailyData(context.Context, *QueryDailyDataRequest) (*QueryDailyDataReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryDailyData not implemented")
}
func (UnimplementedDesktopServer) mustEmbedUnimplementedDesktopServer() {}

// UnsafeDesktopServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DesktopServer will
// result in compilation errors.
type UnsafeDesktopServer interface {
	mustEmbedUnimplementedDesktopServer()
}

func RegisterDesktopServer(s grpc.ServiceRegistrar, srv DesktopServer) {
	s.RegisterService(&Desktop_ServiceDesc, srv)
}

func _Desktop_QueryDailyData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDailyDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesktopServer).QueryDailyData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.desktop.v1.Desktop/QueryDailyData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesktopServer).QueryDailyData(ctx, req.(*QueryDailyDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Desktop_ServiceDesc is the grpc.ServiceDesc for Desktop service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Desktop_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.desktop.v1.Desktop",
	HandlerType: (*DesktopServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryDailyData",
			Handler:    _Desktop_QueryDailyData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "desktop/v1/desktop.proto",
}
