/**
 * Mind2Build Shared Package
 * Exports common types, constants, and utilities
 */

export * from './types';
export * from './utils';

// Re-export constants separately to avoid conflicts
export {
  MESSAGE_ROUTE_TO_ALL,
  MESSAGE_ROUTE_TO_SELF,
  ACTION_USER_REQUIREMENT,
  ACTION_WRITE_REQUIREMENT_SPEC,
  ACTION_WRITE_PRD,
  ACTION_WRITE_DESIGN,
  ACTION_WRITE_CODE,
  ACTION_WRITE_TEST,
  ACTION_WRITE_CODE_REVIEW,
  ACTION_FIX_BUG,
  ACTION_SEARCH_ENHANCED_QA,
  ACTION_DATA_ANALYSIS,
  ACTION_COORDINATE,
  ACTION_RUN_CODE,
  ACTION_BREAKDOWN_TASKS,
  ACTION_WRITE_SUB_PROJECT_DESIGN,
  ACTION_GENERATE_TASK,
  ACTION_CODE_REVIEW,
  ROLE_PRODUCT_MANAGER,
  ROLE_ARCHITECT,
  ROLE_ENGINEER,
  ROLE_QA_ENGINEER,
  ROLE_TEAM_LEADER,
  ROLE_DATA_ANALYST,
  ROLE_PROJECT_MANAGER,
  DEFAULT_MAX_BUDGET,
  DEFAULT_MAX_RETRY,
  DEFAULT_REQUEST_TIMEOUT,
  DEFAULT_MAX_TOKENS,
  DEFAULT_TEMPERATURE,
  DEFAULT_N_ROUND,
  MODEL_GPT_4_TURBO,
  MODEL_GPT_4,
  MODEL_GPT_35_TURBO,
  MODEL_CLAUDE_3_OPUS,
  MODEL_CLAUDE_3_SONNET,
  MODEL_GLM_4_FLASH,
  MODEL_GLM_4,
  COST_PER_1K_TOKENS,
  FILE_EXTENSIONS,
  DEFAULT_PRD_TEMPLATE,
  DEFAULT_DESIGN_TEMPLATE,
  DEFAULT_CODE_TEMPLATE,
} from './constants';

