syntax = "proto3";

package wechat.v1;

import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";
import "validate/validate.proto";

option go_package = "gitlab.yc345.tv/backend/yanxue/api/wechat/v1;v1";

//优惠券表
service Coupon {
  //优惠券表-列表数据查询
  rpc GetCouponList(GetCouponListReq) returns (GetCouponListReply) {
    option (google.api.http) = {
      post: "/yanxue/wechat/v1/coupon/list"
      body: "*"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      parameters: {
        headers: {
          name: "Authorization"
          description: "TOKEN"
          type: STRING
          required: true
        }
      }
    };
  }
  //查询优惠券适用的商品信息
  rpc GetCouponAdaptGoodInfoList(GetCouponAdaptGoodInfoListReq) returns (GetCouponAdaptGoodInfoListReply) {
    option (google.api.http) = {
      post: "/yanxue/wechat/v1/coupon/getCouponAdaptGoodInfoList"
      body: "*"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      parameters: {
        headers: {
          name: "Authorization"
          description: "TOKEN"
          type: STRING
          required: true
        }
      }
    };
  }
  //查询优惠券信息
  rpc GetCouponInfoById(GetCouponInfoByIdReq) returns (GetCouponInfoByIdReply) {
    option (google.api.http) = {get: "/yanxue/wechat/v1/coupon/getCouponInfoById"};
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      parameters: {
        headers: {
          name: "Authorization"
          description: "TOKEN"
          type: STRING
          required: true
        }
      }
    };
  }
}

//请求-通过优惠券ID查询优惠券信息
message GetCouponInfoByIdReq {
  string couponId = 1 [(validate.rules).string = {uuid: true}]; // 优惠券ID
}

//响应-通过优惠券ID查询优惠券信息
message GetCouponInfoByIdReply {
  CouponInfo couponInfo = 1; // 优惠券信息
}

//请求-查询优惠券适用的商品信息
message GetCouponAdaptGoodInfoListReq {
  string couponId = 1 [(validate.rules).string = {uuid: true}]; // 优惠券ID
}

//优惠券适用的商品信息
message AdaptGoodInfo {
  string goodId = 1; // 商品ID
  string goodName = 2; // 商品名称
  repeated string mainImage = 3; // 主图(多张)
  repeated string detailImages = 4; // 详情图(多张)
  double price = 5; // 价格
}

//响应-查询优惠券适用的商品信息
message GetCouponAdaptGoodInfoListReply {
  repeated AdaptGoodInfo list = 1; // 优惠券列表
}

//优惠券表信息
message CouponInfo {
  string id = 1; // id
  string name = 2; // 优惠券名称
  int32 discountAmount = 5; // 优惠金额
  string pushType = 6; // 推送方式：public:公开；private:私密
  string couponType = 7; // 优惠券类型：common:通用；good:商品
  int32 minAmount = 9; // 门槛金额：为0则表示无门槛
  string validStartTime = 10; // 使用开始时间
  string validEndTime = 11; // 使用结束时间
  string claimStartTime = 12; // 领取开始时间
  string claimEndTime = 13; // 领取结束时间
  int32 limitPerUser = 15; // 每人限领张数
  int32 couponValidDays = 19; // 优惠券领取后多少天内有效
  int32 receivedCount = 20; // 已领取数量
}

//请求-优惠券表-列表数据查询
message GetCouponListReq {
  string goodId = 1; // 商品ID
}

//响应-优惠券表-列表数据查询
message GetCouponListReply {
  repeated CouponInfo list = 2; // 列表数据
}
