syntax = "proto3";

package wechat.v1;

import "google/api/annotations.proto";
import "google/protobuf/struct.proto";
import "protoc-gen-openapiv2/options/annotations.proto";
import "validate/validate.proto";
import "wechat/v1/good.proto";

option go_package = "gitlab.yc345.tv/backend/yanxue/api/wechat/v1;v1";

// 订单
service Order {
  // 订单-获取用户订单列表
  rpc GetOrderList(GetOrderListReq) returns (GetOrderListReply) {
    option (google.api.http) = {
      post: "/yanxue/wechat/v1/order/list"
      body: "*"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      parameters: {
        headers: {
          name: "Authorization"
          description: "TOKEN"
          type: STRING
          required: true
        }
      }
    };
  }
  // 订单-获取订单商品详情
  rpc GetOrderGoodInfo(GetOrderGoodInfoReq) returns (GetOrderGoodInfoReply) {
    option (google.api.http) = {
      post: "/yanxue/wechat/v1/order/good/info"
      body: "*"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      parameters: {
        headers: {
          name: "Authorization"
          description: "TOKEN"
          type: STRING
          required: true
        }
      }
    };
  }
  // 订单-创建小程序订单
  rpc CreateMiniProgramOrder(CreateMiniProgramOrderReq) returns (CreateMiniProgramOrderReply) {
    option (google.api.http) = {
      post: "/yanxue/wechat/v1/order/createMiniProgramOrder"
      body: "*"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      parameters: {
        headers: {
          name: "Authorization"
          description: "TOKEN"
          type: STRING
          required: true
        }
      }
    };
  }
  // 订单-查询订单支付信息
  rpc GetOrderPaymentInfo(GetOrderPaymentInfoReq) returns (GetOrderPaymentInfoReply) {
    option (google.api.http) = {get: "/yanxue/wechat/v1/order/getOrderPaymentInfo"};
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      parameters: {
        headers: {
          name: "Authorization"
          description: "TOKEN"
          type: STRING
          required: true
        }
      }
    };
  }
  // 订单-发起微信支付
  rpc CreateWechatPaymentOrder(CreateWechatPaymentOrderReq) returns (CreateWechatPaymentOrderReply) {
    option (google.api.http) = {
      post: "/yanxue/wechat/v1/order/createWechatPaymentOrder"
      body: "*"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      parameters: {
        headers: {
          name: "Authorization"
          description: "TOKEN"
          type: STRING
          required: true
        }
      }
    };
  }
  // 订单-查询订单支付状态
  rpc GetOrderPaymentStatus(GetOrderPaymentStatusReq) returns (GetOrderPaymentStatusReply) {
    option (google.api.http) = {get: "/yanxue/wechat/v1/order/getOrderPaymentStatus"};
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      parameters: {
        headers: {
          name: "Authorization"
          description: "TOKEN"
          type: STRING
          required: true
        }
      }
    };
  }
  // 订单-更改订单状态
  rpc UpdateOrderStatus(UpdateOrderStatusReq) returns (UpdateOrderStatusReply) {
    option (google.api.http) = {
      post: "/yanxue/wechat/v1/order/updateOrderStatus"
      body: "*"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      parameters: {
        headers: {
          name: "Authorization"
          description: "TOKEN"
          type: STRING
          required: true
        }
      }
    };
  }
}

//请求-更改订单状态
message UpdateOrderStatusReq {
  string orderId = 1 [(validate.rules).string.uuid = true]; // 订单ID
  string status = 2 [(validate.rules).string = {min_len: 1}]; // 订单状态：closed：已关闭
}

//响应-更改订单状态
message UpdateOrderStatusReply {}

//请求-查询订单支付状态
message GetOrderPaymentStatusReq {
  string orderId = 1 [(validate.rules).string.uuid = true]; // 订单ID
}

//响应-查询订单支付状态
message GetOrderPaymentStatusReply {
  bool isFinishPay = 1; // 是否完成支付：true:已完成，false:未完成
}

//请求-发起微信支付
message CreateWechatPaymentOrderReq {
  string orderId = 1 [(validate.rules).string.uuid = true]; // 订单ID
}

//响应-发起微信支付
message CreateWechatPaymentOrderReply {
  string prePayId = 1; // 预支付ID
  string jsSdkOptions = 2; // JSSDK配置
}

//请求-查询订单支付信息
message GetOrderPaymentInfoReq {
  string orderId = 1 [(validate.rules).string = {min_len: 1}]; // 订单ID
}

//响应-查询订单支付信息
message GetOrderPaymentInfoReply {
  string goodName = 1; // 商品名称
  repeated string mainImage = 2; // 主图(多张)
  int32 goodNums = 3; // 购买商品数量
  string orderNumber = 4; // 订单编号
  float paymentAmount = 5; // 支付金额
  string paymentTime = 6; // 支付时间
  int32 discountAmount = 7; // 优惠金额
}

//请求-创建小程序订单
message CreateMiniProgramOrderReq {
  string goodId = 1 [(validate.rules).string = {min_len: 1}]; // 商品ID
  string parentRemark = 2 [(validate.rules).string = {max_len: 200}]; // 家长备注
  string userCouponId = 3; // 用户优惠券ID
  google.protobuf.Struct courseAppointmentDraft = 4; // 预约草稿
}

//响应-创建小程序订单
message CreateMiniProgramOrderReply {
  string orderId = 1; // 订单ID
}

// 渠道信息
message ChannelInfo {
  string id = 1; // id
  string name = 2; // 名称
  string verificationCodeType = 3; // 渠道卷码类型none:无卷码required:必须optional:可有可无
}

// 订单信息
message OrderInfo {
  string id = 1; // id
  string orderNumber = 2; // 订单编号
  string goodId = 3; // 商品 Id
  string goodName = 4; // 商品名称
  string channelId = 5; // 渠道Id
  string channelName = 6; // 渠道名称
  int32 orderPrice = 7; // 订单金额：单位分
  string phone = 8; // 联系方式(手机号)
  string paymentTime = 9; // 支付时间
  string status = 10; // 订单状态 pending待预约 success已预约 completed已完成 refunded已退款 pendingPayment待支付 closed交易关闭
  int32 discountAmount = 11; // 优惠金额
  string parentRemark = 12; // 家长备注
  string payId = 13; // 支付订单号
  string refundId = 14; // 退款订单号
  string refundReason = 15; // 退款原因
  string userCouponId = 16; // 用户优惠券Id
  string paymentDeadline = 17; // 支付截止时间
  string createdAt = 18; // 开始时间
  string updatedAt = 19; // 更新时间
  string goodType = 20; // 商品类型：single:单日营；multi：多日营；
  float refundAmount = 21; // 退款金额
  string refundTime = 22; // 退款时间
  string serviceStatus = 23; // 服务状态 pending待预约 success已预约 completed已出行
}

message GetOrderListReq {
  option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_schema) = {
    json_schema: {
      required: [
        "page",
        "pageSize"
      ]
    }
  };
  int32 page = 1 [(validate.rules).int32.gt = 0]; // 页码
  int32 pageSize = 2 [(validate.rules).int32.gt = 0]; // 页数
  repeated string status = 3; // 订单状态 pendingPayment待支付 pending支付成功 closed订单关闭 refunded已退款 refunding退款中 failedRefund 退款失败
  repeated string serviceStatus = 4; // 服务状态 pending待预约 success已预约 completed已出行
}

message GetOrderListReply {
  int32 total = 1; // 总数
  repeated OrderInfo orderList = 2; // 订单列表
}

message GetOrderGoodInfoReq {
  option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_schema) = {
    json_schema: {
      required: ["id"]
    }
  };
  string id = 1 [(validate.rules).string.uuid = true]; // id
}

message GetOrderGoodInfoReply {
  OrderInfo orderInfo = 1; // 订单信息
  GoodInfo goodInfo = 2; // 商品信息
  ChannelInfo channelInfo = 3; // 渠道信息
  google.protobuf.Struct courseAppointmentDraft = 4; // 预约草稿
}
