export {
  PROJECT_DOCS_QUERY_STREAM_CHARS_PER_TICK as KNOWLEDGE_BASE_STREAM_CHARS_PER_TICK,
  PROJECT_DOCS_QUERY_STREAM_TICK_MS as KNOWLEDGE_BASE_STREAM_TICK_MS,
} from '@shared/constants/project-docs-query-stream'
