syntax = "proto3";

package shadow.v1;

import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";
import "validate/validate.proto";

option go_package = "gitlab.yc345.tv/backend/yanxue/api/shadow/v1;v1";

service Contract {
  // 导入创建合同的用户信息
  rpc ImportContractUserInfoByCsvFile(ImportContractUserInfoByCsvFileReq) returns (ImportContractUserInfoByCsvFileReply) {
    option (google.api.http) = {
      post: "/yanxue/api/shadow/v1/importContractUserInfoByCsvFile"
      body: "*"
    };
  }
  // 催签流程中签署人
  rpc UrgeSignFlow(UrgeSignFlowReq) returns (UrgeSignFlowReply) {
    option (google.api.http) = {
      post: "/yanxue/api/shadow/v1/urgeSignFlow"
      body: "*"
    };
  }
  // 添加合同模版（有则更新，无则新增）
  rpc StoreContractTemplate(StoreContractTemplateReq) returns (StoreContractTemplateReply) {
    option (google.api.http) = {
      post: "/yanxue/api/shadow/v1/storeContractTemplate"
      body: "*"
    };
  }
  // 修改合同模版状态
  rpc UpdateContractTemplateStatus(UpdateContractTemplateStatusReq) returns (UpdateContractTemplateStatusReply) {
    option (google.api.http) = {
      post: "/yanxue/api/shadow/v1/updateContractTemplateStatus"
      body: "*"
    };
  }
  // 查询合同模版列表
  rpc QueryContractTemplateList(QueryContractTemplateListReq) returns (QueryContractTemplateListReply) {
    option (google.api.http) = {
      post: "/yanxue/api/shadow/v1/queryContractTemplateList"
      body: "*"
    };
  }
  // 撤销签署流程
  rpc RevokeSignFlow(RevokeSignFlowReq) returns (RevokeSignFlowReply) {
    option (google.api.http) = {
      post: "/yanxue/api/shadow/v1/revokeSignFlow"
      body: "*"
    };
  }
  // 查询异步任务结果
  rpc QueryAsyncTaskResult(QueryAsyncTaskResultReq) returns (QueryAsyncTaskResultReply) {
    option (google.api.http) = {get: "/yanxue/api/shadow/v1/queryAsyncTaskResult"};
  }
  // 查询合同列表
  rpc QueryContractList(QueryContractListReq) returns (QueryContractListReply) {
    option (google.api.http) = {
      post: "/yanxue/api/shadow/v1/queryContractList"
      body: "*"
    };
  }
  // 查询主题列表
  rpc QueryTopicList(QueryTopicListReq) returns (QueryTopicListReply) {
    option (google.api.http) = {get: "/yanxue/api/shadow/v1/queryTopicList"};
  }
  // 导出合同列表
  rpc ExportContractList(ExportContractListReq) returns (ExportContractListReply) {
    option (google.api.http) = {
      post: "/yanxue/api/shadow/v1/exportContractList"
      body: "*"
    };
  }
  // 生成合同
  rpc GenerateContractByUserInfo(GenerateContractByUserInfoReq) returns (GenerateContractByUserInfoReply) {
    option (google.api.http) = {
      post: "/yanxue/api/shadow/v1/generateContractByUserInfo"
      body: "*"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      parameters: {
        headers: {
          name: "Authorization"
          description: "TOKEN"
          type: STRING
          required: true
        }
      }
    };
  }
}

message GenerateContractByUserInfoReq {
  string courseAppointmentId = 1 [(validate.rules).string = {min_len: 1}]; // 课程预约ID
  string parentName = 2 [(validate.rules).string = {min_len: 1}]; // 家长姓名
  string parentPhone = 3 [(validate.rules).string = {min_len: 1}]; // 家长手机号
  string childName = 4 [(validate.rules).string = {min_len: 1}]; // 孩子姓名
  string childId = 5 [(validate.rules).string = {min_len: 1}]; // 孩子身份证号
  string activityStartDate = 6 [(validate.rules).string = {min_len: 1}]; // 活动开始日期
  string activityEndDate = 7 [(validate.rules).string = {min_len: 1}]; // 活动结束日期
  string cost = 8 [(validate.rules).string = {min_len: 1}]; // 活动费用
  string costCapital = 9 [(validate.rules).string = {min_len: 1}]; // 活动费用大写
  string payEndDate = 10 [(validate.rules).string = {min_len: 1}]; // 付款截止日期
}

message GenerateContractByUserInfoReply {
  string asyncTaskId = 1; // 异步任务ID
}

message ExportContractListReq {
  string childName = 1; // 孩子姓名
  string parentPhone = 2; // 家长电话
  string topic = 3; // 合同主题
  int32 status = 4; // 合同状态
  string activityStartDate = 5; // 营期开始时间
}

message ExportContractListReply {
  string downloadUrl = 1; // 下载链接
}

message QueryTopicListReq {}

message QueryTopicListReply {
  repeated string list = 1; // 主题列表
}

message QueryContractListReq {
  string childName = 1; // 孩子姓名
  string parentPhone = 2; // 家长电话
  string topic = 3; // 合同主题
  int32 status = 4; // 合同状态
  string activityStartDate = 5; // 营期开始时间
  int32 contractType = 6; // 合同类型: 1：单日营；2：多日营
  int32 page = 7;
  int32 pageSize = 8;
}

message ContractItem {
  string id = 1; // 主键ID
  string signFlowId = 2; // E签宝合同ID
  string parentName = 3; // 家长姓名
  string parentPhone = 4; // 家长电话
  string childName = 5; // 孩子姓名
  string childPhone = 6; // 孩子电话
  string childId = 7; // 孩子身份证
  string userSource = 8; // 用户来源
  string topic = 9; // 合同主题
  string activityStartDate = 10; // 营期开始时间
  string activityEndDate = 11; // 营期结束时间
  string purchaseChannel = 12; // 购买渠道
  string childGrade = 13; // 孩子年级
  string childGender = 14; // 孩子性别
  string cost = 15; // 参营费用
  string costCapital = 16; // 参营费用大写
  string payEndDate = 17; // 支付截止时间
  int32 contractStatus = 18; // 合同状态（0-草稿 1-签署中 2-完成 3-撤销 5-过期 7-拒签）
  string contractLink = 19; // 合同链接
  int32 contractType = 20; // 合同类型：1：单日营；2：多日营
  string courseAppointmentId = 21; // 课程预约ID
  string createdAt = 22; // 创建时间
  string updatedAt = 23; // 更新时间
}

message QueryContractListReply {
  int32 total = 1; // 总数
  repeated ContractItem list = 2; // 合同列表
}

message QueryAsyncTaskResultReq {
  string taskId = 1 [(validate.rules).string = {min_len: 1}]; // 异步任务ID
}

message QueryAsyncTaskResultReply {
  string taskId = 1; // 任务ID
  int32 status = 2; // 状态：0-待处理 1-执行中 2-成功 3-失败
  string errorInfo = 3; // 错误信息
}

message ImportContractUserInfoByCsvFileReq {
  string fileUrl = 1 [(validate.rules).string = {min_len: 1}]; // 文件地址
}

message ImportContractUserInfoByCsvFileReply {
  string asyncTaskId = 1; // 异步任务ID
}

message UrgeSignFlowReq {
  string signFlowId = 1 [(validate.rules).string = {min_len: 1}]; // 合同签署流程ID
  string psnAccount = 2 [(validate.rules).string = {min_len: 1}]; // 被催签人账号（手机号）
}

message UrgeSignFlowReply {
  bool isSucceed = 1; // 是否成功
}

message StoreContractTemplateReq {
  string id = 1; // 模版ID
  string templateName = 2 [(validate.rules).string = {min_len: 1}]; // 合同模板名称
  string templateUrl = 3 [(validate.rules).string = {min_len: 1}]; // 合同模板地址
  int32 templateType = 4 [(validate.rules).int32 = {
    in: [
      1,
      2
    ]
  }]; // 合同模板类型
}

message StoreContractTemplateReply {
  string id = 1; // 主键ID
}

message UpdateContractTemplateStatusReq {
  string id = 1 [(validate.rules).string = {min_len: 1}]; // 主键ID
  int32 status = 2; // 状态: -1:删除
}

message UpdateContractTemplateStatusReply {
  bool isSucceed = 1; // 是否成功
}

message QueryContractTemplateListReq {
  string templateName = 1; // 合同模板名称
  int32 page = 2; // 页码
  int32 pageSize = 3; // 每页数量
}

message ContractTemplateItem {
  string id = 1; // 主键ID
  int32 templateType = 2; // 模版类型：1：单日营；2：多日营
  string templateName = 3; // 合同模板名称
  string templateUrl = 4; // 合同模板地址
  int32 status = 5; // 状态
  string createdAt = 6; // 创建时间
  string updatedAt = 7; // 更新时间
  string updatedBy = 8; // 操作人
  string updatedByName = 9; // 操作人名称
}

message QueryContractTemplateListReply {
  repeated ContractTemplateItem list = 1; // 合同模板列表
  int32 total = 2; // 总数
}

message RevokeSignFlowReq {
  string signFlowId = 1 [(validate.rules).string = {min_len: 1}]; // 合同签署流程ID
  string revokeReason = 2 [(validate.rules).string = {min_len: 1}]; // 撤销原因
}

message RevokeSignFlowReply {
  bool isSucceed = 1; // 是否成功
}
