syntax = "proto3";

package shadow.v1;

import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";
import "validate/validate.proto";

option go_package = "gitlab.yc345.tv/backend/yanxue/api/shadow/v1;v1";

//优惠券表
service Coupon {
  //优惠券表-创建一条数据
  rpc CreateCoupon(CreateCouponReq) returns (CreateCouponReply) {
    option (google.api.http) = {
      post: "/yanxue/api/shadow/v1/coupon/create"
      body: "*"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      parameters: {
        headers: {
          name: "Authorization"
          description: "TOKEN"
          type: STRING
          required: true
        }
      }
    };
  }
  //优惠券表-单条数据查询
  rpc GetCouponInfo(GetCouponInfoReq) returns (GetCouponInfoReply) {
    option (google.api.http) = {get: "/yanxue/api/shadow/v1/coupon/info"};
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      parameters: {
        headers: {
          name: "Authorization"
          description: "TOKEN"
          type: STRING
          required: true
        }
      }
    };
  }
  //优惠券表-列表数据查询
  rpc GetCouponList(GetCouponListReq) returns (GetCouponListReply) {
    option (google.api.http) = {
      post: "/yanxue/api/shadow/v1/coupon/list"
      body: "*"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      parameters: {
        headers: {
          name: "Authorization"
          description: "TOKEN"
          type: STRING
          required: true
        }
      }
    };
  }
  //优惠券表-更新优惠券状态
  rpc UpdateCouponStatus(UpdateCouponStatusReq) returns (UpdateCouponStatusReply) {
    option (google.api.http) = {
      post: "/yanxue/api/shadow/v1/coupon/updateStatus"
      body: "*"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      parameters: {
        headers: {
          name: "Authorization"
          description: "TOKEN"
          type: STRING
          required: true
        }
      }
    };
  }
  //优惠券表-查询优惠券数量信息
  rpc GetCouponQuantitySummary(GetCouponQuantitySummaryReq) returns (GetCouponQuantitySummaryReply) {
    option (google.api.http) = {get: "/yanxue/api/shadow/v1/coupon/quantitySummary"};
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      parameters: {
        headers: {
          name: "Authorization"
          description: "TOKEN"
          type: STRING
          required: true
        }
      }
    };
  }
}

message GetCouponQuantitySummaryReq {
  string id = 1; // 优惠券ID
}

message GetCouponQuantitySummaryReply {
  int32 remainingQuantity = 1; // 剩余数量
  int32 totalQuantity = 2; // 投放数量
  int32 receivedQuantity = 3; // 领取数量
  int32 usedQuantity = 4; // 使用数量
}

//请求-更新优惠券状态
message UpdateCouponStatusReq {
  string id = 1 [(validate.rules).string = {min_len: 1}]; // id
  string status = 2 [(validate.rules).string = {min_len: 1}]; // 状态：put_on:上架；put_off:下架；
}

//响应-更新优惠券状态
message UpdateCouponStatusReply {}

//优惠券表信息
message CouponInfo {
  string id = 1; // id
  string name = 2; // 优惠券名称
  int32 discountAmount = 3; // 优惠金额
  string pushType = 4; // 推送方式：public:公开；private:私密
  string couponType = 5; // 优惠券类型：common:通用；good:商品
  repeated string adaptGoodInfo = 6; // 适用商品信息
  int32 minAmount = 7; // 门槛金额：为0则表示无门槛
  string validStartTime = 8; // 使用开始时间
  string validEndTime = 9; // 使用结束时间
  string claimStartTime = 10; // 领取开始时间
  string claimEndTime = 11; // 领取结束时间
  int32 totalStock = 12; // 投放张数
  int32 limitPerUser = 13; // 每人限领张数
  string remark = 14; // 备注
  string shareQRCode = 15; // 分享二维码
  int32 couponValidDays = 16; // 优惠券领取后几天内有效
  string createdAt = 17; // 创建时间
  string updatedAt = 18; // 更新时间
  string status = 19; // 状态：put_on:上架；put_off:下架；
}

//请求-优惠券表-创建一条数据
message CreateCouponReq {
  string id = 1 [(validate.rules).string.uuid = true]; // 优惠券ID
  string name = 2 [(validate.rules).string = {min_len: 1}]; // 优惠券名称
  int32 discountAmount = 3; // 优惠金额
  string pushType = 4 [(validate.rules).string = {min_len: 1}]; // 推送方式：public:公开；private:私密
  string couponType = 5 [(validate.rules).string = {min_len: 1}]; // 优惠券类型：common:通用；good:商品
  repeated string adaptGoodInfo = 6; // 适用商品信息
  int32 minAmount = 7; // 门槛金额：为0则表示无门槛
  string validStartTime = 8; // 使用开始时间
  string validEndTime = 9; // 使用结束时间
  string claimStartTime = 10; // 领取开始时间
  string claimEndTime = 11; // 领取结束时间
  int32 totalStock = 12; // 投放张数
  int32 limitPerUser = 13; // 每人限领张数
  string remark = 14; // 备注
  string shareQRCode = 15; // 分享二维码
  int32 couponValidDays = 16; // 优惠券领取后几天内有效
}

//响应-优惠券表-创建一条数据
message CreateCouponReply {
  string id = 1; // id
}

//请求-优惠券表-单条数据查询
message GetCouponInfoReq {
  string id = 1; // id
}

//响应-优惠券表-单条数据查询
message GetCouponInfoReply {
  CouponInfo info = 1;
}

//请求-优惠券表-列表数据查询
message GetCouponListReq {
  string name = 1; // 优惠券名称
  string pushType = 2; // 推送方式：public:公开；private:私密
  string status = 3; // 状态：put_on:上架；put_off:下架；
  int32 page = 4; //页码
  int32 pageSize = 5; //页数
}

//响应-优惠券表-列表数据查询
message GetCouponListReply {
  int32 total = 1; //总数
  repeated CouponInfo list = 2; // 列表数据
}
