// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: shadow/v1/grab_ticket_task_config.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on UpdateGrabTicketTaskConfigStatusReq with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *UpdateGrabTicketTaskConfigStatusReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateGrabTicketTaskConfigStatusReq
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// UpdateGrabTicketTaskConfigStatusReqMultiError, or nil if none found.
func (m *UpdateGrabTicketTaskConfigStatusReq) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateGrabTicketTaskConfigStatusReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Status

	if len(errors) > 0 {
		return UpdateGrabTicketTaskConfigStatusReqMultiError(errors)
	}

	return nil
}

// UpdateGrabTicketTaskConfigStatusReqMultiError is an error wrapping multiple
// validation errors returned by
// UpdateGrabTicketTaskConfigStatusReq.ValidateAll() if the designated
// constraints aren't met.
type UpdateGrabTicketTaskConfigStatusReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateGrabTicketTaskConfigStatusReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateGrabTicketTaskConfigStatusReqMultiError) AllErrors() []error { return m }

// UpdateGrabTicketTaskConfigStatusReqValidationError is the validation error
// returned by UpdateGrabTicketTaskConfigStatusReq.Validate if the designated
// constraints aren't met.
type UpdateGrabTicketTaskConfigStatusReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateGrabTicketTaskConfigStatusReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateGrabTicketTaskConfigStatusReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateGrabTicketTaskConfigStatusReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateGrabTicketTaskConfigStatusReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateGrabTicketTaskConfigStatusReqValidationError) ErrorName() string {
	return "UpdateGrabTicketTaskConfigStatusReqValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateGrabTicketTaskConfigStatusReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateGrabTicketTaskConfigStatusReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateGrabTicketTaskConfigStatusReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateGrabTicketTaskConfigStatusReqValidationError{}

// Validate checks the field values on UpdateGrabTicketTaskConfigStatusReply
// with the rules defined in the proto definition for this message. If any
// rules are violated, the first error encountered is returned, or nil if
// there are no violations.
func (m *UpdateGrabTicketTaskConfigStatusReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateGrabTicketTaskConfigStatusReply
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// UpdateGrabTicketTaskConfigStatusReplyMultiError, or nil if none found.
func (m *UpdateGrabTicketTaskConfigStatusReply) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateGrabTicketTaskConfigStatusReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return UpdateGrabTicketTaskConfigStatusReplyMultiError(errors)
	}

	return nil
}

// UpdateGrabTicketTaskConfigStatusReplyMultiError is an error wrapping
// multiple validation errors returned by
// UpdateGrabTicketTaskConfigStatusReply.ValidateAll() if the designated
// constraints aren't met.
type UpdateGrabTicketTaskConfigStatusReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateGrabTicketTaskConfigStatusReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateGrabTicketTaskConfigStatusReplyMultiError) AllErrors() []error { return m }

// UpdateGrabTicketTaskConfigStatusReplyValidationError is the validation error
// returned by UpdateGrabTicketTaskConfigStatusReply.Validate if the
// designated constraints aren't met.
type UpdateGrabTicketTaskConfigStatusReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateGrabTicketTaskConfigStatusReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateGrabTicketTaskConfigStatusReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateGrabTicketTaskConfigStatusReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateGrabTicketTaskConfigStatusReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateGrabTicketTaskConfigStatusReplyValidationError) ErrorName() string {
	return "UpdateGrabTicketTaskConfigStatusReplyValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateGrabTicketTaskConfigStatusReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateGrabTicketTaskConfigStatusReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateGrabTicketTaskConfigStatusReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateGrabTicketTaskConfigStatusReplyValidationError{}

// Validate checks the field values on GrabTicketUserInfo with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GrabTicketUserInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GrabTicketUserInfo with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GrabTicketUserInfoMultiError, or nil if none found.
func (m *GrabTicketUserInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *GrabTicketUserInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	// no validation rules for IdCard

	// no validation rules for Phone

	if len(errors) > 0 {
		return GrabTicketUserInfoMultiError(errors)
	}

	return nil
}

// GrabTicketUserInfoMultiError is an error wrapping multiple validation errors
// returned by GrabTicketUserInfo.ValidateAll() if the designated constraints
// aren't met.
type GrabTicketUserInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GrabTicketUserInfoMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GrabTicketUserInfoMultiError) AllErrors() []error { return m }

// GrabTicketUserInfoValidationError is the validation error returned by
// GrabTicketUserInfo.Validate if the designated constraints aren't met.
type GrabTicketUserInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GrabTicketUserInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GrabTicketUserInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GrabTicketUserInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GrabTicketUserInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GrabTicketUserInfoValidationError) ErrorName() string {
	return "GrabTicketUserInfoValidationError"
}

// Error satisfies the builtin error interface
func (e GrabTicketUserInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGrabTicketUserInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GrabTicketUserInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GrabTicketUserInfoValidationError{}

// Validate checks the field values on GrabTicketTaskConfigInfo with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GrabTicketTaskConfigInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GrabTicketTaskConfigInfo with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GrabTicketTaskConfigInfoMultiError, or nil if none found.
func (m *GrabTicketTaskConfigInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *GrabTicketTaskConfigInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for SiteConfigId

	// no validation rules for Session

	// no validation rules for Venue

	// no validation rules for TimeSlot

	// no validation rules for Priority

	// no validation rules for MaxRetries

	// no validation rules for RetryCount

	for idx, item := range m.GetUserInfo() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GrabTicketTaskConfigInfoValidationError{
						field:  fmt.Sprintf("UserInfo[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GrabTicketTaskConfigInfoValidationError{
						field:  fmt.Sprintf("UserInfo[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GrabTicketTaskConfigInfoValidationError{
					field:  fmt.Sprintf("UserInfo[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for TicketType

	// no validation rules for VisitDate

	// no validation rules for PreExecuteTimeGap

	// no validation rules for EnableRetry

	// no validation rules for RetryTimeGap

	// no validation rules for Status

	// no validation rules for TaskName

	// no validation rules for CreatedAt

	// no validation rules for UpdatedAt

	if len(errors) > 0 {
		return GrabTicketTaskConfigInfoMultiError(errors)
	}

	return nil
}

// GrabTicketTaskConfigInfoMultiError is an error wrapping multiple validation
// errors returned by GrabTicketTaskConfigInfo.ValidateAll() if the designated
// constraints aren't met.
type GrabTicketTaskConfigInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GrabTicketTaskConfigInfoMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GrabTicketTaskConfigInfoMultiError) AllErrors() []error { return m }

// GrabTicketTaskConfigInfoValidationError is the validation error returned by
// GrabTicketTaskConfigInfo.Validate if the designated constraints aren't met.
type GrabTicketTaskConfigInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GrabTicketTaskConfigInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GrabTicketTaskConfigInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GrabTicketTaskConfigInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GrabTicketTaskConfigInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GrabTicketTaskConfigInfoValidationError) ErrorName() string {
	return "GrabTicketTaskConfigInfoValidationError"
}

// Error satisfies the builtin error interface
func (e GrabTicketTaskConfigInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGrabTicketTaskConfigInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GrabTicketTaskConfigInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GrabTicketTaskConfigInfoValidationError{}

// Validate checks the field values on CreateGrabTicketTaskConfigReq with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateGrabTicketTaskConfigReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateGrabTicketTaskConfigReq with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// CreateGrabTicketTaskConfigReqMultiError, or nil if none found.
func (m *CreateGrabTicketTaskConfigReq) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateGrabTicketTaskConfigReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for SiteConfigId

	// no validation rules for Session

	// no validation rules for Venue

	// no validation rules for TimeSlot

	// no validation rules for Priority

	// no validation rules for MaxRetries

	// no validation rules for RetryCount

	for idx, item := range m.GetUserInfo() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, CreateGrabTicketTaskConfigReqValidationError{
						field:  fmt.Sprintf("UserInfo[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, CreateGrabTicketTaskConfigReqValidationError{
						field:  fmt.Sprintf("UserInfo[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return CreateGrabTicketTaskConfigReqValidationError{
					field:  fmt.Sprintf("UserInfo[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for TicketType

	// no validation rules for VisitDate

	// no validation rules for PreExecuteTimeGap

	// no validation rules for EnableRetry

	// no validation rules for RetryTimeGap

	// no validation rules for Status

	// no validation rules for TaskName

	if len(errors) > 0 {
		return CreateGrabTicketTaskConfigReqMultiError(errors)
	}

	return nil
}

// CreateGrabTicketTaskConfigReqMultiError is an error wrapping multiple
// validation errors returned by CreateGrabTicketTaskConfigReq.ValidateAll()
// if the designated constraints aren't met.
type CreateGrabTicketTaskConfigReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateGrabTicketTaskConfigReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateGrabTicketTaskConfigReqMultiError) AllErrors() []error { return m }

// CreateGrabTicketTaskConfigReqValidationError is the validation error
// returned by CreateGrabTicketTaskConfigReq.Validate if the designated
// constraints aren't met.
type CreateGrabTicketTaskConfigReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateGrabTicketTaskConfigReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateGrabTicketTaskConfigReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateGrabTicketTaskConfigReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateGrabTicketTaskConfigReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateGrabTicketTaskConfigReqValidationError) ErrorName() string {
	return "CreateGrabTicketTaskConfigReqValidationError"
}

// Error satisfies the builtin error interface
func (e CreateGrabTicketTaskConfigReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateGrabTicketTaskConfigReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateGrabTicketTaskConfigReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateGrabTicketTaskConfigReqValidationError{}

// Validate checks the field values on CreateGrabTicketTaskConfigReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateGrabTicketTaskConfigReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateGrabTicketTaskConfigReply with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// CreateGrabTicketTaskConfigReplyMultiError, or nil if none found.
func (m *CreateGrabTicketTaskConfigReply) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateGrabTicketTaskConfigReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return CreateGrabTicketTaskConfigReplyMultiError(errors)
	}

	return nil
}

// CreateGrabTicketTaskConfigReplyMultiError is an error wrapping multiple
// validation errors returned by CreateGrabTicketTaskConfigReply.ValidateAll()
// if the designated constraints aren't met.
type CreateGrabTicketTaskConfigReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateGrabTicketTaskConfigReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateGrabTicketTaskConfigReplyMultiError) AllErrors() []error { return m }

// CreateGrabTicketTaskConfigReplyValidationError is the validation error
// returned by CreateGrabTicketTaskConfigReply.Validate if the designated
// constraints aren't met.
type CreateGrabTicketTaskConfigReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateGrabTicketTaskConfigReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateGrabTicketTaskConfigReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateGrabTicketTaskConfigReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateGrabTicketTaskConfigReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateGrabTicketTaskConfigReplyValidationError) ErrorName() string {
	return "CreateGrabTicketTaskConfigReplyValidationError"
}

// Error satisfies the builtin error interface
func (e CreateGrabTicketTaskConfigReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateGrabTicketTaskConfigReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateGrabTicketTaskConfigReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateGrabTicketTaskConfigReplyValidationError{}

// Validate checks the field values on UpdateGrabTicketTaskConfigReq with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateGrabTicketTaskConfigReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateGrabTicketTaskConfigReq with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// UpdateGrabTicketTaskConfigReqMultiError, or nil if none found.
func (m *UpdateGrabTicketTaskConfigReq) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateGrabTicketTaskConfigReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for SiteConfigId

	// no validation rules for Session

	// no validation rules for Venue

	// no validation rules for TimeSlot

	// no validation rules for Priority

	// no validation rules for MaxRetries

	// no validation rules for RetryCount

	for idx, item := range m.GetUserInfo() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, UpdateGrabTicketTaskConfigReqValidationError{
						field:  fmt.Sprintf("UserInfo[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, UpdateGrabTicketTaskConfigReqValidationError{
						field:  fmt.Sprintf("UserInfo[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return UpdateGrabTicketTaskConfigReqValidationError{
					field:  fmt.Sprintf("UserInfo[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for TicketType

	// no validation rules for VisitDate

	// no validation rules for PreExecuteTimeGap

	// no validation rules for EnableRetry

	// no validation rules for RetryTimeGap

	// no validation rules for Status

	// no validation rules for TaskName

	if len(errors) > 0 {
		return UpdateGrabTicketTaskConfigReqMultiError(errors)
	}

	return nil
}

// UpdateGrabTicketTaskConfigReqMultiError is an error wrapping multiple
// validation errors returned by UpdateGrabTicketTaskConfigReq.ValidateAll()
// if the designated constraints aren't met.
type UpdateGrabTicketTaskConfigReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateGrabTicketTaskConfigReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateGrabTicketTaskConfigReqMultiError) AllErrors() []error { return m }

// UpdateGrabTicketTaskConfigReqValidationError is the validation error
// returned by UpdateGrabTicketTaskConfigReq.Validate if the designated
// constraints aren't met.
type UpdateGrabTicketTaskConfigReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateGrabTicketTaskConfigReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateGrabTicketTaskConfigReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateGrabTicketTaskConfigReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateGrabTicketTaskConfigReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateGrabTicketTaskConfigReqValidationError) ErrorName() string {
	return "UpdateGrabTicketTaskConfigReqValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateGrabTicketTaskConfigReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateGrabTicketTaskConfigReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateGrabTicketTaskConfigReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateGrabTicketTaskConfigReqValidationError{}

// Validate checks the field values on UpdateGrabTicketTaskConfigReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateGrabTicketTaskConfigReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateGrabTicketTaskConfigReply with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// UpdateGrabTicketTaskConfigReplyMultiError, or nil if none found.
func (m *UpdateGrabTicketTaskConfigReply) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateGrabTicketTaskConfigReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return UpdateGrabTicketTaskConfigReplyMultiError(errors)
	}

	return nil
}

// UpdateGrabTicketTaskConfigReplyMultiError is an error wrapping multiple
// validation errors returned by UpdateGrabTicketTaskConfigReply.ValidateAll()
// if the designated constraints aren't met.
type UpdateGrabTicketTaskConfigReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateGrabTicketTaskConfigReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateGrabTicketTaskConfigReplyMultiError) AllErrors() []error { return m }

// UpdateGrabTicketTaskConfigReplyValidationError is the validation error
// returned by UpdateGrabTicketTaskConfigReply.Validate if the designated
// constraints aren't met.
type UpdateGrabTicketTaskConfigReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateGrabTicketTaskConfigReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateGrabTicketTaskConfigReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateGrabTicketTaskConfigReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateGrabTicketTaskConfigReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateGrabTicketTaskConfigReplyValidationError) ErrorName() string {
	return "UpdateGrabTicketTaskConfigReplyValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateGrabTicketTaskConfigReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateGrabTicketTaskConfigReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateGrabTicketTaskConfigReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateGrabTicketTaskConfigReplyValidationError{}

// Validate checks the field values on DeleteGrabTicketTaskConfigReq with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteGrabTicketTaskConfigReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteGrabTicketTaskConfigReq with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// DeleteGrabTicketTaskConfigReqMultiError, or nil if none found.
func (m *DeleteGrabTicketTaskConfigReq) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteGrabTicketTaskConfigReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return DeleteGrabTicketTaskConfigReqMultiError(errors)
	}

	return nil
}

// DeleteGrabTicketTaskConfigReqMultiError is an error wrapping multiple
// validation errors returned by DeleteGrabTicketTaskConfigReq.ValidateAll()
// if the designated constraints aren't met.
type DeleteGrabTicketTaskConfigReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteGrabTicketTaskConfigReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteGrabTicketTaskConfigReqMultiError) AllErrors() []error { return m }

// DeleteGrabTicketTaskConfigReqValidationError is the validation error
// returned by DeleteGrabTicketTaskConfigReq.Validate if the designated
// constraints aren't met.
type DeleteGrabTicketTaskConfigReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteGrabTicketTaskConfigReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteGrabTicketTaskConfigReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteGrabTicketTaskConfigReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteGrabTicketTaskConfigReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteGrabTicketTaskConfigReqValidationError) ErrorName() string {
	return "DeleteGrabTicketTaskConfigReqValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteGrabTicketTaskConfigReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteGrabTicketTaskConfigReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteGrabTicketTaskConfigReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteGrabTicketTaskConfigReqValidationError{}

// Validate checks the field values on DeleteGrabTicketTaskConfigReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteGrabTicketTaskConfigReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteGrabTicketTaskConfigReply with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// DeleteGrabTicketTaskConfigReplyMultiError, or nil if none found.
func (m *DeleteGrabTicketTaskConfigReply) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteGrabTicketTaskConfigReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return DeleteGrabTicketTaskConfigReplyMultiError(errors)
	}

	return nil
}

// DeleteGrabTicketTaskConfigReplyMultiError is an error wrapping multiple
// validation errors returned by DeleteGrabTicketTaskConfigReply.ValidateAll()
// if the designated constraints aren't met.
type DeleteGrabTicketTaskConfigReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteGrabTicketTaskConfigReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteGrabTicketTaskConfigReplyMultiError) AllErrors() []error { return m }

// DeleteGrabTicketTaskConfigReplyValidationError is the validation error
// returned by DeleteGrabTicketTaskConfigReply.Validate if the designated
// constraints aren't met.
type DeleteGrabTicketTaskConfigReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteGrabTicketTaskConfigReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteGrabTicketTaskConfigReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteGrabTicketTaskConfigReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteGrabTicketTaskConfigReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteGrabTicketTaskConfigReplyValidationError) ErrorName() string {
	return "DeleteGrabTicketTaskConfigReplyValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteGrabTicketTaskConfigReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteGrabTicketTaskConfigReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteGrabTicketTaskConfigReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteGrabTicketTaskConfigReplyValidationError{}

// Validate checks the field values on GetGrabTicketTaskConfigInfoReq with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetGrabTicketTaskConfigInfoReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetGrabTicketTaskConfigInfoReq with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// GetGrabTicketTaskConfigInfoReqMultiError, or nil if none found.
func (m *GetGrabTicketTaskConfigInfoReq) ValidateAll() error {
	return m.validate(true)
}

func (m *GetGrabTicketTaskConfigInfoReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return GetGrabTicketTaskConfigInfoReqMultiError(errors)
	}

	return nil
}

// GetGrabTicketTaskConfigInfoReqMultiError is an error wrapping multiple
// validation errors returned by GetGrabTicketTaskConfigInfoReq.ValidateAll()
// if the designated constraints aren't met.
type GetGrabTicketTaskConfigInfoReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetGrabTicketTaskConfigInfoReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetGrabTicketTaskConfigInfoReqMultiError) AllErrors() []error { return m }

// GetGrabTicketTaskConfigInfoReqValidationError is the validation error
// returned by GetGrabTicketTaskConfigInfoReq.Validate if the designated
// constraints aren't met.
type GetGrabTicketTaskConfigInfoReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetGrabTicketTaskConfigInfoReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetGrabTicketTaskConfigInfoReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetGrabTicketTaskConfigInfoReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetGrabTicketTaskConfigInfoReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetGrabTicketTaskConfigInfoReqValidationError) ErrorName() string {
	return "GetGrabTicketTaskConfigInfoReqValidationError"
}

// Error satisfies the builtin error interface
func (e GetGrabTicketTaskConfigInfoReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetGrabTicketTaskConfigInfoReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetGrabTicketTaskConfigInfoReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetGrabTicketTaskConfigInfoReqValidationError{}

// Validate checks the field values on GetGrabTicketTaskConfigInfoReply with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *GetGrabTicketTaskConfigInfoReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetGrabTicketTaskConfigInfoReply with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// GetGrabTicketTaskConfigInfoReplyMultiError, or nil if none found.
func (m *GetGrabTicketTaskConfigInfoReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetGrabTicketTaskConfigInfoReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetInfo()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetGrabTicketTaskConfigInfoReplyValidationError{
					field:  "Info",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetGrabTicketTaskConfigInfoReplyValidationError{
					field:  "Info",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetInfo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetGrabTicketTaskConfigInfoReplyValidationError{
				field:  "Info",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetGrabTicketTaskConfigInfoReplyMultiError(errors)
	}

	return nil
}

// GetGrabTicketTaskConfigInfoReplyMultiError is an error wrapping multiple
// validation errors returned by
// GetGrabTicketTaskConfigInfoReply.ValidateAll() if the designated
// constraints aren't met.
type GetGrabTicketTaskConfigInfoReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetGrabTicketTaskConfigInfoReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetGrabTicketTaskConfigInfoReplyMultiError) AllErrors() []error { return m }

// GetGrabTicketTaskConfigInfoReplyValidationError is the validation error
// returned by GetGrabTicketTaskConfigInfoReply.Validate if the designated
// constraints aren't met.
type GetGrabTicketTaskConfigInfoReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetGrabTicketTaskConfigInfoReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetGrabTicketTaskConfigInfoReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetGrabTicketTaskConfigInfoReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetGrabTicketTaskConfigInfoReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetGrabTicketTaskConfigInfoReplyValidationError) ErrorName() string {
	return "GetGrabTicketTaskConfigInfoReplyValidationError"
}

// Error satisfies the builtin error interface
func (e GetGrabTicketTaskConfigInfoReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetGrabTicketTaskConfigInfoReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetGrabTicketTaskConfigInfoReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetGrabTicketTaskConfigInfoReplyValidationError{}

// Validate checks the field values on GetGrabTicketTaskConfigListReq with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetGrabTicketTaskConfigListReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetGrabTicketTaskConfigListReq with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// GetGrabTicketTaskConfigListReqMultiError, or nil if none found.
func (m *GetGrabTicketTaskConfigListReq) ValidateAll() error {
	return m.validate(true)
}

func (m *GetGrabTicketTaskConfigListReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Page

	// no validation rules for PageSize

	// no validation rules for SiteConfigId

	if len(errors) > 0 {
		return GetGrabTicketTaskConfigListReqMultiError(errors)
	}

	return nil
}

// GetGrabTicketTaskConfigListReqMultiError is an error wrapping multiple
// validation errors returned by GetGrabTicketTaskConfigListReq.ValidateAll()
// if the designated constraints aren't met.
type GetGrabTicketTaskConfigListReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetGrabTicketTaskConfigListReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetGrabTicketTaskConfigListReqMultiError) AllErrors() []error { return m }

// GetGrabTicketTaskConfigListReqValidationError is the validation error
// returned by GetGrabTicketTaskConfigListReq.Validate if the designated
// constraints aren't met.
type GetGrabTicketTaskConfigListReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetGrabTicketTaskConfigListReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetGrabTicketTaskConfigListReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetGrabTicketTaskConfigListReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetGrabTicketTaskConfigListReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetGrabTicketTaskConfigListReqValidationError) ErrorName() string {
	return "GetGrabTicketTaskConfigListReqValidationError"
}

// Error satisfies the builtin error interface
func (e GetGrabTicketTaskConfigListReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetGrabTicketTaskConfigListReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetGrabTicketTaskConfigListReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetGrabTicketTaskConfigListReqValidationError{}

// Validate checks the field values on GetGrabTicketTaskConfigListReply with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *GetGrabTicketTaskConfigListReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetGrabTicketTaskConfigListReply with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// GetGrabTicketTaskConfigListReplyMultiError, or nil if none found.
func (m *GetGrabTicketTaskConfigListReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetGrabTicketTaskConfigListReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Total

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetGrabTicketTaskConfigListReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetGrabTicketTaskConfigListReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetGrabTicketTaskConfigListReplyValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetGrabTicketTaskConfigListReplyMultiError(errors)
	}

	return nil
}

// GetGrabTicketTaskConfigListReplyMultiError is an error wrapping multiple
// validation errors returned by
// GetGrabTicketTaskConfigListReply.ValidateAll() if the designated
// constraints aren't met.
type GetGrabTicketTaskConfigListReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetGrabTicketTaskConfigListReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetGrabTicketTaskConfigListReplyMultiError) AllErrors() []error { return m }

// GetGrabTicketTaskConfigListReplyValidationError is the validation error
// returned by GetGrabTicketTaskConfigListReply.Validate if the designated
// constraints aren't met.
type GetGrabTicketTaskConfigListReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetGrabTicketTaskConfigListReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetGrabTicketTaskConfigListReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetGrabTicketTaskConfigListReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetGrabTicketTaskConfigListReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetGrabTicketTaskConfigListReplyValidationError) ErrorName() string {
	return "GetGrabTicketTaskConfigListReplyValidationError"
}

// Error satisfies the builtin error interface
func (e GetGrabTicketTaskConfigListReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetGrabTicketTaskConfigListReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetGrabTicketTaskConfigListReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetGrabTicketTaskConfigListReplyValidationError{}
