// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: shadow/v1/sub_order.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ExportSubOrderListReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ExportSubOrderListReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ExportSubOrderListReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ExportSubOrderListReqMultiError, or nil if none found.
func (m *ExportSubOrderListReq) ValidateAll() error {
	return m.validate(true)
}

func (m *ExportSubOrderListReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for GoodName

	// no validation rules for ChannelId

	// no validation rules for PaymentTimeStart

	// no validation rules for PaymentTimeEnd

	// no validation rules for OrderStatus

	// no validation rules for OrderNumber

	// no validation rules for Phone

	// no validation rules for ServiceStatus

	// no validation rules for GoodType

	// no validation rules for RefundTimeStart

	// no validation rules for RefundTimeEnd

	// no validation rules for ParentOrderId

	// no validation rules for CampTimeStart

	// no validation rules for CampTimeEnd

	if len(errors) > 0 {
		return ExportSubOrderListReqMultiError(errors)
	}

	return nil
}

// ExportSubOrderListReqMultiError is an error wrapping multiple validation
// errors returned by ExportSubOrderListReq.ValidateAll() if the designated
// constraints aren't met.
type ExportSubOrderListReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ExportSubOrderListReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ExportSubOrderListReqMultiError) AllErrors() []error { return m }

// ExportSubOrderListReqValidationError is the validation error returned by
// ExportSubOrderListReq.Validate if the designated constraints aren't met.
type ExportSubOrderListReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ExportSubOrderListReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ExportSubOrderListReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ExportSubOrderListReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ExportSubOrderListReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ExportSubOrderListReqValidationError) ErrorName() string {
	return "ExportSubOrderListReqValidationError"
}

// Error satisfies the builtin error interface
func (e ExportSubOrderListReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sExportSubOrderListReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ExportSubOrderListReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ExportSubOrderListReqValidationError{}

// Validate checks the field values on ExportSubOrderListReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ExportSubOrderListReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ExportSubOrderListReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ExportSubOrderListReplyMultiError, or nil if none found.
func (m *ExportSubOrderListReply) ValidateAll() error {
	return m.validate(true)
}

func (m *ExportSubOrderListReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for DownloadUrl

	if len(errors) > 0 {
		return ExportSubOrderListReplyMultiError(errors)
	}

	return nil
}

// ExportSubOrderListReplyMultiError is an error wrapping multiple validation
// errors returned by ExportSubOrderListReply.ValidateAll() if the designated
// constraints aren't met.
type ExportSubOrderListReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ExportSubOrderListReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ExportSubOrderListReplyMultiError) AllErrors() []error { return m }

// ExportSubOrderListReplyValidationError is the validation error returned by
// ExportSubOrderListReply.Validate if the designated constraints aren't met.
type ExportSubOrderListReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ExportSubOrderListReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ExportSubOrderListReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ExportSubOrderListReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ExportSubOrderListReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ExportSubOrderListReplyValidationError) ErrorName() string {
	return "ExportSubOrderListReplyValidationError"
}

// Error satisfies the builtin error interface
func (e ExportSubOrderListReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sExportSubOrderListReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ExportSubOrderListReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ExportSubOrderListReplyValidationError{}

// Validate checks the field values on SubOrderInfo with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SubOrderInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SubOrderInfo with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SubOrderInfoMultiError, or
// nil if none found.
func (m *SubOrderInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *SubOrderInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for ChannelId

	// no validation rules for GoodId

	// no validation rules for ChannelGoodId

	// no validation rules for OrderNumber

	// no validation rules for OrderPrice

	// no validation rules for PaymentTime

	// no validation rules for Phone

	// no validation rules for Status

	// no validation rules for CreatedAt

	// no validation rules for UpdatedAt

	// no validation rules for UpdatedBy

	// no validation rules for GoodName

	// no validation rules for ChannelName

	// no validation rules for DiscountAmount

	// no validation rules for UpdatedByName

	// no validation rules for PayId

	// no validation rules for RefundId

	// no validation rules for RefundReason

	// no validation rules for RefundAmount

	// no validation rules for ParentRemark

	// no validation rules for RefundTime

	// no validation rules for GoodType

	// no validation rules for PlatformFee

	// no validation rules for ServiceStatus

	// no validation rules for TalentUid

	// no validation rules for TalentName

	// no validation rules for TalentCommission

	// no validation rules for ReceiptAmount

	// no validation rules for ParentOrderId

	// no validation rules for CampTime

	// no validation rules for PlatformDiscountAmount

	// no validation rules for PaymentDiscountAmount

	// no validation rules for ShopDiscountAmount

	// no validation rules for ActualInsured

	if len(errors) > 0 {
		return SubOrderInfoMultiError(errors)
	}

	return nil
}

// SubOrderInfoMultiError is an error wrapping multiple validation errors
// returned by SubOrderInfo.ValidateAll() if the designated constraints aren't met.
type SubOrderInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SubOrderInfoMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SubOrderInfoMultiError) AllErrors() []error { return m }

// SubOrderInfoValidationError is the validation error returned by
// SubOrderInfo.Validate if the designated constraints aren't met.
type SubOrderInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SubOrderInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SubOrderInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SubOrderInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SubOrderInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SubOrderInfoValidationError) ErrorName() string { return "SubOrderInfoValidationError" }

// Error satisfies the builtin error interface
func (e SubOrderInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSubOrderInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SubOrderInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SubOrderInfoValidationError{}

// Validate checks the field values on GetSubOrderListReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetSubOrderListReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetSubOrderListReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetSubOrderListReqMultiError, or nil if none found.
func (m *GetSubOrderListReq) ValidateAll() error {
	return m.validate(true)
}

func (m *GetSubOrderListReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Page

	// no validation rules for PageSize

	// no validation rules for GoodName

	// no validation rules for ChannelId

	// no validation rules for PaymentTimeStart

	// no validation rules for PaymentTimeEnd

	// no validation rules for OrderStatus

	// no validation rules for OrderNumber

	// no validation rules for Phone

	// no validation rules for ServiceStatus

	// no validation rules for GoodType

	// no validation rules for RefundTimeStart

	// no validation rules for RefundTimeEnd

	// no validation rules for ParentOrderId

	// no validation rules for CampTimeStart

	// no validation rules for CampTimeEnd

	if len(errors) > 0 {
		return GetSubOrderListReqMultiError(errors)
	}

	return nil
}

// GetSubOrderListReqMultiError is an error wrapping multiple validation errors
// returned by GetSubOrderListReq.ValidateAll() if the designated constraints
// aren't met.
type GetSubOrderListReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetSubOrderListReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetSubOrderListReqMultiError) AllErrors() []error { return m }

// GetSubOrderListReqValidationError is the validation error returned by
// GetSubOrderListReq.Validate if the designated constraints aren't met.
type GetSubOrderListReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetSubOrderListReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetSubOrderListReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetSubOrderListReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetSubOrderListReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetSubOrderListReqValidationError) ErrorName() string {
	return "GetSubOrderListReqValidationError"
}

// Error satisfies the builtin error interface
func (e GetSubOrderListReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetSubOrderListReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetSubOrderListReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetSubOrderListReqValidationError{}

// Validate checks the field values on GetSubOrderListReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetSubOrderListReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetSubOrderListReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetSubOrderListReplyMultiError, or nil if none found.
func (m *GetSubOrderListReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetSubOrderListReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Total

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetSubOrderListReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetSubOrderListReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetSubOrderListReplyValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetSubOrderListReplyMultiError(errors)
	}

	return nil
}

// GetSubOrderListReplyMultiError is an error wrapping multiple validation
// errors returned by GetSubOrderListReply.ValidateAll() if the designated
// constraints aren't met.
type GetSubOrderListReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetSubOrderListReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetSubOrderListReplyMultiError) AllErrors() []error { return m }

// GetSubOrderListReplyValidationError is the validation error returned by
// GetSubOrderListReply.Validate if the designated constraints aren't met.
type GetSubOrderListReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetSubOrderListReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetSubOrderListReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetSubOrderListReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetSubOrderListReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetSubOrderListReplyValidationError) ErrorName() string {
	return "GetSubOrderListReplyValidationError"
}

// Error satisfies the builtin error interface
func (e GetSubOrderListReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetSubOrderListReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetSubOrderListReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetSubOrderListReplyValidationError{}
