syntax = "proto3";

package shadow.v1;

import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";
import "validate/validate.proto";

option go_package = "gitlab.yc345.tv/backend/yanxue/api/shadow/v1;v1";

// 变量的命名一律使用小驼峰命名法，例如：firstName、lastName等。
// 后缀定义:请求req,响应reply

// 功能权限模块
service SysPermission {
  //功能权限-列表
  rpc SysPermissionList(SysPermissionListReq) returns (SysPermissionListResp) {
    option (google.api.http) = {get: "/yanxue/shadow/v1/sysPermission/list"};
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      parameters: {
        headers: {
          name: "Authorization"
          description: "TOKEN"
          type: STRING
          required: true
        }
      }
    };
  }
  //功能权限-保存
  rpc SysPermissionStore(SysPermissionStoreReq) returns (SysPermissionStoreResp) {
    option (google.api.http) = {
      post: "/yanxue/shadow/v1/sysPermission/store"
      body: "*"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      parameters: {
        headers: {
          name: "Authorization"
          description: "TOKEN"
          type: STRING
          required: true
        }
      }
    };
  }
  //功能权限-删除
  rpc SysPermissionDel(SysPermissionDelReq) returns (SysPermissionDelResp) {
    option (google.api.http) = {
      post: "/yanxue/shadow/v1/sysPermission/del"
      body: "*"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      parameters: {
        headers: {
          name: "Authorization"
          description: "TOKEN"
          type: STRING
          required: true
        }
      }
    };
  }
  //功能权限-修改权限状态
  rpc SysPermissionStatus(SysPermissionStatusReq) returns (SysPermissionStatusResp) {
    option (google.api.http) = {
      post: "/yanxue/shadow/v1/sysPermission/status"
      body: "*"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      parameters: {
        headers: {
          name: "Authorization"
          description: "TOKEN"
          type: STRING
          required: true
        }
      }
    };
  }
}

//功能权限-信息
message SysPermissionInfo {
  string id = 1; // Id
  string pid = 2; // 上级菜单
  string type = 3; // 类型:menu_dir=菜单目录,menu=菜单项,button=页面按钮
  string title = 4; // 标题
  string name = 5; // 规则名称
  string path = 6; // 路由路径
  string icon = 7; // 图标
  string menuType = 8; // 菜单类型:tab=选项卡,link=链接,iframe=Iframe
  string url = 9; // Url
  string component = 10; // 组件路径
  string extend = 11; // 扩展属性:none=无,add_rules_only=只添加为路由,add_menu_only=只添加为菜单
  string remark = 12; // 备注
  int32 status = 13; // 状态:-1=禁用,1=启用
  string createdAt = 14; // 创建时间
  string updatedAt = 15; // 更新时间
  repeated SysPermissionInfo children = 16; //子集
}

//功能权限-列表-请求
message SysPermissionListReq {}

//功能权限-列表-响应
message SysPermissionListResp {
  repeated SysPermissionInfo list = 1; //列表
}

//功能权限-保存-请求
message SysPermissionStoreReq {
  option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_schema) = {
    json_schema: {
      required: [
        "id",
        "pid",
        "type",
        "title",
        "name",
        "path"
      ]
    }
  };
  string id = 1 [(validate.rules).string = {
    uuid: true
    ignore_empty: true
  }]; // Id
  string pid = 2 [(validate.rules).string = {
    uuid: true
    ignore_empty: true
  }]; // 上级菜单
  string type = 3 [(validate.rules).string = {
    in: [
      "menu_dir",
      "menu",
      "button"
    ]
  }]; // 类型:menu_dir=菜单目录,menu=菜单项,button=页面按钮
  string title = 4 [(validate.rules).string = {
    ignore_empty: true
    min_len: 1
    max_len: 50
  }]; // 标题
  string name = 5 [(validate.rules).string = {
    min_len: 1
    max_len: 50
  }]; // 规则名称
  string path = 6 [(validate.rules).string = {
    min_len: 1
    max_len: 100
  }]; // 路由路径
  string icon = 7 [(validate.rules).string = {
    ignore_empty: true
    min_len: 1
    max_len: 50
  }]; // 图标
  string menuType = 8 [(validate.rules).string = {
    ignore_empty: true
    min_len: 1
    max_len: 32
  }]; // 菜单类型:tab=选项卡,link=链接,iframe=Iframe
  string url = 9 [(validate.rules).string = {
    ignore_empty: true
    min_len: 1
    max_len: 255
  }]; // Url
  string component = 10 [(validate.rules).string = {
    ignore_empty: true
    min_len: 1
    max_len: 100
  }]; // 组件路径
  string extend = 11 [(validate.rules).string = {
    ignore_empty: true
    min_len: 1
    max_len: 255
  }]; // 扩展属性:none=无,add_rules_only=只添加为路由,add_menu_only=只添加为菜单
  string remark = 12 [(validate.rules).string = {
    ignore_empty: true
    min_len: 1
    max_len: 255
  }]; // 备注
  int32 status = 13 [(validate.rules).int32 = {
    in: [
      -1,
      1
    ]
  }]; // 状态:-1=禁用,1=启用
}

//功能权限-保存-响应
message SysPermissionStoreResp {
  string id = 1; // Id
}

//功能权限-删除-请求
message SysPermissionDelReq {
  option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_schema) = {
    json_schema: {
      required: ["id"]
    }
  };
  string id = 1 [(validate.rules).string = {uuid: true}]; //Id
}

//功能权限-删除-响应
message SysPermissionDelResp {}

//功能权限-修改权限状态-请求
message SysPermissionStatusReq {
  option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_schema) = {
    json_schema: {
      required: [
        "id",
        "status"
      ]
    }
  };
  string id = 1 [(validate.rules).string.uuid = true]; // Id
  int32 status = 2 [(validate.rules).int32 = {
    in: [
      -1,
      1
    ]
  }]; // 状态:-1=禁用,1=启用
}

//功能权限-修改权限状态-响应
message SysPermissionStatusResp {}
