// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: shadow/v1/sys_dept.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// define the regex for a UUID once up-front
var _sys_dept_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on SysDeptInfo with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SysDeptInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SysDeptInfo with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SysDeptInfoMultiError, or
// nil if none found.
func (m *SysDeptInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *SysDeptInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Pid

	// no validation rules for Type

	// no validation rules for Name

	// no validation rules for Remark

	// no validation rules for Status

	// no validation rules for CreatedAt

	// no validation rules for UpdatedAt

	for idx, item := range m.GetChildren() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, SysDeptInfoValidationError{
						field:  fmt.Sprintf("Children[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, SysDeptInfoValidationError{
						field:  fmt.Sprintf("Children[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return SysDeptInfoValidationError{
					field:  fmt.Sprintf("Children[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for IsSelect

	if len(errors) > 0 {
		return SysDeptInfoMultiError(errors)
	}

	return nil
}

// SysDeptInfoMultiError is an error wrapping multiple validation errors
// returned by SysDeptInfo.ValidateAll() if the designated constraints aren't met.
type SysDeptInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SysDeptInfoMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SysDeptInfoMultiError) AllErrors() []error { return m }

// SysDeptInfoValidationError is the validation error returned by
// SysDeptInfo.Validate if the designated constraints aren't met.
type SysDeptInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SysDeptInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SysDeptInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SysDeptInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SysDeptInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SysDeptInfoValidationError) ErrorName() string { return "SysDeptInfoValidationError" }

// Error satisfies the builtin error interface
func (e SysDeptInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSysDeptInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SysDeptInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SysDeptInfoValidationError{}

// Validate checks the field values on SysDeptListReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SysDeptListReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SysDeptListReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SysDeptListReqMultiError,
// or nil if none found.
func (m *SysDeptListReq) ValidateAll() error {
	return m.validate(true)
}

func (m *SysDeptListReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return SysDeptListReqMultiError(errors)
	}

	return nil
}

// SysDeptListReqMultiError is an error wrapping multiple validation errors
// returned by SysDeptListReq.ValidateAll() if the designated constraints
// aren't met.
type SysDeptListReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SysDeptListReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SysDeptListReqMultiError) AllErrors() []error { return m }

// SysDeptListReqValidationError is the validation error returned by
// SysDeptListReq.Validate if the designated constraints aren't met.
type SysDeptListReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SysDeptListReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SysDeptListReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SysDeptListReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SysDeptListReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SysDeptListReqValidationError) ErrorName() string { return "SysDeptListReqValidationError" }

// Error satisfies the builtin error interface
func (e SysDeptListReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSysDeptListReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SysDeptListReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SysDeptListReqValidationError{}

// Validate checks the field values on SysDeptListResp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *SysDeptListResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SysDeptListResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SysDeptListRespMultiError, or nil if none found.
func (m *SysDeptListResp) ValidateAll() error {
	return m.validate(true)
}

func (m *SysDeptListResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, SysDeptListRespValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, SysDeptListRespValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return SysDeptListRespValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return SysDeptListRespMultiError(errors)
	}

	return nil
}

// SysDeptListRespMultiError is an error wrapping multiple validation errors
// returned by SysDeptListResp.ValidateAll() if the designated constraints
// aren't met.
type SysDeptListRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SysDeptListRespMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SysDeptListRespMultiError) AllErrors() []error { return m }

// SysDeptListRespValidationError is the validation error returned by
// SysDeptListResp.Validate if the designated constraints aren't met.
type SysDeptListRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SysDeptListRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SysDeptListRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SysDeptListRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SysDeptListRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SysDeptListRespValidationError) ErrorName() string { return "SysDeptListRespValidationError" }

// Error satisfies the builtin error interface
func (e SysDeptListRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSysDeptListResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SysDeptListRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SysDeptListRespValidationError{}

// Validate checks the field values on SysDeptStoreReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *SysDeptStoreReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SysDeptStoreReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SysDeptStoreReqMultiError, or nil if none found.
func (m *SysDeptStoreReq) ValidateAll() error {
	return m.validate(true)
}

func (m *SysDeptStoreReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetId() != "" {

		if err := m._validateUuid(m.GetId()); err != nil {
			err = SysDeptStoreReqValidationError{
				field:  "Id",
				reason: "value must be a valid UUID",
				cause:  err,
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if m.GetPid() != "" {

		if err := m._validateUuid(m.GetPid()); err != nil {
			err = SysDeptStoreReqValidationError{
				field:  "Pid",
				reason: "value must be a valid UUID",
				cause:  err,
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if _, ok := _SysDeptStoreReq_Type_InLookup[m.GetType()]; !ok {
		err := SysDeptStoreReqValidationError{
			field:  "Type",
			reason: "value must be in list [root child leaf]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetName()); l < 1 || l > 50 {
		err := SysDeptStoreReqValidationError{
			field:  "Name",
			reason: "value length must be between 1 and 50 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Remark

	if _, ok := _SysDeptStoreReq_Status_InLookup[m.GetStatus()]; !ok {
		err := SysDeptStoreReqValidationError{
			field:  "Status",
			reason: "value must be in list [-1 1]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return SysDeptStoreReqMultiError(errors)
	}

	return nil
}

func (m *SysDeptStoreReq) _validateUuid(uuid string) error {
	if matched := _sys_dept_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// SysDeptStoreReqMultiError is an error wrapping multiple validation errors
// returned by SysDeptStoreReq.ValidateAll() if the designated constraints
// aren't met.
type SysDeptStoreReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SysDeptStoreReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SysDeptStoreReqMultiError) AllErrors() []error { return m }

// SysDeptStoreReqValidationError is the validation error returned by
// SysDeptStoreReq.Validate if the designated constraints aren't met.
type SysDeptStoreReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SysDeptStoreReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SysDeptStoreReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SysDeptStoreReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SysDeptStoreReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SysDeptStoreReqValidationError) ErrorName() string { return "SysDeptStoreReqValidationError" }

// Error satisfies the builtin error interface
func (e SysDeptStoreReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSysDeptStoreReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SysDeptStoreReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SysDeptStoreReqValidationError{}

var _SysDeptStoreReq_Type_InLookup = map[string]struct{}{
	"root":  {},
	"child": {},
	"leaf":  {},
}

var _SysDeptStoreReq_Status_InLookup = map[int32]struct{}{
	-1: {},
	1:  {},
}

// Validate checks the field values on SysDeptStoreResp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *SysDeptStoreResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SysDeptStoreResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SysDeptStoreRespMultiError, or nil if none found.
func (m *SysDeptStoreResp) ValidateAll() error {
	return m.validate(true)
}

func (m *SysDeptStoreResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return SysDeptStoreRespMultiError(errors)
	}

	return nil
}

// SysDeptStoreRespMultiError is an error wrapping multiple validation errors
// returned by SysDeptStoreResp.ValidateAll() if the designated constraints
// aren't met.
type SysDeptStoreRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SysDeptStoreRespMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SysDeptStoreRespMultiError) AllErrors() []error { return m }

// SysDeptStoreRespValidationError is the validation error returned by
// SysDeptStoreResp.Validate if the designated constraints aren't met.
type SysDeptStoreRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SysDeptStoreRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SysDeptStoreRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SysDeptStoreRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SysDeptStoreRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SysDeptStoreRespValidationError) ErrorName() string { return "SysDeptStoreRespValidationError" }

// Error satisfies the builtin error interface
func (e SysDeptStoreRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSysDeptStoreResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SysDeptStoreRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SysDeptStoreRespValidationError{}

// Validate checks the field values on SysDeptDelReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SysDeptDelReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SysDeptDelReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SysDeptDelReqMultiError, or
// nil if none found.
func (m *SysDeptDelReq) ValidateAll() error {
	return m.validate(true)
}

func (m *SysDeptDelReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetId()); err != nil {
		err = SysDeptDelReqValidationError{
			field:  "Id",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return SysDeptDelReqMultiError(errors)
	}

	return nil
}

func (m *SysDeptDelReq) _validateUuid(uuid string) error {
	if matched := _sys_dept_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// SysDeptDelReqMultiError is an error wrapping multiple validation errors
// returned by SysDeptDelReq.ValidateAll() if the designated constraints
// aren't met.
type SysDeptDelReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SysDeptDelReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SysDeptDelReqMultiError) AllErrors() []error { return m }

// SysDeptDelReqValidationError is the validation error returned by
// SysDeptDelReq.Validate if the designated constraints aren't met.
type SysDeptDelReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SysDeptDelReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SysDeptDelReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SysDeptDelReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SysDeptDelReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SysDeptDelReqValidationError) ErrorName() string { return "SysDeptDelReqValidationError" }

// Error satisfies the builtin error interface
func (e SysDeptDelReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSysDeptDelReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SysDeptDelReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SysDeptDelReqValidationError{}

// Validate checks the field values on SysDeptDelResp with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SysDeptDelResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SysDeptDelResp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SysDeptDelRespMultiError,
// or nil if none found.
func (m *SysDeptDelResp) ValidateAll() error {
	return m.validate(true)
}

func (m *SysDeptDelResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return SysDeptDelRespMultiError(errors)
	}

	return nil
}

// SysDeptDelRespMultiError is an error wrapping multiple validation errors
// returned by SysDeptDelResp.ValidateAll() if the designated constraints
// aren't met.
type SysDeptDelRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SysDeptDelRespMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SysDeptDelRespMultiError) AllErrors() []error { return m }

// SysDeptDelRespValidationError is the validation error returned by
// SysDeptDelResp.Validate if the designated constraints aren't met.
type SysDeptDelRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SysDeptDelRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SysDeptDelRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SysDeptDelRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SysDeptDelRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SysDeptDelRespValidationError) ErrorName() string { return "SysDeptDelRespValidationError" }

// Error satisfies the builtin error interface
func (e SysDeptDelRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSysDeptDelResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SysDeptDelRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SysDeptDelRespValidationError{}

// Validate checks the field values on SysDeptStatusReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *SysDeptStatusReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SysDeptStatusReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SysDeptStatusReqMultiError, or nil if none found.
func (m *SysDeptStatusReq) ValidateAll() error {
	return m.validate(true)
}

func (m *SysDeptStatusReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetId()); err != nil {
		err = SysDeptStatusReqValidationError{
			field:  "Id",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := _SysDeptStatusReq_Status_InLookup[m.GetStatus()]; !ok {
		err := SysDeptStatusReqValidationError{
			field:  "Status",
			reason: "value must be in list [-1 1]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return SysDeptStatusReqMultiError(errors)
	}

	return nil
}

func (m *SysDeptStatusReq) _validateUuid(uuid string) error {
	if matched := _sys_dept_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// SysDeptStatusReqMultiError is an error wrapping multiple validation errors
// returned by SysDeptStatusReq.ValidateAll() if the designated constraints
// aren't met.
type SysDeptStatusReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SysDeptStatusReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SysDeptStatusReqMultiError) AllErrors() []error { return m }

// SysDeptStatusReqValidationError is the validation error returned by
// SysDeptStatusReq.Validate if the designated constraints aren't met.
type SysDeptStatusReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SysDeptStatusReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SysDeptStatusReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SysDeptStatusReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SysDeptStatusReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SysDeptStatusReqValidationError) ErrorName() string { return "SysDeptStatusReqValidationError" }

// Error satisfies the builtin error interface
func (e SysDeptStatusReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSysDeptStatusReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SysDeptStatusReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SysDeptStatusReqValidationError{}

var _SysDeptStatusReq_Status_InLookup = map[int32]struct{}{
	-1: {},
	1:  {},
}

// Validate checks the field values on SysDeptStatusResp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *SysDeptStatusResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SysDeptStatusResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SysDeptStatusRespMultiError, or nil if none found.
func (m *SysDeptStatusResp) ValidateAll() error {
	return m.validate(true)
}

func (m *SysDeptStatusResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return SysDeptStatusRespMultiError(errors)
	}

	return nil
}

// SysDeptStatusRespMultiError is an error wrapping multiple validation errors
// returned by SysDeptStatusResp.ValidateAll() if the designated constraints
// aren't met.
type SysDeptStatusRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SysDeptStatusRespMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SysDeptStatusRespMultiError) AllErrors() []error { return m }

// SysDeptStatusRespValidationError is the validation error returned by
// SysDeptStatusResp.Validate if the designated constraints aren't met.
type SysDeptStatusRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SysDeptStatusRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SysDeptStatusRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SysDeptStatusRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SysDeptStatusRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SysDeptStatusRespValidationError) ErrorName() string {
	return "SysDeptStatusRespValidationError"
}

// Error satisfies the builtin error interface
func (e SysDeptStatusRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSysDeptStatusResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SysDeptStatusRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SysDeptStatusRespValidationError{}
