// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: shadow/v1/user_message.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 用户-消息信息
type UserMessageInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`               // id
	UserId    string `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`       // 用户ID
	Category  string `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`   // 类别
	Type      string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`           // 类型
	Data      string `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`           // 内容
	Status    int32  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`      // 状态
	CreatedAt string `protobuf:"bytes,7,opt,name=createdAt,proto3" json:"createdAt,omitempty"` // 创建时间
}

func (x *UserMessageInfo) Reset() {
	*x = UserMessageInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shadow_v1_user_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserMessageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMessageInfo) ProtoMessage() {}

func (x *UserMessageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_shadow_v1_user_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMessageInfo.ProtoReflect.Descriptor instead.
func (*UserMessageInfo) Descriptor() ([]byte, []int) {
	return file_shadow_v1_user_message_proto_rawDescGZIP(), []int{0}
}

func (x *UserMessageInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserMessageInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserMessageInfo) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *UserMessageInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UserMessageInfo) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *UserMessageInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UserMessageInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// 请求-用户-消息-创建一条数据
type CreateUserMessageReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`     // 用户ID
	Category string `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"` // 类别
	Type     string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`         // 类型
	Data     string `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`         // 内容
	Status   int32  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`    // 状态
}

func (x *CreateUserMessageReq) Reset() {
	*x = CreateUserMessageReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shadow_v1_user_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUserMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserMessageReq) ProtoMessage() {}

func (x *CreateUserMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_shadow_v1_user_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserMessageReq.ProtoReflect.Descriptor instead.
func (*CreateUserMessageReq) Descriptor() ([]byte, []int) {
	return file_shadow_v1_user_message_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserMessageReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateUserMessageReq) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateUserMessageReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateUserMessageReq) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *CreateUserMessageReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 响应-用户-消息-创建一条数据
type CreateUserMessageReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // id
}

func (x *CreateUserMessageReply) Reset() {
	*x = CreateUserMessageReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shadow_v1_user_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUserMessageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserMessageReply) ProtoMessage() {}

func (x *CreateUserMessageReply) ProtoReflect() protoreflect.Message {
	mi := &file_shadow_v1_user_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserMessageReply.ProtoReflect.Descriptor instead.
func (*CreateUserMessageReply) Descriptor() ([]byte, []int) {
	return file_shadow_v1_user_message_proto_rawDescGZIP(), []int{2}
}

func (x *CreateUserMessageReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// 请求-用户-消息-更新一条数据
type UpdateUserMessageReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`             // id
	UserId   string `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`     // 用户ID
	Category string `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"` // 类别
	Type     string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`         // 类型
	Data     string `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`         // 内容
	Status   int32  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`    // 状态
}

func (x *UpdateUserMessageReq) Reset() {
	*x = UpdateUserMessageReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shadow_v1_user_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateUserMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserMessageReq) ProtoMessage() {}

func (x *UpdateUserMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_shadow_v1_user_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserMessageReq.ProtoReflect.Descriptor instead.
func (*UpdateUserMessageReq) Descriptor() ([]byte, []int) {
	return file_shadow_v1_user_message_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateUserMessageReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateUserMessageReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateUserMessageReq) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *UpdateUserMessageReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UpdateUserMessageReq) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *UpdateUserMessageReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 响应-用户-消息-更新一条数据
type UpdateUserMessageReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateUserMessageReply) Reset() {
	*x = UpdateUserMessageReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shadow_v1_user_message_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateUserMessageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserMessageReply) ProtoMessage() {}

func (x *UpdateUserMessageReply) ProtoReflect() protoreflect.Message {
	mi := &file_shadow_v1_user_message_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserMessageReply.ProtoReflect.Descriptor instead.
func (*UpdateUserMessageReply) Descriptor() ([]byte, []int) {
	return file_shadow_v1_user_message_proto_rawDescGZIP(), []int{4}
}

// 请求-用户-消息-删除多条数据
type DeleteUserMessageReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"` // id集合
}

func (x *DeleteUserMessageReq) Reset() {
	*x = DeleteUserMessageReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shadow_v1_user_message_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteUserMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserMessageReq) ProtoMessage() {}

func (x *DeleteUserMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_shadow_v1_user_message_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserMessageReq.ProtoReflect.Descriptor instead.
func (*DeleteUserMessageReq) Descriptor() ([]byte, []int) {
	return file_shadow_v1_user_message_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteUserMessageReq) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

// 响应-用户-消息-删除多条数据
type DeleteUserMessageReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteUserMessageReply) Reset() {
	*x = DeleteUserMessageReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shadow_v1_user_message_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteUserMessageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserMessageReply) ProtoMessage() {}

func (x *DeleteUserMessageReply) ProtoReflect() protoreflect.Message {
	mi := &file_shadow_v1_user_message_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserMessageReply.ProtoReflect.Descriptor instead.
func (*DeleteUserMessageReply) Descriptor() ([]byte, []int) {
	return file_shadow_v1_user_message_proto_rawDescGZIP(), []int{6}
}

// 请求-用户-消息-单条数据查询
type GetUserMessageInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // id
}

func (x *GetUserMessageInfoReq) Reset() {
	*x = GetUserMessageInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shadow_v1_user_message_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserMessageInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserMessageInfoReq) ProtoMessage() {}

func (x *GetUserMessageInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_shadow_v1_user_message_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserMessageInfoReq.ProtoReflect.Descriptor instead.
func (*GetUserMessageInfoReq) Descriptor() ([]byte, []int) {
	return file_shadow_v1_user_message_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserMessageInfoReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// 响应-用户-消息-单条数据查询
type GetUserMessageInfoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info *UserMessageInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *GetUserMessageInfoReply) Reset() {
	*x = GetUserMessageInfoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shadow_v1_user_message_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserMessageInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserMessageInfoReply) ProtoMessage() {}

func (x *GetUserMessageInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_shadow_v1_user_message_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserMessageInfoReply.ProtoReflect.Descriptor instead.
func (*GetUserMessageInfoReply) Descriptor() ([]byte, []int) {
	return file_shadow_v1_user_message_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserMessageInfoReply) GetInfo() *UserMessageInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

// 请求-用户-消息-列表数据查询
type GetUserMessageListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page     int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`         //页码
	PageSize int32 `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"` //页数
}

func (x *GetUserMessageListReq) Reset() {
	*x = GetUserMessageListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shadow_v1_user_message_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserMessageListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserMessageListReq) ProtoMessage() {}

func (x *GetUserMessageListReq) ProtoReflect() protoreflect.Message {
	mi := &file_shadow_v1_user_message_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserMessageListReq.ProtoReflect.Descriptor instead.
func (*GetUserMessageListReq) Descriptor() ([]byte, []int) {
	return file_shadow_v1_user_message_proto_rawDescGZIP(), []int{9}
}

func (x *GetUserMessageListReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetUserMessageListReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 响应-用户-消息-列表数据查询
type GetUserMessageListReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total int32              `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"` //总数
	List  []*UserMessageInfo `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`    // 列表数据
}

func (x *GetUserMessageListReply) Reset() {
	*x = GetUserMessageListReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shadow_v1_user_message_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserMessageListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserMessageListReply) ProtoMessage() {}

func (x *GetUserMessageListReply) ProtoReflect() protoreflect.Message {
	mi := &file_shadow_v1_user_message_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserMessageListReply.ProtoReflect.Descriptor instead.
func (*GetUserMessageListReply) Descriptor() ([]byte, []int) {
	return file_shadow_v1_user_message_proto_rawDescGZIP(), []int{10}
}

func (x *GetUserMessageListReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetUserMessageListReply) GetList() []*UserMessageInfo {
	if x != nil {
		return x.List
	}
	return nil
}

var File_shadow_v1_user_message_proto protoreflect.FileDescriptor

var file_shadow_v1_user_message_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x73, 0x68, 0x61, 0x64, 0x6f, 0x77, 0x2f, 0x76, 0x31, 0x2f, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09,
	0x73, 0x68, 0x61, 0x64, 0x6f, 0x77, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb3, 0x01, 0x0a, 0x0f, 0x55, 0x73, 0x65, 0x72,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x8a, 0x01,
	0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x28, 0x0a, 0x16, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x9a, 0x01, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x22, 0x18, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x28, 0x0a, 0x14, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x03, 0x69, 0x64, 0x73, 0x22, 0x18, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x27, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x49, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x2e, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x73, 0x68, 0x61, 0x64, 0x6f, 0x77, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69,
	0x6e, 0x66, 0x6f, 0x22, 0x47, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x5f, 0x0a, 0x17,
	0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x2e, 0x0a,
	0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x73, 0x68,
	0x61, 0x64, 0x6f, 0x77, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x32, 0xdc, 0x05,
	0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x8d, 0x01,
	0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x1f, 0x2e, 0x73, 0x68, 0x61, 0x64, 0x6f, 0x77, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x52, 0x65, 0x71, 0x1a, 0x21, 0x2e, 0x73, 0x68, 0x61, 0x64, 0x6f, 0x77, 0x2e, 0x76, 0x31,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x34, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x2e, 0x22,
	0x29, 0x2f, 0x79, 0x61, 0x6e, 0x78, 0x75, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x68, 0x61,
	0x64, 0x6f, 0x77, 0x2f, 0x76, 0x31, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x3a, 0x01, 0x2a, 0x12, 0x8d, 0x01,
	0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x1f, 0x2e, 0x73, 0x68, 0x61, 0x64, 0x6f, 0x77, 0x2e, 0x76, 0x31, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x52, 0x65, 0x71, 0x1a, 0x21, 0x2e, 0x73, 0x68, 0x61, 0x64, 0x6f, 0x77, 0x2e, 0x76, 0x31,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x34, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x2e, 0x22,
	0x29, 0x2f, 0x79, 0x61, 0x6e, 0x78, 0x75, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x68, 0x61,
	0x64, 0x6f, 0x77, 0x2f, 0x76, 0x31, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x3a, 0x01, 0x2a, 0x12, 0x8d, 0x01,
	0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x1f, 0x2e, 0x73, 0x68, 0x61, 0x64, 0x6f, 0x77, 0x2e, 0x76, 0x31, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x52, 0x65, 0x71, 0x1a, 0x21, 0x2e, 0x73, 0x68, 0x61, 0x64, 0x6f, 0x77, 0x2e, 0x76, 0x31,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x34, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x2e, 0x22,
	0x29, 0x2f, 0x79, 0x61, 0x6e, 0x78, 0x75, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x68, 0x61,
	0x64, 0x6f, 0x77, 0x2f, 0x76, 0x31, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x3a, 0x01, 0x2a, 0x12, 0x8b, 0x01,
	0x0a, 0x12, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x20, 0x2e, 0x73, 0x68, 0x61, 0x64, 0x6f, 0x77, 0x2e, 0x76, 0x31,
	0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x22, 0x2e, 0x73, 0x68, 0x61, 0x64, 0x6f, 0x77, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x2f, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x29, 0x12, 0x27, 0x2f, 0x79, 0x61, 0x6e, 0x78, 0x75, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x73, 0x68, 0x61, 0x64, 0x6f, 0x77, 0x2f, 0x76, 0x31, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x8e, 0x01, 0x0a, 0x12,
	0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x20, 0x2e, 0x73, 0x68, 0x61, 0x64, 0x6f, 0x77, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x1a, 0x22, 0x2e, 0x73, 0x68, 0x61, 0x64, 0x6f, 0x77, 0x2e, 0x76, 0x31,
	0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x32, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x2c,
	0x22, 0x27, 0x2f, 0x79, 0x61, 0x6e, 0x78, 0x75, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x68,
	0x61, 0x64, 0x6f, 0x77, 0x2f, 0x76, 0x31, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x2f, 0x6c, 0x69, 0x73, 0x74, 0x3a, 0x01, 0x2a, 0x42, 0x31, 0x5a, 0x2f,
	0x67, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x79, 0x63, 0x33, 0x34, 0x35, 0x2e, 0x74, 0x76, 0x2f,
	0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x79, 0x61, 0x6e, 0x78, 0x75, 0x65, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x73, 0x68, 0x61, 0x64, 0x6f, 0x77, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_shadow_v1_user_message_proto_rawDescOnce sync.Once
	file_shadow_v1_user_message_proto_rawDescData = file_shadow_v1_user_message_proto_rawDesc
)

func file_shadow_v1_user_message_proto_rawDescGZIP() []byte {
	file_shadow_v1_user_message_proto_rawDescOnce.Do(func() {
		file_shadow_v1_user_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_shadow_v1_user_message_proto_rawDescData)
	})
	return file_shadow_v1_user_message_proto_rawDescData
}

var file_shadow_v1_user_message_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_shadow_v1_user_message_proto_goTypes = []interface{}{
	(*UserMessageInfo)(nil),         // 0: shadow.v1.UserMessageInfo
	(*CreateUserMessageReq)(nil),    // 1: shadow.v1.CreateUserMessageReq
	(*CreateUserMessageReply)(nil),  // 2: shadow.v1.CreateUserMessageReply
	(*UpdateUserMessageReq)(nil),    // 3: shadow.v1.UpdateUserMessageReq
	(*UpdateUserMessageReply)(nil),  // 4: shadow.v1.UpdateUserMessageReply
	(*DeleteUserMessageReq)(nil),    // 5: shadow.v1.DeleteUserMessageReq
	(*DeleteUserMessageReply)(nil),  // 6: shadow.v1.DeleteUserMessageReply
	(*GetUserMessageInfoReq)(nil),   // 7: shadow.v1.GetUserMessageInfoReq
	(*GetUserMessageInfoReply)(nil), // 8: shadow.v1.GetUserMessageInfoReply
	(*GetUserMessageListReq)(nil),   // 9: shadow.v1.GetUserMessageListReq
	(*GetUserMessageListReply)(nil), // 10: shadow.v1.GetUserMessageListReply
}
var file_shadow_v1_user_message_proto_depIdxs = []int32{
	0,  // 0: shadow.v1.GetUserMessageInfoReply.info:type_name -> shadow.v1.UserMessageInfo
	0,  // 1: shadow.v1.GetUserMessageListReply.list:type_name -> shadow.v1.UserMessageInfo
	1,  // 2: shadow.v1.UserMessage.CreateUserMessage:input_type -> shadow.v1.CreateUserMessageReq
	3,  // 3: shadow.v1.UserMessage.UpdateUserMessage:input_type -> shadow.v1.UpdateUserMessageReq
	5,  // 4: shadow.v1.UserMessage.DeleteUserMessage:input_type -> shadow.v1.DeleteUserMessageReq
	7,  // 5: shadow.v1.UserMessage.GetUserMessageInfo:input_type -> shadow.v1.GetUserMessageInfoReq
	9,  // 6: shadow.v1.UserMessage.GetUserMessageList:input_type -> shadow.v1.GetUserMessageListReq
	2,  // 7: shadow.v1.UserMessage.CreateUserMessage:output_type -> shadow.v1.CreateUserMessageReply
	4,  // 8: shadow.v1.UserMessage.UpdateUserMessage:output_type -> shadow.v1.UpdateUserMessageReply
	6,  // 9: shadow.v1.UserMessage.DeleteUserMessage:output_type -> shadow.v1.DeleteUserMessageReply
	8,  // 10: shadow.v1.UserMessage.GetUserMessageInfo:output_type -> shadow.v1.GetUserMessageInfoReply
	10, // 11: shadow.v1.UserMessage.GetUserMessageList:output_type -> shadow.v1.GetUserMessageListReply
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_shadow_v1_user_message_proto_init() }
func file_shadow_v1_user_message_proto_init() {
	if File_shadow_v1_user_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_shadow_v1_user_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserMessageInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shadow_v1_user_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUserMessageReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shadow_v1_user_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUserMessageReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shadow_v1_user_message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateUserMessageReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shadow_v1_user_message_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateUserMessageReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shadow_v1_user_message_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteUserMessageReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shadow_v1_user_message_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteUserMessageReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shadow_v1_user_message_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserMessageInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shadow_v1_user_message_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserMessageInfoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shadow_v1_user_message_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserMessageListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shadow_v1_user_message_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserMessageListReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_shadow_v1_user_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shadow_v1_user_message_proto_goTypes,
		DependencyIndexes: file_shadow_v1_user_message_proto_depIdxs,
		MessageInfos:      file_shadow_v1_user_message_proto_msgTypes,
	}.Build()
	File_shadow_v1_user_message_proto = out.File
	file_shadow_v1_user_message_proto_rawDesc = nil
	file_shadow_v1_user_message_proto_goTypes = nil
	file_shadow_v1_user_message_proto_depIdxs = nil
}
