// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: shadow/v1/user_message.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on UserMessageInfo with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *UserMessageInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserMessageInfo with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UserMessageInfoMultiError, or nil if none found.
func (m *UserMessageInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *UserMessageInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for UserId

	// no validation rules for Category

	// no validation rules for Type

	// no validation rules for Data

	// no validation rules for Status

	// no validation rules for CreatedAt

	if len(errors) > 0 {
		return UserMessageInfoMultiError(errors)
	}

	return nil
}

// UserMessageInfoMultiError is an error wrapping multiple validation errors
// returned by UserMessageInfo.ValidateAll() if the designated constraints
// aren't met.
type UserMessageInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserMessageInfoMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserMessageInfoMultiError) AllErrors() []error { return m }

// UserMessageInfoValidationError is the validation error returned by
// UserMessageInfo.Validate if the designated constraints aren't met.
type UserMessageInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserMessageInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserMessageInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserMessageInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserMessageInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserMessageInfoValidationError) ErrorName() string { return "UserMessageInfoValidationError" }

// Error satisfies the builtin error interface
func (e UserMessageInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserMessageInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserMessageInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserMessageInfoValidationError{}

// Validate checks the field values on CreateUserMessageReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateUserMessageReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateUserMessageReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateUserMessageReqMultiError, or nil if none found.
func (m *CreateUserMessageReq) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateUserMessageReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserId

	// no validation rules for Category

	// no validation rules for Type

	// no validation rules for Data

	// no validation rules for Status

	if len(errors) > 0 {
		return CreateUserMessageReqMultiError(errors)
	}

	return nil
}

// CreateUserMessageReqMultiError is an error wrapping multiple validation
// errors returned by CreateUserMessageReq.ValidateAll() if the designated
// constraints aren't met.
type CreateUserMessageReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateUserMessageReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateUserMessageReqMultiError) AllErrors() []error { return m }

// CreateUserMessageReqValidationError is the validation error returned by
// CreateUserMessageReq.Validate if the designated constraints aren't met.
type CreateUserMessageReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateUserMessageReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateUserMessageReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateUserMessageReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateUserMessageReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateUserMessageReqValidationError) ErrorName() string {
	return "CreateUserMessageReqValidationError"
}

// Error satisfies the builtin error interface
func (e CreateUserMessageReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateUserMessageReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateUserMessageReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateUserMessageReqValidationError{}

// Validate checks the field values on CreateUserMessageReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateUserMessageReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateUserMessageReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateUserMessageReplyMultiError, or nil if none found.
func (m *CreateUserMessageReply) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateUserMessageReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return CreateUserMessageReplyMultiError(errors)
	}

	return nil
}

// CreateUserMessageReplyMultiError is an error wrapping multiple validation
// errors returned by CreateUserMessageReply.ValidateAll() if the designated
// constraints aren't met.
type CreateUserMessageReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateUserMessageReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateUserMessageReplyMultiError) AllErrors() []error { return m }

// CreateUserMessageReplyValidationError is the validation error returned by
// CreateUserMessageReply.Validate if the designated constraints aren't met.
type CreateUserMessageReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateUserMessageReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateUserMessageReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateUserMessageReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateUserMessageReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateUserMessageReplyValidationError) ErrorName() string {
	return "CreateUserMessageReplyValidationError"
}

// Error satisfies the builtin error interface
func (e CreateUserMessageReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateUserMessageReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateUserMessageReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateUserMessageReplyValidationError{}

// Validate checks the field values on UpdateUserMessageReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateUserMessageReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateUserMessageReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateUserMessageReqMultiError, or nil if none found.
func (m *UpdateUserMessageReq) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateUserMessageReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for UserId

	// no validation rules for Category

	// no validation rules for Type

	// no validation rules for Data

	// no validation rules for Status

	if len(errors) > 0 {
		return UpdateUserMessageReqMultiError(errors)
	}

	return nil
}

// UpdateUserMessageReqMultiError is an error wrapping multiple validation
// errors returned by UpdateUserMessageReq.ValidateAll() if the designated
// constraints aren't met.
type UpdateUserMessageReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateUserMessageReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateUserMessageReqMultiError) AllErrors() []error { return m }

// UpdateUserMessageReqValidationError is the validation error returned by
// UpdateUserMessageReq.Validate if the designated constraints aren't met.
type UpdateUserMessageReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateUserMessageReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateUserMessageReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateUserMessageReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateUserMessageReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateUserMessageReqValidationError) ErrorName() string {
	return "UpdateUserMessageReqValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateUserMessageReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateUserMessageReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateUserMessageReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateUserMessageReqValidationError{}

// Validate checks the field values on UpdateUserMessageReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateUserMessageReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateUserMessageReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateUserMessageReplyMultiError, or nil if none found.
func (m *UpdateUserMessageReply) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateUserMessageReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return UpdateUserMessageReplyMultiError(errors)
	}

	return nil
}

// UpdateUserMessageReplyMultiError is an error wrapping multiple validation
// errors returned by UpdateUserMessageReply.ValidateAll() if the designated
// constraints aren't met.
type UpdateUserMessageReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateUserMessageReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateUserMessageReplyMultiError) AllErrors() []error { return m }

// UpdateUserMessageReplyValidationError is the validation error returned by
// UpdateUserMessageReply.Validate if the designated constraints aren't met.
type UpdateUserMessageReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateUserMessageReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateUserMessageReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateUserMessageReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateUserMessageReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateUserMessageReplyValidationError) ErrorName() string {
	return "UpdateUserMessageReplyValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateUserMessageReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateUserMessageReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateUserMessageReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateUserMessageReplyValidationError{}

// Validate checks the field values on DeleteUserMessageReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteUserMessageReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteUserMessageReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteUserMessageReqMultiError, or nil if none found.
func (m *DeleteUserMessageReq) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteUserMessageReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return DeleteUserMessageReqMultiError(errors)
	}

	return nil
}

// DeleteUserMessageReqMultiError is an error wrapping multiple validation
// errors returned by DeleteUserMessageReq.ValidateAll() if the designated
// constraints aren't met.
type DeleteUserMessageReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteUserMessageReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteUserMessageReqMultiError) AllErrors() []error { return m }

// DeleteUserMessageReqValidationError is the validation error returned by
// DeleteUserMessageReq.Validate if the designated constraints aren't met.
type DeleteUserMessageReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteUserMessageReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteUserMessageReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteUserMessageReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteUserMessageReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteUserMessageReqValidationError) ErrorName() string {
	return "DeleteUserMessageReqValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteUserMessageReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteUserMessageReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteUserMessageReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteUserMessageReqValidationError{}

// Validate checks the field values on DeleteUserMessageReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteUserMessageReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteUserMessageReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteUserMessageReplyMultiError, or nil if none found.
func (m *DeleteUserMessageReply) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteUserMessageReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return DeleteUserMessageReplyMultiError(errors)
	}

	return nil
}

// DeleteUserMessageReplyMultiError is an error wrapping multiple validation
// errors returned by DeleteUserMessageReply.ValidateAll() if the designated
// constraints aren't met.
type DeleteUserMessageReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteUserMessageReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteUserMessageReplyMultiError) AllErrors() []error { return m }

// DeleteUserMessageReplyValidationError is the validation error returned by
// DeleteUserMessageReply.Validate if the designated constraints aren't met.
type DeleteUserMessageReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteUserMessageReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteUserMessageReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteUserMessageReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteUserMessageReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteUserMessageReplyValidationError) ErrorName() string {
	return "DeleteUserMessageReplyValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteUserMessageReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteUserMessageReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteUserMessageReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteUserMessageReplyValidationError{}

// Validate checks the field values on GetUserMessageInfoReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetUserMessageInfoReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetUserMessageInfoReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetUserMessageInfoReqMultiError, or nil if none found.
func (m *GetUserMessageInfoReq) ValidateAll() error {
	return m.validate(true)
}

func (m *GetUserMessageInfoReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return GetUserMessageInfoReqMultiError(errors)
	}

	return nil
}

// GetUserMessageInfoReqMultiError is an error wrapping multiple validation
// errors returned by GetUserMessageInfoReq.ValidateAll() if the designated
// constraints aren't met.
type GetUserMessageInfoReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetUserMessageInfoReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetUserMessageInfoReqMultiError) AllErrors() []error { return m }

// GetUserMessageInfoReqValidationError is the validation error returned by
// GetUserMessageInfoReq.Validate if the designated constraints aren't met.
type GetUserMessageInfoReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUserMessageInfoReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetUserMessageInfoReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetUserMessageInfoReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetUserMessageInfoReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetUserMessageInfoReqValidationError) ErrorName() string {
	return "GetUserMessageInfoReqValidationError"
}

// Error satisfies the builtin error interface
func (e GetUserMessageInfoReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetUserMessageInfoReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetUserMessageInfoReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUserMessageInfoReqValidationError{}

// Validate checks the field values on GetUserMessageInfoReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetUserMessageInfoReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetUserMessageInfoReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetUserMessageInfoReplyMultiError, or nil if none found.
func (m *GetUserMessageInfoReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetUserMessageInfoReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetInfo()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetUserMessageInfoReplyValidationError{
					field:  "Info",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetUserMessageInfoReplyValidationError{
					field:  "Info",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetInfo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetUserMessageInfoReplyValidationError{
				field:  "Info",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetUserMessageInfoReplyMultiError(errors)
	}

	return nil
}

// GetUserMessageInfoReplyMultiError is an error wrapping multiple validation
// errors returned by GetUserMessageInfoReply.ValidateAll() if the designated
// constraints aren't met.
type GetUserMessageInfoReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetUserMessageInfoReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetUserMessageInfoReplyMultiError) AllErrors() []error { return m }

// GetUserMessageInfoReplyValidationError is the validation error returned by
// GetUserMessageInfoReply.Validate if the designated constraints aren't met.
type GetUserMessageInfoReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUserMessageInfoReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetUserMessageInfoReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetUserMessageInfoReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetUserMessageInfoReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetUserMessageInfoReplyValidationError) ErrorName() string {
	return "GetUserMessageInfoReplyValidationError"
}

// Error satisfies the builtin error interface
func (e GetUserMessageInfoReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetUserMessageInfoReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetUserMessageInfoReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUserMessageInfoReplyValidationError{}

// Validate checks the field values on GetUserMessageListReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetUserMessageListReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetUserMessageListReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetUserMessageListReqMultiError, or nil if none found.
func (m *GetUserMessageListReq) ValidateAll() error {
	return m.validate(true)
}

func (m *GetUserMessageListReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Page

	// no validation rules for PageSize

	if len(errors) > 0 {
		return GetUserMessageListReqMultiError(errors)
	}

	return nil
}

// GetUserMessageListReqMultiError is an error wrapping multiple validation
// errors returned by GetUserMessageListReq.ValidateAll() if the designated
// constraints aren't met.
type GetUserMessageListReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetUserMessageListReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetUserMessageListReqMultiError) AllErrors() []error { return m }

// GetUserMessageListReqValidationError is the validation error returned by
// GetUserMessageListReq.Validate if the designated constraints aren't met.
type GetUserMessageListReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUserMessageListReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetUserMessageListReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetUserMessageListReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetUserMessageListReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetUserMessageListReqValidationError) ErrorName() string {
	return "GetUserMessageListReqValidationError"
}

// Error satisfies the builtin error interface
func (e GetUserMessageListReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetUserMessageListReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetUserMessageListReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUserMessageListReqValidationError{}

// Validate checks the field values on GetUserMessageListReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetUserMessageListReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetUserMessageListReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetUserMessageListReplyMultiError, or nil if none found.
func (m *GetUserMessageListReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetUserMessageListReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Total

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetUserMessageListReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetUserMessageListReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetUserMessageListReplyValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetUserMessageListReplyMultiError(errors)
	}

	return nil
}

// GetUserMessageListReplyMultiError is an error wrapping multiple validation
// errors returned by GetUserMessageListReply.ValidateAll() if the designated
// constraints aren't met.
type GetUserMessageListReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetUserMessageListReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetUserMessageListReplyMultiError) AllErrors() []error { return m }

// GetUserMessageListReplyValidationError is the validation error returned by
// GetUserMessageListReply.Validate if the designated constraints aren't met.
type GetUserMessageListReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUserMessageListReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetUserMessageListReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetUserMessageListReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetUserMessageListReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetUserMessageListReplyValidationError) ErrorName() string {
	return "GetUserMessageListReplyValidationError"
}

// Error satisfies the builtin error interface
func (e GetUserMessageListReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetUserMessageListReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetUserMessageListReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUserMessageListReplyValidationError{}
