syntax = "proto3";

package shadow.v1;

import "google/api/annotations.proto";

option go_package = "gitlab.yc345.tv/backend/yanxue/api/shadow/v1;v1";

//用户操作记录表
service UserOperationLog {
  //用户操作记录表-创建一条数据
  rpc CreateUserOperationLog(CreateUserOperationLogReq) returns (CreateUserOperationLogReply) {
    option (google.api.http) = {
      post: "/yanxue/api/shadow/v1/user_operation_log/create"
      body: "*"
    };
  }
  //用户操作记录表-更新一条数据
  rpc UpdateUserOperationLog(UpdateUserOperationLogReq) returns (UpdateUserOperationLogReply) {
    option (google.api.http) = {
      post: "/yanxue/api/shadow/v1/user_operation_log/update"
      body: "*"
    };
  }
  //用户操作记录表-删除多条数据
  rpc DeleteUserOperationLog(DeleteUserOperationLogReq) returns (DeleteUserOperationLogReply) {
    option (google.api.http) = {
      post: "/yanxue/api/shadow/v1/user_operation_log/delete"
      body: "*"
    };
  }
  //用户操作记录表-单条数据查询
  rpc GetUserOperationLogInfo(GetUserOperationLogInfoReq) returns (GetUserOperationLogInfoReply) {
    option (google.api.http) = {get: "/yanxue/api/shadow/v1/user_operation_log/info"};
  }
  //用户操作记录表-列表数据查询
  rpc GetUserOperationLogList(GetUserOperationLogListReq) returns (GetUserOperationLogListReply) {
    option (google.api.http) = {
      post: "/yanxue/api/shadow/v1/user_operation_log/list"
      body: "*"
    };
  }
}

//用户操作记录表信息
message UserOperationLogInfo {
  string id = 1; // 主键ID（UUID自动生成）
  string operationType = 2; // 操作类型
  string operator = 3; // 操作人
  string oldData = 4; // 旧数据
  string newData = 5; // 新数据
  string createdAt = 6; // 创建时间
  string updatedAt = 7; // 最后更新时间
}

//请求-用户操作记录表-创建一条数据
message CreateUserOperationLogReq {
  string operationType = 1; // 操作类型
  string operator = 2; // 操作人
  string oldData = 3; // 旧数据
  string newData = 4; // 新数据
}

//响应-用户操作记录表-创建一条数据
message CreateUserOperationLogReply {
  string id = 1; // 主键ID（UUID自动生成）
}

//请求-用户操作记录表-更新一条数据
message UpdateUserOperationLogReq {
  string id = 1; // 主键ID（UUID自动生成）
  string operationType = 2; // 操作类型
  string operator = 3; // 操作人
  string oldData = 4; // 旧数据
  string newData = 5; // 新数据
}

//响应-用户操作记录表-更新一条数据
message UpdateUserOperationLogReply {}

//请求-用户操作记录表-删除多条数据
message DeleteUserOperationLogReq {
  repeated string ids = 1; // 主键ID（UUID自动生成）集合
}

//响应-用户操作记录表-删除多条数据
message DeleteUserOperationLogReply {}

//请求-用户操作记录表-单条数据查询
message GetUserOperationLogInfoReq {
  string id = 1; // 主键ID（UUID自动生成）
}

//响应-用户操作记录表-单条数据查询
message GetUserOperationLogInfoReply {
  UserOperationLogInfo info = 1;
}

//请求-用户操作记录表-列表数据查询
message GetUserOperationLogListReq {
  int32 page = 1; //页码
  int32 pageSize = 2; //页数
}

//响应-用户操作记录表-列表数据查询
message GetUserOperationLogListReply {
  int32 total = 1; //总数
  repeated UserOperationLogInfo list = 2; // 列表数据
}
