syntax = "proto3";

package shadow.v1;

import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";
import "validate/validate.proto";

option go_package = "gitlab.yc345.tv/backend/yanxue/api/shadow/v1;v1";

//用户绑定学生
service UserBindStudent {
  //用户绑定学生-创建一条数据
  rpc CreateUserBindStudent(CreateUserBindStudentReq) returns (CreateUserBindStudentReply) {
    option (google.api.http) = {
      post: "/yanxue/api/shadow/v1/user_bind_student/create"
      body: "*"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      parameters: {
        headers: {
          name: "Authorization"
          description: "TOKEN"
          type: STRING
          required: true
        }
      }
    };
  }
  //用户绑定学生-更新一条数据
  rpc UpdateUserBindStudent(UpdateUserBindStudentReq) returns (UpdateUserBindStudentReply) {
    option (google.api.http) = {
      post: "/yanxue/api/shadow/v1/user_bind_student/update"
      body: "*"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      parameters: {
        headers: {
          name: "Authorization"
          description: "TOKEN"
          type: STRING
          required: true
        }
      }
    };
  }
  //用户绑定学生-删除多条数据
  rpc DeleteUserBindStudent(DeleteUserBindStudentReq) returns (DeleteUserBindStudentReply) {
    option (google.api.http) = {
      post: "/yanxue/api/shadow/v1/user_bind_student/delete"
      body: "*"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      parameters: {
        headers: {
          name: "Authorization"
          description: "TOKEN"
          type: STRING
          required: true
        }
      }
    };
  }
  //用户绑定学生-单条数据查询
  rpc GetUserBindStudentInfo(GetUserBindStudentInfoReq) returns (GetUserBindStudentInfoReply) {
    option (google.api.http) = {get: "/yanxue/api/shadow/v1/user_bind_student/info"};
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      parameters: {
        headers: {
          name: "Authorization"
          description: "TOKEN"
          type: STRING
          required: true
        }
      }
    };
  }
  //用户绑定学生-列表数据查询
  rpc GetUserBindStudentList(GetUserBindStudentListReq) returns (GetUserBindStudentListReply) {
    option (google.api.http) = {
      post: "/yanxue/api/shadow/v1/user_bind_student/list"
      body: "*"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      parameters: {
        headers: {
          name: "Authorization"
          description: "TOKEN"
          type: STRING
          required: true
        }
      }
    };
  }
}

//用户绑定学生信息
message UserBindStudentInfo {
  string id = 1; // id
  string userId = 2; // 用户ID
  string studentName = 3; // 学生-名称
  string studentIdentityCard = 4; // 学生-身份证（加密）
  string studentSex = 5; // 学生-性别 (男M,女F)
  int32 studentAge = 6; // 学生-年龄
  string createdAt = 7; // 创建时间
  string updatedAt = 8; // 更新时间
}

//请求-用户绑定学生-创建一条数据
message CreateUserBindStudentReq {
  string userId = 1 [(validate.rules).string = {min_len: 1}]; // 用户ID
  string studentName = 2 [(validate.rules).string = {min_len: 1}]; // 学生-名称
  string studentIdentityCard = 3; // 学生-身份证（加密）
  string studentSex = 4 [(validate.rules).string = {
    in: [
      "M",
      "F"
    ]
  }]; // 学生-性别 (男M,女F)
  int32 studentAge = 5 [(validate.rules).int32 = {gt: 0}]; // 学生-年龄
}

//响应-用户绑定学生-创建一条数据
message CreateUserBindStudentReply {
  string id = 1; // id
}

//请求-用户绑定学生-更新一条数据
message UpdateUserBindStudentReq {
  string id = 1 [(validate.rules).string = {min_len: 1}]; // id
  string userId = 2 [(validate.rules).string = {min_len: 1}]; // 用户ID
  string studentName = 3 [(validate.rules).string = {min_len: 1}]; // 学生-名称
  string studentIdentityCard = 4; // 学生-身份证（加密）
  string studentSex = 5 [(validate.rules).string = {
    in: [
      "M",
      "F"
    ]
  }]; // 学生-性别 (男M,女F)
  int32 studentAge = 6 [(validate.rules).int32 = {gt: 0}]; // 学生-年龄
}

//响应-用户绑定学生-更新一条数据
message UpdateUserBindStudentReply {}

//请求-用户绑定学生-删除多条数据
message DeleteUserBindStudentReq {
  repeated string ids = 1 [(validate.rules).repeated = {min_items: 1}]; // id集合
}

//响应-用户绑定学生-删除多条数据
message DeleteUserBindStudentReply {}

//请求-用户绑定学生-单条数据查询
message GetUserBindStudentInfoReq {
  string id = 1 [(validate.rules).string = {min_len: 1}]; // id
}

//响应-用户绑定学生-单条数据查询
message GetUserBindStudentInfoReply {
  UserBindStudentInfo info = 1;
}

//请求-用户绑定学生-列表数据查询
message GetUserBindStudentListReq {
  string userId = 1 [(validate.rules).string = {min_len: 1}]; // 用户ID
}

//响应-用户绑定学生-列表数据查询
message GetUserBindStudentListReply {
  repeated UserBindStudentInfo list = 1; // 列表数据
}
